declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const UP=`${BASE}/functions/v1/cuhalide-atlas-smart-rag-v9-final-canary`,FALLBACK=`${BASE}/functions/v1/cuhalide-atlas-lexical-rag-v9-internal`,CANDIDATE=`${BASE}/functions/v1/cuhalide-atlas-candidate-search-v4-internal`,EXACT_SERVICE=`${BASE}/functions/v1/cuhalide-atlas-exact-v10-internal`;
const RELEASE='3.0.1',VERSION='9.9.6-public-internal',STATE_KEY='cloudflare_workers_ai_free';
const EXACT=/how many|\bcount\b|number of|多少|几篇|精确统计/i,DOMAIN=/copper|cuprous|halide|iodide|bromide|chloride|铜|碘|溴|氯|structure|结构|space\s*group|空间群|polar|极性|ferroelectric|铁电|emission|luminescen|发光|ste\b|self[- ]?trapped|自陷|exciton|激子|scintillat|闪烁|crown|冠醚|record\s*\d+|记录\s*\d+|CUH-\d{3}-S\d{2}|evidence|证据|release|CuHalide|candidate|候选|database|数据库/i;
const STE=/self[- ]?trapped|\bste\b|自陷|自俘获/i,CUCU=/cu\s*[·.]{1,}\s*cu|cu[-−]\s*cu|cuprophil|铜铜/i,REL=/relation|relationship|cause|universal|compare|different|关系|因果|普遍|比较|对比|不同/i,FERRO=/ferroelectric|铁电/i,POLAR=/\bpolar\b|极性|non[- ]?centrosymmetric|非中心对称/i,EVD=/(?:evidence|证据)\s*[-:：]?\s*D\b/i;
const PHOTOPHYS=/self[- ]?trapped|\bste\b|exciton|emission|luminescen|photolum|plqy|quantum\s*yield|lifetime|scintillat|radiolum|thermochrom|发光|发射|自陷|激子|量子产率|寿命|闪烁|热致变色/i,STRICT_TEMP=/strict[- ]?polar|严格极性|高置信极性/i,TEMP=/temperature|温度|热致|thermochrom/i;
const STRUCT_REQ=/structure\s*(?:\/\s*phase\s*)?(?:record|row)s?|crystallographic\s+record|and\s+(?:its|their)\s+structures?|结构(?:\/相)?记录|结构条目|及其结构|对应结构/i;
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow','x-cuhalide-release':RELEASE,'x-cuhalide-rag-version':VERSION}});
function qlast(b:any){const m=(Array.isArray(b?.messages)?b.messages:[]).filter((x:any)=>x?.role==='user'&&typeof x.content==='string');return String(m.at(-1)?.content||'').trim()}
function protectedQuery(q:string){return !DOMAIN.test(q)||EXACT.test(q)||/(?:record\s*(?:13|54|95|101|123|156|187|205|214|267)|记录\s*(?:13|54|95|101|123|156|187|205|214|267)|CUH-327-S02)/i.test(q)||STE.test(q)&&CUCU.test(q)&&REL.test(q)||FERRO.test(q)&&POLAR.test(q)||EVD.test(q)||STRICT_TEMP.test(q)&&TEMP.test(q)}
function client(req:Request){const x=String(req.headers.get('x-cuhalide-client')||'').toLowerCase();return/^[a-f0-9]{64}$/.test(x)?x:''}
async function sha(s:string){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));return[...b].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function rest(path:string,init:RequestInit={}){const r=await fetch(`${BASE}/rest/v1/${path}`,{...init,headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json',...(init.headers||{})},signal:AbortSignal.timeout(15000)}),raw=await r.text();let x:any;try{x=raw?JSON.parse(raw):null}catch{x={raw}}return{ok:r.ok,status:r.status,x,raw}}
async function state(){const r=await rest(`cuhalide_atlas_rag_provider_state?provider_key=eq.${STATE_KEY}&select=provider_key,state,cooldown_until,reason,metadata,updated_at&limit=1`);return r.ok&&Array.isArray(r.x)&&r.x[0]?r.x[0]:null}
async function writeState(st:string,cool:string|null,reason:string,metadata:any){await rest('cuhalide_atlas_rag_provider_state?on_conflict=provider_key',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify([{provider_key:STATE_KEY,state:st,cooldown_until:cool,reason,metadata,updated_at:new Date().toISOString()}])})}
async function markQuota(detail:string){await writeState('quota_exhausted',new Date(new Date().setUTCHours(24,0,0,0)).toISOString(),'Workers AI free allocation exhausted; deterministic precision fallback enabled.',{paid_overage_authorized:false,fallback:'precision_search_v9',detail:String(detail).slice(0,500)})}
async function markAvailable(){await writeState('available',null,'Workers AI availability verified by successful internal request.',{paid_overage_authorized:false,verified_at:new Date().toISOString()})}
async function rate(req:Request){const c=client(req),fp=c||await sha(`v9.9.6-fallback|${req.headers.get('user-agent')||'internal'}`),r=await rest('rpc/cuhalide_atlas_agent_rate_limit',{method:'POST',body:JSON.stringify({p_fingerprint:fp,p_weight:1})});return r.ok?r.x:{allowed:false}}
async function invoke(url:string,body:any,timeout=80000,c=''){const headers:any={apikey:KEY,authorization:`Bearer ${KEY}`,'content-type':'application/json',accept:'application/json','user-agent':'CuHalide-v9.9.6-internal'};if(c)headers['x-cuhalide-client']=c;const r=await fetch(url,{method:'POST',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(timeout)}),raw=await r.text();let x:any;try{x=JSON.parse(raw)}catch{x={error:raw}}return{status:r.status,ok:r.ok,x,raw}}
async function getUp(){const r=await fetch(UP,{headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','user-agent':'CuHalide-v9.9.6-health'},signal:AbortSignal.timeout(30000)}),x=await r.json().catch(()=>({}));return{r,x}}
function quotaSignal(x:any){return/free allocation|10,000 neurons|used up your daily|neurons/i.test(JSON.stringify(x||{}))}
function quotaNote(q:string){return/[\u3400-\u9fff]/.test(q)?'\n\n> **LLM 状态：** 免费 Workers AI 当前处于额度熔断/恢复探测状态；本答案使用冻结数据库的 lexical/precision 检索与确定性规则，不进行额外 LLM 机理扩写。':'\n\n> **LLM status:** the free Workers AI path is temporarily unavailable. This answer uses frozen lexical/precision retrieval and deterministic rules without additional model interpretation.'}
function liveSection(q:string,c:any[]){const z=/[\u3400-\u9fff]/.test(q),a=[z?'### Live Monitor 候选元数据':'### Live Monitor candidate metadata'];if(!c.length)a.push(z?'- 当前问题未检索到匹配的已筛选候选。':'- No screened candidate matched this query.');for(const x of c)a.push(`- [W:${x.doi||`candidate-${x.candidate_id}`}] ${x.title}${x.year?` (${x.year})`:''} — **${x.review_status}**; ${z?'未审核候选元数据，不参与冻结科学解释。':'unreviewed candidate metadata; it does not support frozen scientific interpretation.'}`);a.push('',z?`> 候选与 release ${RELEASE} 冻结统计隔离。`:`> Candidates are isolated from frozen release ${RELEASE} statistics.`);return'\n\n'+a.join('\n')}
function grainGuard(x:any,q:string){if(!PHOTOPHYS.test(q)||/CUH-\d{3}-S\d{2}/i.test(q)||STRUCT_REQ.test(q)||STRICT_TEMP.test(q)&&TEMP.test(q))return x;const sources=Array.isArray(x?.sources)?x.sources.filter((s:any)=>s?.type!=='structure'):[];const answer=String(x?.answer||'').split('\n').filter(line=>!/^\s*-?\s*\[S:CUH-/i.test(line)).join('\n').replace(/\n{3,}/g,'\n\n');return{...x,answer,sources}}
async function fallback(req:Request,b:any,q:string,alreadyRated=false){if(!alreadyRated){const rl=await rate(req);if(!rl?.allowed)return json({ok:false,error:'Rate limit exceeded',release:RELEASE,version:VERSION,rate_limit:rl},429)}const f=await invoke(FALLBACK,{query:q},25000);if(!f.ok)return json({ok:false,error:'Evidence fallback is unavailable',release:RELEASE,version:VERSION},503);let answer=String(f.x?.answer||'')+quotaNote(q),sources=Array.isArray(f.x?.sources)?f.x.sources:[],trace=[...(f.x?.trace||[])];if(b?.mode==='research'){const c=await invoke(CANDIDATE,{query:q,limit:5},20000),items=c.ok&&Array.isArray(c.x?.items)?c.x.items:[];answer+=liveSection(q,items);sources=[...sources,...items.map((x:any)=>({type:'web',id:x.doi||`candidate-${x.candidate_id}`,candidate_id:x.candidate_id,title:x.title,doi:x.doi||'',url:x.source_url||'',candidate:true,review_status:x.review_status}))]}return json(grainGuard({...f.x,ok:true,answer,sources,trace,provider:'deterministic-lexical-fallback-v9',model:'none',release:RELEASE,version:VERSION,production:false,ai_provider_state:'safe_fallback',fallback_active:true,write_access:false},q),200)}
Deno.serve(async(req:Request)=>{try{
  if(req.method==='GET'){const[{r,x},st]=await Promise.all([getUp(),state()]),quota=st?.state==='quota_exhausted',cool=quota&&st?.cooldown_until&&new Date(st.cooldown_until).getTime()>Date.now(),mode=st?.state==='available'?'available':quota?(cool?'quota_exhausted':'probe_due'):(st?.state||'unknown');return json({...x,ok:r.ok&&x?.ok===true,agent:'CuHalide Atlas Smart RAG quota-aware gateway',version:VERSION,upstream_version:x?.version||'',production:false,provider_circuit:{state:mode,cooldown_until:st?.cooldown_until||null,paid_overage_authorized:false,fallback:'precision_search_v9',auto_recovery_probe:true},checks:{...(x?.checks||{}),quota_circuit_breaker:true,client_isolated_rate_path:true,structure_grain_photophysics_guard:true,explicit_safe_structure_projection_allowed:true,deterministic_exact_service:true}},r.ok&&x?.ok===true?200:503)}
  if(req.method!=='POST')return json({error:'method not allowed'},405);
  const b=await req.json().catch(()=>({})),q=qlast(b),c=client(req);if(!q)return json({error:'user message required'},400);
  const ex=await invoke(EXACT_SERVICE,b,25000,c);if(ex.ok&&ex.x?.matched===true)return json({...ex.x,version:VERSION,exact_service_version:ex.x?.version||'',production:false},200);
  const st=await state(),quota=st?.state==='quota_exhausted',cool=quota&&st?.cooldown_until&&new Date(st.cooldown_until).getTime()>Date.now();if(cool&&!protectedQuery(q))return fallback(req,b,q,false);
  const u=await invoke(UP,b,80000,c);if(u.status===429)return json({...u.x,version:VERSION},429);if(u.ok){let y=grainGuard(u.x,q);if(quotaSignal(y)){await markQuota(JSON.stringify(y).slice(0,500));y.answer=String(y.answer||'')+quotaNote(q);y.ai_provider_state='quota_exhausted'}else if(!protectedQuery(q)&&st?.state!=='available')await markAvailable();return json({...y,version:VERSION,production:false},200)}if(quotaSignal(u.x)||[502,503,504].includes(u.status)){if(quotaSignal(u.x))await markQuota(u.x?.detail||u.raw);return fallback(req,b,q,true)}return json({...u.x,version:VERSION},u.status)
}catch(e){console.error('[v9.9.6-internal-gateway]',e);return json({ok:false,error:'Smart RAG internal gateway unavailable',release:RELEASE,version:VERSION},503)}});
