version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:17"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:47"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope
