declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const UP=`${BASE}/functions/v1/cuhalide-atlas-rag-v9-core-safe-internal`;
const RELEASE='3.0.2',VERSION='9.12.0-v302-core-adapter-internal';
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow','x-cuhalide-release':RELEASE,'x-cuhalide-rag-core-version':VERSION}});
function lastUser(b:any){const ms=Array.isArray(b?.messages)?b.messages:[];return String([...ms].reverse().find((m:any)=>m?.role==='user'&&typeof m.content==='string')?.content||'').trim()}
const R13=/(?:\brecord\s*13\b|记录\s*13|CUH-013-S0[1-4]|pip6Cu10I16|pyr4Cu4Br8|pyr4Cu4I8|pyrCu2Br3)/i,DIM=/dimensionality|dimension|\b[0-3]D\b|zero[- ]dimensional|维度|零维|未解析|unresolved/i;
async function rpc(name:string,body:any={}){const r=await fetch(`${BASE}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:KEY,authorization:`Bearer ${KEY}`,'content-type':'application/json',accept:'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(20000)}),t=await r.text();if(!r.ok)throw Error(`${name} ${r.status}: ${t.slice(0,250)}`);return t?JSON.parse(t):null}
async function upstream(req:Request,body?:string){const r=await fetch(UP,{method:req.method,headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json','x-cuhalide-client':req.headers.get('x-cuhalide-client')||''},body,signal:AbortSignal.timeout(req.method==='GET'?35000:90000)}),t=await r.text();let x:any;try{x=JSON.parse(t)}catch{x={error:'invalid upstream response'}};return{r,x}}
async function structures(ids:string[]){if(!ids.length)return[];const u=new URL(`${BASE}/rest/v1/cuhalide_atlas_public_structures_v302`);u.searchParams.set('structure_id',`in.(${[...new Set(ids)].join(',')})`);u.searchParams.set('select','structure_id,record_id,label,formula,halogen_effective,halogen_scope,halogen_confidence,dimension_class,dimensionality,space_group,point_group,crystal_system,polar,doi,doi_url');u.searchParams.set('order','structure_id.asc');const r=await fetch(u,{headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json'},signal:AbortSignal.timeout(15000)}),t=await r.text();if(!r.ok)throw Error(`structure projection ${r.status}`);return JSON.parse(t)}
function scard(s:any){return{type:'structure',id:s.structure_id,record_id:s.record_id,title:s.label||s.structure_id,formula:s.formula||'',doi:s.doi||'',url:s.doi_url||'',space_group:s.space_group||'',dimensionality:s.dimension_class||s.dimensionality||'',halogen:s.halogen_effective||'Unresolved',halogen_scope:s.halogen_scope||'unresolved',halogen_confidence:s.halogen_confidence||'Unresolved',evidence_scope:'structure identity/crystallography only'}}
function currentText(v:any){return String(v||'').replace(/Release 3\.0\.1/g,'Release 3.0.2').replace(/release 3\.0\.1/g,'release 3.0.2').replace(/frozen release 3\.0\.1/g,'frozen release 3.0.2')}
async function normalize(x:any){const src=Array.isArray(x?.sources)?x.sources:[],ids=src.filter((s:any)=>s?.type==='structure').map((s:any)=>String(s.id||'')).filter(Boolean),rows=await structures(ids),m=new Map(rows.map((s:any)=>[s.structure_id,scard(s)]));const sources=src.map((s:any)=>s?.type==='structure'?(m.get(String(s.id||''))||s):s);return{...x,release:RELEASE,answer:currentText(x?.answer),sources,trace:[...(Array.isArray(x?.trace)?x.trace:[]),{tool:'release_302_compatibility_adapter',args:{article_hash_equivalent_to_301:true,unchanged_structure_hash_equivalent_to_301:true,record13_rehydrated_from_v302_projection:true}}]}}
async function r13(q:string){const rows=await structures(['CUH-013-S01','CUH-013-S02','CUH-013-S03','CUH-013-S04']),zh=/[\u3400-\u9fff]/.test(q),lines=rows.map((s:any)=>`- [S:${s.structure_id}] ${s.label}: **${s.dimension_class||s.dimensionality||'Unresolved'}**`);return{ok:true,release:RELEASE,version:VERSION,provider:'deterministic-release-302-correction',model:'none',answer:[zh?'### Record 13 · release 3.0.2 已固化维度':'### Record 13 dimensionalities in release 3.0.2',...lines,'',zh?'3.0.2 已把这四个已确认修正写入冻结科学快照；历史 3.0.1 归档保持不可变。':'Release 3.0.2 physically incorporates these four confirmed corrections in the frozen scientific snapshot; historical 3.0.1 remains immutable.'].join('\n'),sources:rows.map(scard),trace:[{tool:'release_302_record13_physical_correction',result_count:4}],production:false,write_access:false}}
Deno.serve(async(req:Request)=>{try{if(req.method==='GET'){const[u,h,p]=await Promise.all([upstream(req),rpc('cuhalide_atlas_rag_release_compat_health_v302'),rpc('cuhalide_atlas_public_projection_health_v302')]);const ok=u.r.ok&&u.x?.ok===true&&h?.ok===true&&p?.ok===true;return json({ok,release:RELEASE,version:VERSION,agent:'CuHalide Atlas release-3.0.2 compatibility core adapter',compatibility_engine_version:u.x?.version||'',index:h?.counts||{},checks:{release_302_rag_contract:h?.ok===true,release_302_projection_contract:p?.ok===true,article_content_hash_equivalence:Number(h?.compatibility?.article_hash_mismatches)===0,unchanged_structure_hash_equivalence:Number(h?.compatibility?.unchanged_structure_hash_mismatches)===0,record13_structure_docs_changed:Number(h?.compatibility?.record13_changed_structure_docs)===4,record13_current_erratum_removed:Number(h?.record13?.no_current_erratum)===4,structure_safe_scientific_projection:true},architecture:{retrieval:'release 3.0.2 RAG index validated; unchanged 3.0.1 retrieval engine logic is reused only where content hashes are identical, with v302 structure projection authoritative','record13':'served directly from the physically corrected v302 projection'},write_access:false,production:false},ok?200:503)}if(req.method!=='POST')return json({error:'method not allowed'},405);const body=await req.text();let b:any;try{b=JSON.parse(body)}catch{return json({error:'invalid JSON'},400)}const q=lastUser(b);if(R13.test(q)&&DIM.test(q))return json(await r13(q),200);const u=await upstream(req,body),n=await normalize(u.x);return json({...n,version:VERSION,compatibility_engine_version:u.x?.version||'',production:false},u.r.status)}catch(e){console.error('[v302-core-adapter]',e);return json({ok:false,error:'release 3.0.2 RAG core adapter unavailable',release:RELEASE,version:VERSION},503)}});
