import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import {join,relative} from 'node:path';

const ROOT=fileURLToPath(new URL('../',import.meta.url));
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const BULK_PATTERNS=['*.pdf','*.cif','*.mmcif','*.xlsx','*.xls','*.ods','*.csv','*.tsv','*.parquet','*.feather','*.arrow','*.sqlite','*.sqlite3','*.db','*.jsonl','*.ndjson','*.docx','*.pptx','*.zip','*.7z','*.rar','*.tar','*.tar.gz','*.tgz'];
const BULK_SUFFIXES=BULK_PATTERNS.map(x=>x.slice(1));
const SCAN_SKIP=new Set(['.git','node_modules','.vercel','.supabase','playwright-report','test-results','lighthouse-report']);
function repositoryFiles(dir=ROOT,out=[]){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(entry.isDirectory()&&SCAN_SKIP.has(entry.name))continue;const path=join(dir,entry.name);if(entry.isDirectory())repositoryFiles(path,out);else if(entry.isFile())out.push(path)}return out}
const has=(text,tokens,label='token')=>{for(const token of tokens)assert.ok(text.includes(token),`missing ${label}: ${token}`)};

test('public repository blocks and contains no private or bulk artifact file types',()=>{const ignore=read('.gitignore');for(const pattern of BULK_PATTERNS)assert.ok(ignore.split(/\r?\n/).includes(pattern),`.gitignore must block ${pattern}`);for(const dir of ['private/','private-data/','primary-evidence/','curation-private/','qa-private/'])assert.ok(ignore.split(/\r?\n/).includes(dir),`.gitignore must block ${dir}`);const violations=repositoryFiles().map(path=>relative(ROOT,path).replaceAll('\\','/')).filter(path=>BULK_SUFFIXES.some(suffix=>path.toLowerCase().endsWith(suffix)));assert.deepEqual(violations,[],'public repository source tree must not contain private/bulk artifacts')});

test('prepublication sitemap is rev.10 and deliberately non-enumerating',()=>{const sitemap=read('api/sitemap.js');has(sitemap,["CURRENT_REVISION='10'","SITE='52'","UI='52.0'",'prepublication-non-enumerating','no-store, max-age=0',"CONTENT_DATE='2026-09-24'"],'sitemap token');assert.match(sitemap,/const URLS=\[\{loc:`\$\{PUBLIC_ORIGIN\}\/`,priority:'1\.0'\},\{loc:`\$\{PUBLIC_ORIGIN\}\/motifs`,priority:'0\.9'\}\]/);assert.ok(!sitemap.includes('/article/${'),'sitemap must not enumerate article records');assert.ok(!sitemap.includes('/structure/${'),'sitemap must not enumerate structure records');const runtime=read('supabase/functions/cuhalide-atlas-runtime-contract-v1-public/index.ts');has(runtime,['REV=10',"SITE='52'","UI='52.0'","record_urls_exposed:false","public_routes:['/','/motifs']",'noindex, nofollow, noarchive'],'runtime sitemap token')});

test('rev.10 middleware closes direct legacy current-state ingress paths',()=>{const m=read('middleware.js');for(const route of ['/api/public-data','/api/public-data.js','/api/data','/api/data.js','/api/motifs','/api/motifs.js','/api/meta','/api/meta.js','/api/record','/api/record.js'])assert.ok(m.includes(`'${route}'`),`middleware must cover ${route}`);has(m,["assistantTarget=new URL('/api/ui-r10'","publicDataTarget=new URL('/api/public-data-r9'","motifTarget=new URL('/api/motifs-r9'","metaTarget=new URL('/api/meta-r9'","recordTarget=new URL('/api/record-r9'","REV='10'","UI='52.0'","SITE='52'","PUBLIC_DATA='2.18.0'","PH='1.4.0'","OC='1.2.0'"],'middleware rev10 token')});

test('canonical rev.10 public data is allowlisted and browse-sized',()=>{const adapter=read('api/public-data-r9.js');has(adapter,["REV='10'","VERSION='2.18.0'","PH='1.4.0'","OC='1.2.0'"],'Vercel public-data token');const edge=read('supabase/functions/cuhalide-atlas-public-data-v3/index.ts');has(edge,["VERSION='2.18.0'","REV='10'","PHOTOPHYSICS_CONTRACT='1.4.0'","ORGANIC_COMPONENTS_CONTRACT='1.2.0'",'Current Curated rev.10 resolution layer'],'Supabase public-data token');assert.match(edge,/PUBLIC_ACTIONS=new Set\(/);assert.match(edge,/unknown public action/);assert.match(edge,/Math\.min\(24,/);assert.match(edge,/out\.length>40/);assert.match(edge,/noindex, nofollow, noarchive/);const allowlist=edge.match(/PUBLIC_ACTIONS=new Set\(\[([^\]]+)\]\)/)?.[1]||'';for(const forbidden of ["'export'","'download'","'raw'","'payload'"])assert.ok(!allowlist.includes(forbidden),`${forbidden} must not be a public action`)});

test('Motif and Organic Components projections remain aggregate/fail-closed',()=>{const edge=read('supabase/functions/cuhalide-atlas-public-data-v3/index.ts');has(edge,["public_projection:'motif-atlas-aggregate-v1'",'component_inventory_public:false'],'Motif projection token');assert.ok(!edge.includes('curated_components'),'canonical Motif Atlas must not expose detailed component inventory');const extra=read('supabase/functions/cuhalide-atlas-public-data-v3/organic-components-extra.ts');has(extra,["resolution_status||'terminal_unresolved'",'verified_connectivity','not_applicable','database_organic_structure_state_closed','database_component_connectivity_state_closed','database_component_orphans_clear','raw_primary_files_exposed:false','raw_evidence_locators_exposed:false',"contract_version:'1.2.0'",'Current Curated rev.10 resolution layer'],'Organic Components token')});

test('production record surfaces and browser assets are rev.10 while historical filenames remain compatibility adapters',()=>{const routes=JSON.parse(read('vercel.json'));const rewrites=new Map(routes.rewrites.map(x=>[x.source,x.destination]));assert.equal(rewrites.get('/'),'/api/ui-r10');assert.match(rewrites.get('/article/:id'),/record-r9/);assert.match(rewrites.get('/structure/:id'),/record-r9/);assert.match(rewrites.get('/ui-photophysics-v1.js'),/assets-r10/);assert.match(rewrites.get('/ui-structure-photophysics-v1.js'),/assets-r10/);assert.match(rewrites.get('/organic-components-v1.js'),/assets-r10/);const record=read('api/record-r9.js');has(record,["REV='10'","SITE='52'","UI='52.0'","PUBLIC_DATA='2.18.0'","PH='1.4.0'","OC='1.2.0'"],'record adapter token');const assets=read('api/assets-r10.js');has(assets,['CURRENT_REVISION=10','ui-photophysics-v1.js','ui-structure-photophysics-v1.js','organic-components-v1.js'],'asset adapter token');for(const asset of ['public/ui-photophysics-v1.js','public/ui-structure-photophysics-v1.js','public/organic-components-v1.js']){const src=read(asset);assert.ok(src.includes('CURRENT_REVISION=10'),`${asset} must be natively rev.10`);assert.ok(!src.includes('CURRENT_REVISION=9'),`${asset} must not rely on runtime revision patching`)}});

test('Public Data v2 remains a static retirement stub',()=>{const source=read('supabase/functions/cuhalide-atlas-public-data-v2/index.ts');assert.match(source,/status:'retired'/);assert.match(source,/status:410/);assert.match(source,/noindex, nofollow, noarchive/);assert.match(source,/prepublication-review/);assert.ok(!source.includes('/rest/v1'),'retired v2 must not access the database directly');assert.ok(!source.includes('SUPABASE_SERVICE_ROLE_KEY'),'retired v2 must not possess service credentials')});

test('CuXplore ingress is synchronized to rev.10 and strips caller-controlled parameters',()=>{const vercel=read('api/agent.js');has(vercel,["CURRENT_REVISION='10'","SITE_VERSION='52'","UI_VERSION='52.0'","PUBLIC_DATA_VERSION='2.18.0'","CUXPLORE_VERSION='10.6.0'","SEMANTIC_INDEX_VERSION='10.0.0'","KNOWLEDGE_CONTRACT='1.3.0'","PHOTOPHYSICS_CONTRACT='1.4.0'","ORGANIC_COMPONENTS_CONTRACT='1.2.0'",'service=\'CuXplore\''],'Vercel CuXplore token');assert.match(vercel,/JSON\.stringify\(\{messages\}\)/);assert.ok(!vercel.includes('requestBody(req)'),'Vercel must not forward raw request object');const edge=read('supabase/functions/cuhalide-atlas-research-assistant-v1-public/index.ts');has(edge,["VERSION='10.6.0'","EVIDENCE_VERSION='10.0.0'","CURRENT_REVISION='10'",'DOCS=1322',"PHOTOPHYSICS_CONTRACT='1.4.0'","ORGANIC_COMPONENTS_CONTRACT='1.2.0'","layer:'current-curated-r10'"],'Supabase assistant token');assert.match(edge,/function normalizeBody\(b:any,mode:string\)\{return JSON\.stringify\(\{messages:messages\(b\),mode,depth:'standard'\}\)\}/);assert.match(edge,/noindex, nofollow, noarchive/)});

test('versioned Smart RAG and runtime sources match deployed rev.10 identities',()=>{const rag=read('supabase/functions/cuhalide-atlas-smart-rag-v302-current-public/index.ts');has(rag,["VERSION='10.0.0'","CURRENT_RELEASE='current-curated-r10'",'REV=10','DOCS=1322','cuhalide-atlas-current-rag-r10-unified-internal',"PH='1.4.0'","OC='1.2.0'",'frozen-3.0.2'],'Smart RAG token');const runtime=read('supabase/functions/cuhalide-atlas-runtime-contract-v1-public/index.ts');has(runtime,["PUBLIC_DATA_VERSION='2.18.0'","EVIDENCE_VERSION='10.0.0'","ASSISTANT_VERSION='10.6.0'","PH='1.4.0'","OC='1.2.0'",'REV=10',"SITE='52'","UI='52.0'",'structure_phase_rows)===939','rag_documents)===1322',"layer:'current-curated-r10'",'2026-09-14'],'runtime rev10 token')});
