import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import {join,relative} from 'node:path';

const ROOT=fileURLToPath(new URL('../',import.meta.url));
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const BULK_PATTERNS=['*.pdf','*.cif','*.mmcif','*.xlsx','*.xls','*.ods','*.csv','*.tsv','*.parquet','*.feather','*.arrow','*.sqlite','*.sqlite3','*.db','*.jsonl','*.ndjson','*.docx','*.pptx','*.zip','*.7z','*.rar','*.tar','*.tar.gz','*.tgz'];
const BULK_SUFFIXES=BULK_PATTERNS.map(x=>x.slice(1));
const SCAN_SKIP=new Set(['.git','node_modules','.vercel','.supabase','playwright-report','test-results','lighthouse-report']);
function repositoryFiles(dir=ROOT,out=[]){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(entry.isDirectory()&&SCAN_SKIP.has(entry.name))continue;const path=join(dir,entry.name);if(entry.isDirectory())repositoryFiles(path,out);else if(entry.isFile())out.push(path)}return out}

test('public repository blocks and contains no private or bulk artifact file types',()=>{const ignore=read('.gitignore');for(const pattern of BULK_PATTERNS)assert.ok(ignore.split(/\r?\n/).includes(pattern),`.gitignore must block ${pattern}`);for(const dir of ['private/','private-data/','primary-evidence/','curation-private/','qa-private/'])assert.ok(ignore.split(/\r?\n/).includes(dir),`.gitignore must block ${dir}`);const violations=repositoryFiles().map(path=>relative(ROOT,path).replaceAll('\\','/')).filter(path=>BULK_SUFFIXES.some(suffix=>path.toLowerCase().endsWith(suffix)));assert.deepEqual(violations,[],'public repository source tree must not contain private/bulk artifacts')});

test('prepublication sitemap is rev.9 and deliberately non-enumerating',()=>{const sitemap=read('api/sitemap.js');assert.match(sitemap,/const URLS=\[\{loc:`\$\{PUBLIC_ORIGIN\}\/`,priority:'1\.0'\},\{loc:`\$\{PUBLIC_ORIGIN\}\/motifs`,priority:'0\.9'\}\]/);assert.match(sitemap,/CURRENT_REVISION='9'/);assert.match(sitemap,/SITE='51'/);assert.match(sitemap,/UI='51\.0'/);assert.match(sitemap,/prepublication-non-enumerating/);assert.match(sitemap,/Cache-Control','no-store, max-age=0'/);assert.ok(!sitemap.includes('/article/${'),'sitemap must not enumerate article records');assert.ok(!sitemap.includes('/structure/${'),'sitemap must not enumerate structure records');const runtime=read('supabase/functions/cuhalide-atlas-runtime-contract-v1-public/index.ts');assert.match(runtime,/CURRENT_REVISION=9/);assert.match(runtime,/enumeration:false/);assert.match(runtime,/record_urls_exposed:false/);assert.match(runtime,/route_count:2/);assert.match(runtime,/public_routes:\['\/','\/motifs'\]/);assert.match(runtime,/prepublication_record_sitemap_enumeration_disabled:true/)});

test('rev.9 middleware closes direct legacy current-state ingress paths',()=>{const m=read('middleware.js');for(const route of ['/api/public-data','/api/public-data.js','/api/data','/api/data.js','/api/motifs','/api/motifs.js','/api/meta','/api/meta.js','/api/record','/api/record.js'])assert.ok(m.includes(`'${route}'`),`middleware must cover ${route}`);assert.match(m,/publicDataTarget=new URL\('\/api\/public-data-r9'/);assert.match(m,/motifTarget=new URL\('\/api\/motifs-r9'/);assert.match(m,/metaTarget=new URL\('\/api\/meta-r9'/);assert.match(m,/recordTarget=new URL\('\/api\/record-r9'/);for(const token of ["REV='9'","UI='51.0'","SITE='51'","PUBLIC_DATA='2.17.1'","PH='1.4.0'","OC='1.2.0'"])assert.ok(m.includes(token));assert.match(m,/Legacy \/api\/data route exposes only the minimized public query contract/)});

test('canonical rev.9 public data is allowlisted and clamps browse-sized motif results',()=>{const adapter=read('api/public-data-r9.js');for(const token of ["REV='9'","VERSION='2.17.1'","PH='1.4.0'","OC='1.2.0'"])assert.ok(adapter.includes(token));const edge=read('supabase/functions/cuhalide-atlas-public-data-v3/index.ts');for(const token of ["VERSION='2.17.1'","REV='9'","PHOTOPHYSICS_CONTRACT='1.4.0'","ORGANIC_COMPONENTS_CONTRACT='1.2.0'"])assert.ok(edge.includes(token));assert.match(edge,/PUBLIC_ACTIONS=new Set\(/);assert.match(edge,/unknown public action/);assert.match(edge,/Math\.min\(24,/,'Motif Atlas public result window must be capped at 24');assert.match(edge,/noindex, nofollow, noarchive/);assert.match(edge,/const upstreamHeaders=\{\.\.\.AUTH/,'canonical v3 must authenticate its protected legacy upstream')});

test('canonical Motif Atlas projection is aggregate-only and omits component inventories',()=>{const edge=read('supabase/functions/cuhalide-atlas-public-data-v3/index.ts');assert.match(edge,/function projectMotifAtlas\(atlas,limit=24\)/);assert.match(edge,/public_projection:'motif-atlas-aggregate-v1'/);assert.match(edge,/component_inventory_public:false/);assert.match(edge,/action==='motifs'&&x\?\.atlas\)x\.atlas=projectMotifAtlas\(x\.atlas,motifLimit\)/);assert.ok(!edge.includes('curated_components'),'canonical Motif Atlas must not expose detailed component inventory');assert.ok(!edge.includes('label_derived_component_candidates'),'canonical Motif Atlas must not expose label-derived candidate inventory');assert.match(edge,/out\.length>40/,'organic-component batch lookup must remain capped at 40 structure ids');const allowlist=edge.match(/PUBLIC_ACTIONS=new Set\(\[([^\]]+)\]\)/)?.[1]||'';for(const forbidden of ["'export'","'download'","'raw'","'payload'","'verified'"])assert.ok(!allowlist.includes(forbidden),`${forbidden} must not be a public action`)});

test('Organic Components public projection is database-authoritative and fail-closed',()=>{const extra=read('supabase/functions/cuhalide-atlas-public-data-v3/organic-components-extra.ts');assert.match(extra,/resolution_status\|\|'terminal_unresolved'/);assert.match(extra,/verified_connectivity/);assert.match(extra,/not_applicable/);assert.match(extra,/database_organic_structure_state_closed/);assert.match(extra,/database_component_connectivity_state_closed/);assert.match(extra,/database_component_orphans_clear/);assert.match(extra,/raw_primary_files_exposed:false/);assert.match(extra,/raw_evidence_locators_exposed:false/);assert.match(extra,/contract_version:'1\.2\.0'/)});

test('production record surfaces are rev.9 adapters while historical implementations remain audit-only',()=>{const routes=read('vercel.json');assert.match(routes,/\/article\/:id/);assert.match(routes,/\/structure\/:id/);assert.match(routes,/record-r9/);const record=read('api/record-r9.js');for(const token of ["REV='9'","SITE='51'","UI='51.0'","PUBLIC_DATA='2.17.1'","PH='1.4.0'","OC='1.2.0'"])assert.ok(record.includes(token));const m=read('middleware.js');assert.match(m,/recordTarget=new URL\('\/api\/record-r9'/);assert.ok(fs.existsSync(new URL('../api/record-evidence-current.js',import.meta.url)))});

test('Public Data v2 is retired after migration to canonical Public Data v3',()=>{const source=read('supabase/functions/cuhalide-atlas-public-data-v2/index.ts');assert.match(source,/status:'retired'/);assert.match(source,/status:410/);assert.match(source,/after migration of the active deterministic RAG dependency chain to canonical Public Data v3/);assert.match(source,/noindex, nofollow, noarchive/);assert.match(source,/prepublication-review/);assert.ok(!source.includes('/rest/v1'),'retired v2 must not access the database directly');assert.ok(!source.includes('SUPABASE_SERVICE_ROLE_KEY'),'retired v2 must not possess service credentials');assert.ok(!source.includes('functions/v1/cuhalide-atlas-public-data-v3'),'retired v2 must not remain a proxy alias')});

test('protected Supabase upstreams remain service-role-only in versioned source',()=>{for(const path of ['supabase/functions/cuhalide-atlas-public-data-v302-public/index.ts','supabase/functions/cuhalide-atlas-public-data-v302/index.ts','supabase/functions/cuhalide-atlas-smart-rag-v302-current-public/index.ts','supabase/functions/cuhalide-atlas-smart-rag-v302-public/index.ts']){const source=read(path);assert.match(source,/authorization'\)===`Bearer \$\{(?:KEY|SERVICE)\}`/i,`${path} must require service bearer token`);assert.match(source,/get\('apikey'\)===(?:KEY|SERVICE)/,`${path} must require service apikey`);assert.match(source,/internal upstream requires service authorization/);assert.match(source,/noindex, nofollow, noarchive/)}});

test('obsolete anonymous Supabase compatibility gateways are static 410 retirement stubs',()=>{for(const path of ['supabase/functions/cuhalide-atlas-meta/index.ts','supabase/functions/cuhalide-atlas-meta-v302-stable/index.ts','supabase/functions/cuhalide-atlas-smart-rag/index.ts','supabase/functions/cuhalide-atlas-public-data-v3-scope-canary/index.ts']){const source=read(path);assert.match(source,/status:'retired'/,`${path} must advertise retirement`);assert.match(source,/status:410/,`${path} must return Gone`);assert.match(source,/noindex, nofollow, noarchive/);assert.match(source,/prepublication-review/);assert.ok(!source.includes('/rest/v1'),`${path} retirement stub must not access database`);assert.ok(!source.includes('SUPABASE_SERVICE_ROLE_KEY'),`${path} retirement stub must not possess service credentials`)}});

test('Research Assistant strips caller-controlled parameters and is synchronized to rev.9 at both ingress layers',()=>{const vercel=read('api/agent.js');assert.match(vercel,/JSON\.stringify\(\{messages\}\)/);for(const token of ["CURRENT_REVISION='9'","SITE_VERSION='51'","UI_VERSION='51.0'","PUBLIC_DATA_VERSION='2.17.1'","ASSISTANT_VERSION='10.5.0'","EVIDENCE_VERSION='9.20.0'","PHOTOPHYSICS_CONTRACT='1.4.0'","ORGANIC_COMPONENTS_CONTRACT='1.2.0'"])assert.ok(vercel.includes(token));assert.ok(!vercel.includes('requestBody(req)'),'Vercel must not forward raw request object');const edge=read('supabase/functions/cuhalide-atlas-research-assistant-v1-public/index.ts');assert.match(edge,/function normalizeBody\(b:any,mode:string\)\{return JSON\.stringify\(\{messages:messages\(b\),mode,depth:'standard'\}\)\}/);for(const token of ["VERSION='10.5.0'","EVIDENCE_VERSION='9.20.0'","CURRENT_REVISION='9'",'DOCS=1330',"PHOTOPHYSICS_CONTRACT='1.4.0'","ORGANIC_COMPONENTS_CONTRACT='1.2.0'"])assert.ok(edge.includes(token));assert.ok(!edge.includes('JSON.stringify({...b,messages:'),'Supabase assistant must not spread arbitrary caller fields');assert.match(edge,/noindex, nofollow, noarchive/);assert.match(edge,/PUBLICATION_STATE='prepublication-review'/)});

test('versioned Smart RAG source matches current rev.9 scientific contracts',()=>{const rag=read('supabase/functions/cuhalide-atlas-smart-rag-v302-current-public/index.ts');for(const token of ["VERSION='9.20.0'","CURRENT_RELEASE='current-curated-r9'",'REV=9','DOCS=1330',"PHOTOPHYSICS_CONTRACT='1.4.0'","ORGANIC_COMPONENTS_CONTRACT='1.2.0'",'cuhalide-atlas-current-rag-r9-unified-internal'])assert.ok(rag.includes(token));assert.match(rag,/two_pass_verified_or_verified_no_reported_data/);assert.match(rag,/organic_connectivity_fail_closed:true/);assert.match(rag,/frozen-3\.0\.2/)});

test('versioned runtime source is synchronized to active rev.9 Site 51 contract',()=>{const runtime=read('supabase/functions/cuhalide-atlas-runtime-contract-v1-public/index.ts');for(const token of ["PUBLIC_DATA_VERSION='2.17.1'","EVIDENCE_VERSION='9.20.0'","ASSISTANT_VERSION='10.5.0'","PHOTOPHYSICS_VERSION='1.4.0'","ORGANIC_COMPONENTS_VERSION='1.2.0'",'CURRENT_REVISION=9',"SITE_VERSION='51'","UI_VERSION='51.0'","META_VERSION='51.0'",'rag:1330',"layer:'current-curated-r9'",'frontend v51 active; backend Current Curated rev.9'])assert.ok(runtime.includes(token),`runtime missing ${token}`);for(const stale of ["PUBLIC_DATA_VERSION='2.16.0'","EVIDENCE_VERSION='9.19.0'","ASSISTANT_VERSION='10.4.1'","PHOTOPHYSICS_VERSION='1.3.3'",'CURRENT_REVISION=8',"SITE_VERSION='50'","META_VERSION='50.5'","layer:'current-curated-r8'"])assert.ok(!runtime.includes(stale),`runtime stale ${stale}`)});
