import {test,expect} from '@playwright/test';
const BASE=process.env.CUHALIDE_BASE_URL||'http://127.0.0.1:4173';
test.describe.configure({mode:'serial'});

test('pre-merge production backend rev.7 is ready',async({request})=>{const r=await request.get(`${BASE}/health.json`);expect(r.status()).toBe(200);const x=await r.json();expect(x.ok).toBe(true);expect(x.current_curated.live_revision).toBe(7);expect(x.current_curated.counts).toMatchObject({structure_phase_rows:946,core_included_structure_rows:886,resolved_space_group_rows:710,verified_space_group_rows:684,verified_polar_rows:97,strict_polar_rows:87,strict_polar_articles:54,rag_documents:1329,rag_embedded:1329})});

test('v50 living portal exposes Current Curated rev.7',async({page,request})=>{const source=await request.get(`${BASE}/api/site`);expect(source.status()).toBe(200);const html=await source.text();expect(html).toContain('CUHALIDE_SITE_V50_CURRENT_CURATED_R7');expect(html).toContain('Current Curated rev.7');expect(html).toContain('Curated literature · n=369');expect(html).toContain('Core-Included · n=886');expect(html).toContain('All structure / phase rows · n=946');expect(html).toContain('Resolved structure rows · n = 710');const r=await page.goto(BASE,{waitUntil:'domcontentloaded'});expect(r?.status()).toBe(200);await expect(page.locator('body')).toContainText('19 Aug 2026');await expect(page.locator('body')).toContainText('946');await expect(page.locator('body')).toContainText('886')});

test('runtime health is exact final rev.7 contract',async({request})=>{const r=await request.get(`${BASE}/health.json`);expect(r.status()).toBe(200);const x=await r.json();expect(x).toMatchObject({ok:true,status:'PASS',site_readiness:'PASS'});expect(x.current_curated.live_revision).toBe(7);expect(x.current_curated.current_curated_through).toBe('2026-08-19');expect(x.current_curated.counts).toMatchObject({article_audit_records:383,chemically_included_articles:372,canonical_verified_articles:369,structure_phase_rows:946,core_included_structure_rows:886,resolved_space_group_rows:710,verified_space_group_rows:684,verified_polar_rows:97,strict_polar_rows:87,strict_polar_articles:54,rag_documents:1329,rag_embedded:1329,taxonomy_rows:946});expect(x.motif_atlas).toMatchObject({taxonomy_rows:946,resolved:624,unresolved:322,unresolved_legacy_category_rows:35});expect(x.checks).toMatchObject({frozen_release_contract:true,current_curated_contract:true,motif_taxonomy_contract:true,rag_embeddings_complete:true,local_motif_global_dimension_separation:true})});

test('manifest sitemap and Motif Atlas agree with final rev.7',async({request,page})=>{const m=await request.get(`${BASE}/release-manifest.json`);expect(m.status()).toBe(200);const j=await m.json();expect(j.current_curated).toMatchObject({revision:7,curated_through:'2026-08-19',structure_phase_rows:946,core_included_structure_rows:886,resolved_space_group_rows:710,verified_space_group_rows:684,strict_polar_rows:87,strict_polar_articles:54,rag_documents:1329,motif_resolved_rows:624,motif_unresolved_rows:322});expect(j.runtime).toMatchObject({public_data_version:'2.14.0',smart_rag_version:'9.19.0',research_assistant_version:'10.4.0'});expect(j.frozen_release).toMatchObject({version:'3.0.2',structure_phase_rows:878,immutable:true});const s=await request.get(`${BASE}/sitemap.xml`);expect(s.status()).toBe(200);const xml=await s.text();expect((xml.match(/<url>/g)||[]).length).toBe(1257);const mr=await page.goto(`${BASE}/motifs`,{waitUntil:'domcontentloaded'});expect(mr?.status()).toBe(200);await expect(page.locator('body')).toContainText('624');await expect(page.locator('body')).toContainText('322')});

test('Research Assistant reports 10.4 / 9.19 and complete rev.7 RAG',async({request})=>{const r=await request.get(`${BASE}/api/agent`);expect(r.status()).toBe(200);const x=await r.json();expect(x.assistant_version).toBe('10.4.0');expect(x.version).toBe('9.19.0');expect(x.current_curated).toMatchObject({layer:'current-curated-r7',live_revision:7,curated_through:'2026-08-19',documents:1329,embedded:1329})});

test('final rev.7 structure-truth corrections are exposed at structure grain',async({request})=>{const get=async id=>{const r=await request.get(`${BASE}/api/public-data?action=structure&id=${encodeURIComponent(id)}`);expect(r.status()).toBe(200);return(await r.json()).item};
  const r6a=await get('CUH-006-S01');expect(r6a).toMatchObject({dimensionality:'0D',space_group:'P-1'});expect(r6a.motif_details?.formula).toBe('Cu2I4');const r6b=await get('CUH-006-S02');expect(r6b).toMatchObject({dimensionality:'0D',space_group:'P2/c'});expect(r6b.motif_details?.formula).toBe('Cu2I4');
  const r60a=await get('CUH-060-S01');expect(r60a).toMatchObject({dimensionality:'0D',ccdc_cif:'2870870'});expect(r60a.motif_details?.formula).toBe('Cu3Br7');const r60c=await get('CUH-060-S03');expect(r60c).toMatchObject({dimensionality:'1D',ccdc_cif:'2870868'});expect(r60c.motif_details?.formula).toBe('Cu2Br4');
  const r91=await get('CUH-091-S02');expect(r91).toMatchObject({dimensionality:'1D',space_group:'P21/n',ccdc_cif:'2350403',formula:'C36 H36 Cu3 I6 N3'});expect(r91.motif_details?.formula).toBe('Cu3I6');
  const r104d=await get('CUH-104-S04');expect(r104d.dimensionality).toBe('1D');expect(r104d.motif_details?.formula).toBe('Cu6I8');const r104e=await get('CUH-104-S05');expect(r104e.dimensionality).toBe('2D');expect(r104e.motif_details?.formula).toBe('Cu4I6');
  const cl=await get('CUH-128-S01');expect(cl).toMatchObject({dimensionality:'0D',space_group:'Pna21',polar:'Yes'});expect(cl.motif_details?.formula).toBe('CuCl4');const br=await get('CUH-128-S02');expect(br).toMatchObject({dimensionality:'0D',space_group:'P31c',polar:'Yes'});expect(br.motif_details?.formula).toContain('Cu2Br7');
  const aio=await get('CUH-154-S02');expect(aio.dimensionality).toBe('0D');expect(aio.motif_details?.formula).toBe('Cu3I5');const aio6=await get('CUH-154-S09');expect(aio6.dimensionality).toBe('0D');expect(aio6.motif_details?.formula).toBe('Cu6I8');
  const mixed=await get('CUH-165-S02');expect(mixed.dimensionality).toBe('0D');expect(mixed.motif_details?.formula).toBe('Unresolved');
  const r172a=await get('CUH-172-S01');expect(r172a.dimensionality).toBe('1D');const r172e=await get('CUH-172-S05');expect(r172e.dimensionality).toBe('2D');const r172g=await get('CUH-172-S07');expect(r172g.dimensionality).toBe('3D');expect(r172g.motif_details?.formula).toBe('Unresolved');
  const hmta=await get('CUH-185-S04');expect(hmta.dimensionality).toBe('0D');expect(hmta.motif_details?.formula).toBe('Cu2Br2');for(const id of ['CUH-185-S06','CUH-185-S07']){const x=await get(id);expect(x.dimensionality).toBe('1D');expect(x.motif_details?.formula).toBe('Cu2Br2')}
  for(const id of ['CUH-246-S01','CUH-246-S02']){const x=await get(id);expect(x.dimensionality).toBe('2D');expect(x.space_group).toBe('Aba2')}for(const id of ['CUH-246-S03','CUH-246-S04']){const x=await get(id);expect(x.dimensionality).toBe('0D');expect(x.motif_details?.formula).toBe('Cu4I8')}const chain=await get('CUH-246-S05');expect(chain.dimensionality).toBe('1D');expect(chain.motif_details?.formula).toBe('Cu2I4');
});

test('local motif versus global dimensionality boundaries remain live',async({request})=>{const ask=async content=>{const r=await request.post(`${BASE}/api/agent`,{data:{messages:[{role:'user',content}]}});expect(r.status()).toBe(200);return r.json()};const r377=await ask('List the structures for record 377 and state local motif and global dimensionality.');expect(r377.answer).toContain('CUH-377-S05');expect(r377.answer).toContain('Cu2I2');expect(r377.answer).toContain('1D');const r378=await ask('What are the motif and dimensionality of CUH-378-S01?');expect(r378.answer).toContain('Cu4I4');expect(r378.answer).toContain('1D');const r186=await ask('List the structures for record 186 and distinguish local Cu-X topology from global dimensionality.');expect(r186.answer).toContain('CUH-186-S01');expect(r186.answer).toContain('3D')});

test('review/perspective placeholders stay absent and export stays disabled',async({request})=>{for(const id of ['CUH-244-S01','CUH-305-S01']){const r=await request.post(`${BASE}/api/agent`,{data:{messages:[{role:'user',content:`Show structure ${id}`}]}});expect(r.status()).toBe(200);const x=await r.json();expect(x.matched).toBe(false);expect(x.not_found).toBe(id)}const e=await request.get(`${BASE}/api/export`);expect(e.status()).toBe(410)});

test('rev.7 exact-count and identity boundaries remain deterministic',async({request})=>{const ask=async content=>{const r=await request.post(`${BASE}/api/agent`,{data:{messages:[{role:'user',content}]}});expect(r.status()).toBe(200);return r.json()};const count=await ask('当前 CuHalide Atlas 收录多少篇 canonical verified articles 和多少条结构？');expect(count.answer).toContain('369');expect(count.answer).toContain('946');const dppb=await ask('1,2-bis(diphenylphosphino)benzene 也常叫 dppb 吗？不要和1,4-bis(diphenylphosphino)butane混淆。');expect(dppb.answer).toContain('CUH-382-S04');expect(dppb.answer).toContain('CUH-382-S05');expect(dppb.answer).toContain('1,4-bis(diphenylphosphino)butane');const glass=await ask('DOI 10.1021/acs.cgd.5c01789 的 2g 和 3g 是晶体结构吗？它们有空间群吗？');expect(glass.answer).toContain('amorphous');expect(glass.answer).toContain('CUH-105-S03')});
