import {test,expect} from '@playwright/test';
const BASE=process.env.CUHALIDE_BASE_URL||'http://127.0.0.1:4173';
test.describe.configure({mode:'serial'});

test('pre-merge production backend rev.6 is ready while frontend may remain v50',async({request})=>{const r=await request.get(`${BASE}/health.json`);expect(r.status()).toBe(200);const x=await r.json();expect(x.ok).toBe(true);expect(x.current_curated.live_revision).toBe(6);expect(x.current_curated.counts).toMatchObject({structure_phase_rows:946,core_included_structure_rows:886,verified_space_group_rows:687,strict_polar_rows:85,strict_polar_articles:53,rag_documents:1329,rag_embedded:1329})});

test('v50 living portal exposes Current Curated rev.6',async({page,request})=>{const source=await request.get(`${BASE}/api/site`);expect(source.status()).toBe(200);const html=await source.text();expect(html).toContain('CUHALIDE_SITE_V50_CURRENT_CURATED_R6');expect(html).toContain('Current Curated rev.6');expect(html).toContain('Curated literature · n=369');expect(html).toContain('Core-Included · n=886');expect(html).toContain('All structure / phase rows · n=946');const r=await page.goto(BASE,{waitUntil:'domcontentloaded'});expect(r?.status()).toBe(200);await expect(page.locator('body')).toContainText('18 Aug 2026');await expect(page.locator('body')).toContainText('946');await expect(page.locator('body')).toContainText('886');await expect(page.locator('body')).not.toContainText('Core-Included · n=864')});

test('runtime health is exact rev.6 contract',async({request})=>{const r=await request.get(`${BASE}/health.json`);expect(r.status()).toBe(200);const x=await r.json();expect(x.ok).toBe(true);expect(x.status).toBe('PASS');expect(x.current_curated.live_revision).toBe(6);expect(x.current_curated.counts).toMatchObject({article_audit_records:383,chemically_included_articles:372,canonical_verified_articles:369,structure_phase_rows:946,core_included_structure_rows:886,resolved_space_group_rows:713,verified_space_group_rows:687,verified_polar_rows:100,strict_polar_rows:85,strict_polar_articles:53,rag_documents:1329,rag_embedded:1329,taxonomy_rows:946});expect(x.motif_atlas).toMatchObject({taxonomy_rows:946,resolved:589,unresolved:357,unresolved_legacy_category_rows:35})});

test('manifest, sitemap and Motif Atlas agree with rev.6',async({request,page})=>{const m=await request.get(`${BASE}/release-manifest.json`);expect(m.status()).toBe(200);const j=await m.json();expect(j.current_curated).toMatchObject({revision:6,structure_phase_rows:946,core_included_structure_rows:886,rag_documents:1329});expect(j.frozen_release).toMatchObject({version:'3.0.2',structure_phase_rows:878,immutable:true});const s=await request.get(`${BASE}/sitemap.xml`);expect(s.status()).toBe(200);const xml=await s.text();expect((xml.match(/<url>/g)||[]).length).toBe(1257);const mr=await page.goto(`${BASE}/motifs`,{waitUntil:'domcontentloaded'});expect(mr?.status()).toBe(200);await expect(page.locator('body')).toContainText('946');await expect(page.locator('body')).toContainText('589');await expect(page.locator('body')).toContainText('357')});

test('Research Assistant reports 10.3 / 9.18 and rev.6 full-current RAG',async({request})=>{const r=await request.get(`${BASE}/api/agent`);expect(r.status()).toBe(200);const x=await r.json();expect(x.assistant_version).toBe('10.3.0');expect(x.version).toBe('9.18.0');expect(x.current_curated).toMatchObject({layer:'current-curated-r6',live_revision:6,documents:1329,embedded:1329})});

test('new structure-truth boundaries are live',async({request})=>{const ask=async content=>{const r=await request.post(`${BASE}/api/agent`,{data:{messages:[{role:'user',content}]}});expect(r.status()).toBe(200);return r.json()};const r377=await ask('List the structures for record 377 and state local motif and global dimensionality.');expect(r377.answer).toContain('CUH-377-S05');expect(r377.answer).toContain('Cu2I2');expect(r377.answer).toContain('1D');const r378=await ask('What are the motif and dimensionality of CUH-378-S01?');expect(r378.answer).toContain('Cu4I4');expect(r378.answer).toContain('1D');expect(r378.answer).toContain('Unresolved');const r374=await ask('What is the space group and polarity of CUH-374-S02?');expect(r374.answer).toContain('C2');expect(r374.answer).toContain('polar=Yes')});

test('review/perspective placeholders stay absent and export stays disabled',async({request})=>{for(const id of ['CUH-244-S01','CUH-305-S01']){const r=await request.post(`${BASE}/api/agent`,{data:{messages:[{role:'user',content:`Show structure ${id}`}]}});expect(r.status()).toBe(200);const x=await r.json();expect(x.matched).toBe(false);expect(x.not_found).toBe(id)}const e=await request.get(`${BASE}/api/export`);expect(e.status()).toBe(410)});

test('rev.6 primary-evidence boundaries remain deterministic',async({request})=>{const ask=async content=>{const r=await request.post(`${BASE}/api/agent`,{data:{messages:[{role:'user',content}]}});expect(r.status()).toBe(200);return r.json()};const count=await ask('当前 CuHalide Atlas 收录多少篇 canonical verified articles 和多少条结构？');expect(count.answer).toContain('369');expect(count.answer).toContain('946');const chain=await ask('CUH-381-S01 是一个0D Cu3I5 cluster吗？');expect(chain.answer).toContain('1D');expect(chain.answer).toContain('Cu3I5');expect(chain.answer).toContain('C10H21N2Cu3I5·CH3CN');expect(chain.answer).toContain('C12H25Cu3I5N2');const dppb=await ask('1,2-bis(diphenylphosphino)benzene 也常叫 dppb 吗？不要和1,4-bis(diphenylphosphino)butane混淆。');expect(dppb.answer).toContain('CUH-382-S04');expect(dppb.answer).toContain('CUH-382-S05');expect(dppb.answer).toContain('1,4-bis(diphenylphosphino)butane');const glass=await ask('DOI 10.1021/acs.cgd.5c01789 的 2g 和 3g 是晶体结构吗？它们有空间群吗？');expect(glass.answer).toContain('amorphous');expect(glass.answer).toContain('CUH-105-S03')});
