import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

const BASE=process.env.CUHALIDE_BASE_URL||'http://127.0.0.1:4173';
test.describe.configure({mode:'serial'});
const AXE_TAGS=['wcag2a','wcag2aa','wcag21aa','wcag22aa'];

function header(response,name){return response.headers()[String(name).toLowerCase()]||''}
function assertNoPrivateEvidence(value){const forbiddenKeys=new Set(['source_file','source_sha256','evidence_locator','page_locator','internal_sample_id']);const walk=x=>{if(Array.isArray(x)){for(const y of x)walk(y);return}if(x&&typeof x==='object'){for(const[k,v]of Object.entries(x)){expect(forbiddenKeys.has(k),`private response key exposed: ${k}`).toBe(false);walk(v)}return}if(typeof x==='string')expect(x.toLowerCase()).not.toContain('atlas_internal')};walk(value)}

async function expectCurrentPageMetadata(response,html){
  expect(response.status()).toBe(200);
  expect(header(response,'x-cuhalide-current-curated-revision')).toBe('7');
  expect(html).toContain('<meta name="cuhalide-current-curated-revision" content="7">');
  expect(html).not.toContain('<meta name="cuhalide-current-curated-revision" content="6">');
  expect(html).toContain('current-r7');
  expect(html).toContain('2026-08-19');
  expect(html).not.toContain('current-r3');
}

async function axe(page,label){const results=await new AxeBuilder({page}).withTags(AXE_TAGS).analyze();expect(results.violations,`${label}: ${results.violations.map(v=>`${v.id}:${v.nodes.length}`).join(', ')}`).toEqual([])}
async function expectNoAxeViolations(page,path){const r=await page.goto(`${BASE}${path}`,{waitUntil:'networkidle'});expect(r?.status()).toBe(200);await axe(page,path)}

test('home passes automated WCAG AA scan with no violations',async({page})=>{await expectNoAxeViolations(page,'/')});
test('every interactive portal view passes automated WCAG AA scan',async({page},testInfo)=>{test.skip(testInfo.project.name!=='desktop-chromium','single-project full-view accessibility sweep');await page.goto(BASE,{waitUntil:'networkidle'});for(const route of ['articles','structures','polar','rag','watch','methods','citation']){await page.goto(`${BASE}/#${route}`,{waitUntil:'networkidle'});await expect(page.locator(`.view[data-view="${route}"]`)).toBeVisible();await axe(page,`#${route}`)}});
test('Motif Atlas and public record pages pass automated WCAG AA scans',async({page})=>{await expectNoAxeViolations(page,'/motifs');await expectNoAxeViolations(page,'/article/381');await expectNoAxeViolations(page,'/structure/CUH-378-S01')});

test('public root exposes one current v50/rev.7 provenance contract',async({request})=>{const r=await request.get(BASE);expect(r.status()).toBe(200);expect(header(r,'x-cuhalide-site-version')).toBe('50');expect(header(r,'x-cuhalide-ui-version')).toBe('50.2');expect(header(r,'x-cuhalide-current-curated-revision')).toBe('7');expect(header(r,'x-cuhalide-middleware')).toContain('current-r7');expect(header(r,'last-modified')).toContain('19 Aug 2026');const html=await r.text();expect(html).toContain('CUHALIDE_SITE_V50_CURRENT_CURATED_R7');expect(html).toContain('Current Curated rev.7');expect(html).toContain('All reviewed / audit records · n=383');expect(html).not.toContain('Current Curated rev.6');expect(html).not.toContain('CUHALIDE_SITE_V50_CURRENT_CURATED_R6')});

test('current article and structure pages expose rev.7 machine provenance and verified photophysics when eligible',async({request})=>{const article=await request.get(`${BASE}/article/381`);const articleHtml=await article.text();await expectCurrentPageMetadata(article,articleHtml);expect(header(article,'x-cuhalide-photophysics-contract')).toBe('1.0.1');expect(articleHtml).toContain('Current Curated rev.7');expect(articleHtml).toContain('19 Aug 2026');expect(articleHtml).toContain('10.1021/acs.inorgchem.5c06028');expect(articleHtml).toContain('Photophysics');expect(articleHtml).toContain('Two-pass verified');const structure=await request.get(`${BASE}/structure/CUH-378-S01`);const structureHtml=await structure.text();await expectCurrentPageMetadata(structure,structureHtml);expect(header(structure,'x-cuhalide-photophysics-contract')).toBe('1.0.1');expect(structureHtml).toContain('PyPzPh-CuI');expect(structureHtml).toContain('Cu4I4');expect(structureHtml).toContain('1D')});

test('frozen-origin record keeps archived scientific provenance while site headers remain rev.7',async({request})=>{const r=await request.get(`${BASE}/article/1`);expect(r.status()).toBe(200);expect(header(r,'x-cuhalide-current-curated-revision')).toBe('7');const html=await r.text();expect(html).toContain('archived scientific snapshot 3.0.2');expect(html).toContain('"version":"3.0.2"');expect(html).toContain('"dateModified":"2026-08-11"')});

test('missing record is a branded noindex 404 rather than a backend-outage false positive',async({request})=>{const r=await request.get(`${BASE}/article/999999`);expect(r.status()).toBe(404);expect(header(r,'x-robots-tag')).toContain('noindex');expect(header(r,'cache-control')).toContain('no-store');const html=await r.text();expect(html).toContain('CuHalide Atlas');expect(html).toContain('Record not found');expect(html).toContain('Browse literature')});

test('health endpoint is normalized to the active v50/rev.7 runtime',async({request})=>{const r=await request.get(`${BASE}/health.json`);expect(r.status()).toBe(200);const x=await r.json();expect(x.ok).toBe(true);expect(x.site_version).toBe('50');expect(x.meta_version).toBe('50.3');expect(x.gateway_meta_version).toBe('50.3');expect(x.site_probe_mode).toBe('frontend v50 active; backend rev.7 deterministic contract');expect(x.public_data.version).toBe('2.15.0');expect(x.photophysics).toMatchObject({ok:true,version:'1.0.1',two_pass_gate:true,primary_files_exposed:false,raw_evidence_locators_exposed:false});expect(x.checks.photophysics_contract).toBe(true);expect(x.current_curated.live_revision).toBe(7);expect(x.motif_atlas).toMatchObject({taxonomy_rows:946,resolved:628,unresolved:318,unresolved_legacy_category_rows:35});expect(JSON.stringify(x)).not.toContain('backend rev.6')});

test('Motif Atlas and HEAD metadata stay aligned with rev.7',async({request})=>{const r=await request.get(`${BASE}/motifs`);expect(r.status()).toBe(200);expect(header(r,'x-cuhalide-current-curated-revision')).toBe('7');const html=await r.text();expect(html).toContain('946');expect(html).toContain('628');expect(html).toContain('318');expect(html).toContain('aria-label="Filter motif taxonomy"');expect(html).toContain('Current Curated rev.7');const head=await request.head(`${BASE}/motifs`);expect(head.status()).toBe(200);expect(header(head,'x-cuhalide-current-curated-revision')).toBe('7')});

test('legacy public-data compatibility route cannot reintroduce stale revision metadata',async({request})=>{const legacy=await request.get(`${BASE}/api/data?action=bootstrap`);expect(legacy.status()).toBe(200);expect(header(legacy,'x-cuhalide-public-data-version')).toBe('2.15.0');expect(header(legacy,'x-cuhalide-photophysics-contract')).toBe('1.0.1');expect(header(legacy,'x-cuhalide-current-curated-revision')).toBe('7');expect(header(legacy,'warning')).toContain('Legacy /api/data')});

test('public photophysics contract is two-pass gated and does not expose private evidence',async({request})=>{const health=await request.get(`${BASE}/api/public-data?action=photophysics-health`);expect(health.status()).toBe(200);const h=await health.json();expect(h.ok).toBe(true);expect(h.checks).toMatchObject({invalid_verified_gate:0,raw_primary_files_exposed:false,raw_evidence_locators_exposed:false});const r=await request.get(`${BASE}/api/public-data?action=photophysics&id=375`);expect(r.status()).toBe(200);const x=await r.json();expect(x).toMatchObject({public_state:'verified',two_pass_verified:true});expect(x.counts.samples).toBeGreaterThan(0);assertNoPrivateEvidence(x)});

test('public interfaces remain read-only and private bulk export remains disabled',async({request})=>{const write=await request.post(`${BASE}/api/public-data`,{data:{action:'bootstrap'}});expect(write.status()).toBe(405);const exp=await request.get(`${BASE}/api/export`);expect(exp.status()).toBe(410);const detail=await request.get(`${BASE}/structure/CUH-378-S01`);const html=(await detail.text()).toLowerCase();for(const forbidden of ['evidence_excerpt','evidence_locator','raw_payload','private_path','candidate_score','reason_code','source_file','source_sha256'])expect(html).not.toContain(forbidden)});

test('mobile pages have no horizontal page overflow and navigation remains operable',async({page},testInfo)=>{test.skip(testInfo.project.name!=='mobile-chromium','mobile-only layout check');await page.goto(BASE,{waitUntil:'networkidle'});let widths=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));expect(widths.scroll).toBeLessThanOrEqual(widths.client+1);const menu=page.locator('#menu');await expect(menu).toBeVisible();await expect(menu).toHaveAttribute('aria-expanded','false');await menu.click();await expect(menu).toHaveAttribute('aria-expanded','true');await expect(page.locator('#nav')).toHaveClass(/open/);await page.locator('#nav a[href="#articles"]').click();await expect(menu).toHaveAttribute('aria-expanded','false');await page.goto(`${BASE}/motifs`,{waitUntil:'networkidle'});widths=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));expect(widths.scroll).toBeLessThanOrEqual(widths.client+1)});
