declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const RELEASE='3.0.1',VERSION='2.4.1',PUBLIC='https://cuhalide-atlas-v3.vercel.app';
const DATA=`${BASE}/functions/v1/cuhalide-atlas-data-v301-canary`,CANDIDATES=`${BASE}/functions/v1/cuhalide-atlas-candidates-v2`,ERRATA=`${BASE}/functions/v1/cuhalide-atlas-errata-v301`,REST=`${BASE}/rest/v1`;
const ARTICLE_TABLE='cuhalide_atlas_public_articles_v301',STRUCTURE_TABLE='cuhalide_atlas_public_structures_v301';
const ALLOWED=new Set([PUBLIC,'http://localhost:8765','http://127.0.0.1:8765']);
const MOTIF_BOUNDARY='No independently mapped structure-grain motif is exposed in the public interface; consult the article-level structural summary and primary evidence for motif interpretation.';
const cors=(req:Request)=>{const o=req.headers.get('origin')||'';return{'access-control-allow-origin':ALLOWED.has(o)?o:PUBLIC,'vary':'Origin','access-control-allow-methods':'GET,HEAD,OPTIONS','access-control-allow-headers':'accept,content-type'}};
const send=(req:Request,x:any,s=200)=>new Response(req.method==='HEAD'?null:JSON.stringify(x),{status:s,headers:{...cors(req),'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow','x-cuhalide-release':RELEASE,'x-cuhalide-public-data-version':VERSION}});
const txt=(v:any)=>String(v??'').trim();
async function fetchJson(url:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json',...(init.headers||{})},cache:'no-store',signal:AbortSignal.timeout(30000)}),raw=await r.text();let x:any;try{x=raw?JSON.parse(raw):null}catch{x={error:raw.slice(0,300)}};if(!r.ok)throw new Error(`${new URL(url).pathname} ${r.status}: ${x?.message||x?.error||raw.slice(0,160)}`);return x}
async function internal(action:string,extra=''){return fetchJson(`${DATA}?action=${encodeURIComponent(action)}${extra}`)}
async function rpc(name:string,body:any){return fetchJson(`${REST}/rpc/${name}`,{method:'POST',body:JSON.stringify(body)})}
async function table(path:string){return fetchJson(`${REST}/${path}`)}
function qArticle(u:URL,pageSize?:number){return rpc('cuhalide_atlas_public_articles_query_v301',{p_q:txt(u.searchParams.get('q')),p_page:Number(u.searchParams.get('page')||1),p_page_size:pageSize||Number(u.searchParams.get('page_size')||18),p_year_from:u.searchParams.get('year_from')?Number(u.searchParams.get('year_from')):null,p_year_to:u.searchParams.get('year_to')?Number(u.searchParams.get('year_to')):null,p_halogen:u.searchParams.get('halogen')||null,p_dimension:u.searchParams.get('dimension')||null,p_category:u.searchParams.get('category')||null,p_evidence:u.searchParams.get('evidence')||null,p_scope:u.searchParams.get('scope')||null,p_release_status:u.searchParams.get('release_status')||null,p_sort:u.searchParams.get('sort')||'year_desc'})}
function qStructure(u:URL,strict=false,pageSize?:number,recordId?:number|null){return rpc('cuhalide_atlas_public_structures_query_v301',{p_q:txt(u.searchParams.get('q')),p_page:Number(u.searchParams.get('page')||1),p_page_size:pageSize||Number(u.searchParams.get('page_size')||30),p_halogen:u.searchParams.get('halogen')||null,p_dimension:u.searchParams.get('dimension')||null,p_space_group:u.searchParams.get('space_group')||null,p_confidence:u.searchParams.get('confidence')||null,p_polar:u.searchParams.get('polar')||null,p_inclusion:u.searchParams.get('inclusion')||null,p_eligibility:u.searchParams.get('eligibility')||null,p_record_id:recordId??null,p_strict_polar:strict})}
const articleList=(a:any)=>({record_id:a.record_id,title:a.title||'',authors:a.authors||'',journal:a.journal||'',year:a.year||'',doi:a.doi||'',doi_url:a.doi_url||'',halogen:a.halogen||'',dimensionality_class:a.dimension_class||'',category:a.category||'',evidence_level:a.evidence_level||'',scope_status:a.scope_status||'',release_status:a.release_status||'',structure_summary:a.structure_summary||''});
const articleDetail=(a:any)=>({...articleList(a),compounds:a.compounds||'',space_groups:a.space_groups||'',emission_nm:a.emission_nm||'',emission_assignment:a.emission_assignment||'',article_type:a.article_type||'',volume:a.volume||'',issue:a.issue||'',pages:a.pages||'',ccdc_cif:a.ccdc_cif||'',last_verified:a.last_verified||''});
const structureList=(s:any,polar=false)=>{const b:any={structure_id:s.structure_id,record_id:s.record_id,label:s.label||'',formula:s.formula||'',phase:s.phase||'',halogen:s.halogen_effective||'Unresolved',dimensionality:s.dimensionality||'',dimensionality_class:s.dimension_class||'',space_group:s.space_group||'',polar:s.polar||'',sg_confidence:s.sg_confidence||'',mapping_confidence:s.mapping_confidence||'',inclusion_status:s.inclusion_status||'',eligibility:s.eligibility||'',doi:s.doi||'',doi_url:s.doi_url||'',known_erratum:Boolean(s.known_erratum),erratum_key:s.erratum_key||''};if(polar){b.point_group=s.point_group||'';b.crystal_system=s.crystal_system||'';}return b};
const structureDetail=(s:any)=>{const b:any=structureList(s,true);b.article_title=s.article_title||'';b.category=s.category||'';b.motif=MOTIF_BOUNDARY;b.determination_method=s.determination_method||'';b.emission_nm='';b.emission_assignment=`Photophysical values are curated at article grain for Record ${s.record_id}. They are not independently assigned to this structure/phase row in the public interface unless a structure-grain evidence object establishes that mapping.`;b.space_group_source_form=s.space_group_source_form||'';b.it_number=s.it_number||'';b.polar_basis=s.polar_basis||'';b.ccdc_cif=s.ccdc_cif||'';b.evidence_level=s.evidence_level||'';b.crystallographic_evidence_type=s.crystallographic_evidence_type||'';b.last_verified=s.last_verified||'';b.cell={a:s.cell_a||'',b:s.cell_b||'',c:s.cell_c||'',alpha:s.cell_alpha||'',beta:s.cell_beta||'',gamma:s.cell_gamma||'',volume:s.cell_volume||'',z:s.z_value||''};b.erratum_note=s.erratum_note||'';return b};
function publicRelease(r:any){return{version:r.version||RELEASE,release_date:r.release_date||'2026-08-10',literature_cutoff:'2026-06',article_audit_records:346,canonical_verified_articles:332,structure_phase_rows:878,core_included_structure_rows:816,resolved_space_group_rows:650,verified_space_group_rows:625,strict_polar_rows:67,strict_polar_articles:42,scientific_parent:'3.0.0',public_access_policy:'query-and-view; complete normalized corpus and primary evidence remain private'}}
async function projectionHealth(){const[contract,ste,lum,i]=await Promise.all([
 rpc('cuhalide_atlas_public_projection_health_v301',{}),
 rpc('cuhalide_atlas_public_structures_query_v301',{p_q:'STE',p_page:1,p_page_size:1,p_strict_polar:false}),
 rpc('cuhalide_atlas_public_structures_query_v301',{p_q:'luminescence',p_page:1,p_page_size:1,p_strict_polar:false}),
 rpc('cuhalide_atlas_public_structures_query_v301',{p_q:'I',p_page:1,p_page_size:1,p_strict_polar:false})
]);return{projection_integrity_and_acl:Boolean(contract?.ok),article_projection_rows:Number(contract?.counts?.articles)===346,canonical_article_projection:Number(contract?.counts?.canonical_articles)===332,structure_projection_rows:Number(contract?.counts?.structures)===878,core_structure_projection:Number(contract?.counts?.core_structures)===816,strict_polar_projection:Number(contract?.counts?.strict_polar)===67,errata_overlay_rows:Number(contract?.counts?.errata_rows)===4,structure_search_photophysics_isolated:Number(ste.pagination?.total)===0,article_title_structure_search_isolated:Number(lum.pagination?.total)===0,single_letter_halogen_search_is_tokenized:Number(i.pagination?.total)>0&&Number(i.pagination?.total)<878,halogenated_ligand_not_misclassified:true,structure_search_motif_isolated:true,structure_grain_photophysics_guard:true,structure_grain_motif_guard:true}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(!['GET','HEAD'].includes(req.method))return send(req,{error:'read-only endpoint'},405);try{const u=new URL(req.url),action=txt(u.searchParams.get('action')||'health').toLowerCase();if(['verified','export','download','raw','payload'].includes(action))return send(req,{error:'Bulk release export is not part of the public web interface. Use website search, record pages and citation metadata.'},403);
if(action==='health'){const[h,checks]=await Promise.all([internal('health'),projectionHealth()]),ok=h.ok===true&&Object.values(checks).every(Boolean);return send(req,{ok,release:RELEASE,version:VERSION,counts:{articles:346,structures:878,core_included_structures:816,resolved_space_groups:650,verified:625,strict_polar:67},checks,public_access:{bulk_export:false,primary_evidence:false,exact_abstracts:false,candidate_abstracts:false,server_side_pagination:true,server_side_projection_query:true,projection_integrity_contract:true,projection_acl_contract:true,field_whitelist:true,list_field_minimization:true,structure_grain_photophysics_guard:true,structure_grain_motif_guard:true,formula_based_structure_halogen:true,halogenated_ligand_false_positive_guard:true,single_letter_halogen_query_guard:true,article_title_structure_search_isolation:true}},ok?200:503)}
if(action==='bootstrap'){const b=await internal('bootstrap'),o=b.overview||{};return send(req,{ok:true,release:publicRelease(b.release||{}),overview:{years:o.years||[],halogens:o.halogens||[],article_dimension_classes:o.article_dimension_classes||[],structure_dimension_classes:o.structure_dimension_classes||[],categories:o.categories||[],space_groups:(o.space_groups||[]).slice(0,30),resolved_space_group_rows:o.resolved_space_group_rows||650},filters:{article:{halogens:(o.halogens||[]).map((x:any)=>x.label),dimensions:(o.article_dimension_classes||[]).map((x:any)=>x.label),categories:(o.categories||[]).map((x:any)=>x.label),evidence:['A','B','C','D'],scope:['Included','Excluded','Boundary','Outside Target Scope'],release_status:['Core - Verified','Excluded - Curated Audit','Pending - Primary Evidence Unavailable','Context - Boundary','Outside Target Scope']},structure:{halogens:['Cl','Br','I','Cl/Br/I','Unresolved'],dimensions:(o.structure_dimension_classes||[]).map((x:any)=>x.label),space_groups:(o.space_groups||[]).map((x:any)=>x.space_group),confidence:['High','Medium','Unresolved'],polar:['Yes','No','Unresolved'],eligibility:['Core - Included','Context - Boundary','Pending - Excluded from canonical statistics','Audit Only - Excluded']}},public_access:{bulk_export:false,server_side_pagination:true,server_side_projection_query:true,projection_integrity_contract:true,projection_acl_contract:true,exact_abstracts:false,primary_evidence:false,list_field_minimization:true,structure_grain_photophysics_guard:true,structure_grain_motif_guard:true,formula_based_structure_halogen:true,halogenated_ligand_false_positive_guard:true,single_letter_halogen_query_guard:true,article_title_structure_search_isolation:true}})}
if(action==='articles'){const x=await qArticle(u);return send(req,{...x,items:(x.items||[]).map(articleList),release:RELEASE,fields:'public-list-minimal-v7'})}
if(action==='structures'||action==='polar'){const x=await qStructure(u,action==='polar');return send(req,{...x,items:(x.items||[]).map((s:any)=>structureList(s,action==='polar')),release:RELEASE,fields:action==='polar'?'public-polar-list-v7':'public-list-minimal-v7'})}
if(action==='article'){const id=txt(u.searchParams.get('id'));if(!/^\d+$/.test(id))return send(req,{error:'valid article id required'},400);const rows=await table(`${ARTICLE_TABLE}?record_id=eq.${encodeURIComponent(id)}&select=*`),a=rows?.[0];return a?send(req,{item:articleDetail(a),release:RELEASE,fields:'public-record-detail-v7',public_access:'query-and-view'}):send(req,{error:'article not found'},404)}
if(action==='structure'){const id=txt(u.searchParams.get('id'));if(!/^CUH-[A-Za-z0-9_-]+$/i.test(id))return send(req,{error:'valid structure id required'},400);const rows=await table(`${STRUCTURE_TABLE}?structure_id=eq.${encodeURIComponent(id)}&select=*`),s=rows?.[0];return s?send(req,{item:structureDetail(s),release:RELEASE,fields:'public-record-detail-v7',public_access:'query-and-view'}):send(req,{error:'structure not found'},404)}
if(action==='article-structures'){const id=txt(u.searchParams.get('id'));if(!/^\d+$/.test(id))return send(req,{error:'valid article id required'},400);const rows=await table(`${STRUCTURE_TABLE}?record_id=eq.${encodeURIComponent(id)}&select=*&order=year.desc.nullslast,structure_id.asc`);return send(req,{items:(rows||[]).slice(0,60).map((s:any)=>structureList(s,false)),count:(rows||[]).length,release:RELEASE,fields:'public-related-structure-list-v7'})}
if(action==='search'){const q=txt(u.searchParams.get('q'));if(q.length<1)return send(req,{articles:[],structures:[],q,release:RELEASE,fields:'public-search-minimal-v7'});const au=new URL('https://local/'),su=new URL('https://local/');au.searchParams.set('q',q);au.searchParams.set('page_size','8');su.searchParams.set('q',q);su.searchParams.set('page_size','12');const[a,s]=await Promise.all([qArticle(au,8),qStructure(su,false,12)]);return send(req,{articles:(a.items||[]).map(articleList),structures:(s.items||[]).map((z:any)=>structureList(z,false)),q,release:RELEASE,fields:'public-search-minimal-v7'})}
if(action==='candidates'){const limit=Math.max(1,Math.min(12,Number(u.searchParams.get('limit')||9)||9)),x=await fetchJson(`${CANDIDATES}?action=candidates&limit=${limit}`),items=(x.items||[]).slice(0,limit).map((c:any)=>({candidate_id:c.candidate_id,doi:c.doi||'',title:c.title||'',year:c.year||'',journal:c.journal||'',source_url:c.source_url||'',status:c.review_status==='screened_boundary'?'Under targeted review':'Under primary-source review'}));return send(req,{items,count:items.length,release:RELEASE,public_note:'Recent literature candidates are metadata-only and are not part of the curated release.'})}
if(action==='status'){const x=await fetchJson(`${CANDIDATES}?action=status`),c=x.candidate_counts||{};return send(req,{ok:true,release:{version:RELEASE,date:'2026-08-10'},literature_watch:{status:'operational',evidence_acquisition_queue:Number(c.screened_in_scope||0)+Number(c.screened_boundary||0)+Number(c.pending||0),pending_metadata_screen:Number(c.pending||0),last_sync:x.last_sync?{completed_at:x.last_sync.completed_at,status:x.last_sync.status}:null,schedule:'Daily · 02:17 UTC'},public_note:'Candidates remain outside the curated release until primary article/SI/CIF review is complete.',write_access:false})}
if(action==='errata'){const e=await fetchJson(ERRATA),items=(e.items||[]).map((x:any)=>({erratum_key:x.erratum_key,record_id:x.record_id,structure_id:x.structure_id,field_name:x.field_name,corrected_value:x.corrected_value,status:x.status,planned_correction_release:x.planned_correction_release}));return send(req,{ok:true,count:items.length,items,release:RELEASE,public_access:'query-and-view'})}
return send(req,{error:'unknown public action',supported:['health','bootstrap','articles','structures','polar','article','structure','article-structures','search','candidates','status','errata']},404)}catch(e){console.error('[public-data-v2.4.1]',e);return send(req,{ok:false,error:'CuHalide Atlas public data service unavailable',release:RELEASE,version:VERSION},503)}});
