declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const UP=`${BASE}/functions/v1/cuhalide-atlas-public-data-v302`,RELEASE='3.0.2',VERSION='2.13.0',REV='6';
const AUTH={apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json'};
const REQUEST_TIMEOUT_MS=3500,RETRIES=2,RETRY_DELAY_MS=120;const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));type Snapshot={status:number;headers:Headers;raw:string};
function internal(req:Request){return req.headers.get('authorization')===`Bearer ${KEY}`&&req.headers.get('apikey')===KEY}
function hdr(ct='application/json; charset=utf-8'){return{'content-type':ct,'cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow, noarchive','x-cuhalide-release':RELEASE,'x-cuhalide-public-data-version':VERSION,'x-cuhalide-public-access':'internal-upstream','x-cuhalide-current-curated-revision':REV,'x-cuhalide-endpoint-state':'internal-upstream'}}
const send=(req:Request,x:any,s=200)=>new Response(req.method==='HEAD'?null:JSON.stringify(x),{status:s,headers:hdr()});
async function fetchSnapshot(url:string,init:RequestInit={},timeoutMs=REQUEST_TIMEOUT_MS):Promise<Snapshot>{let last:Snapshot|null=null,lastError:any=null;for(let attempt=0;attempt<RETRIES;attempt++){try{const r=await fetch(url,{...init,signal:AbortSignal.timeout(timeoutMs)}),method=String(init.method||'GET').toUpperCase(),raw=method==='HEAD'?'':await r.text(),snap={status:r.status,headers:r.headers,raw};last=snap;if(r.status<500||attempt===RETRIES-1)return snap}catch(e){lastError=e;if(attempt===RETRIES-1){if(last)return last;throw e}}await sleep(RETRY_DELAY_MS)}if(last)return last;throw lastError||Error('upstream request failed')}
async function requestJson(url:string,init:RequestInit={}){const s=await fetchSnapshot(url,init),raw=s.raw;let x:any;try{x=raw?JSON.parse(raw):null}catch{x={error:raw.slice(0,300)}}if(s.status<200||s.status>=300)throw Error(`${new URL(url).pathname} ${s.status}: ${x?.message||x?.error||raw.slice(0,180)}`);return x}
async function rest(path:string){return requestJson(`${BASE}/rest/v1/${path}`,{headers:AUTH})}
async function rpc(name:string,body:any){return requestJson(`${BASE}/rest/v1/rpc/${name}`,{method:'POST',headers:AUTH,body:JSON.stringify(body)})}
async function state(){const rows=await rest('cuhalide_atlas_current_curated_state?state_key=eq.current&select=*&limit=1');return rows?.[0]||null}
async function coverage(){const rows=await rest('cuhalide_atlas_current_curated_articles?qc_status=eq.passed&select=coverage_class');let coverage_backfills=0,post_cutoff_additions=0;for(const z of rows||[]){if(z.coverage_class==='coverage_backfill')coverage_backfills++;else if(z.coverage_class==='post_cutoff_addition')post_cutoff_additions++}return{coverage_backfills,post_cutoff_additions}}
function currentMeta(cc:any,c:any){return{...c,live_revision:Number(cc?.live_revision||6),curated_through:String(cc?.current_curated_through||'2026-08-18'),architecture:'full-current-atomic-structure-snapshot'}}
function patchTemporal(x:any,c:any,cc:any){const p=currentMeta(cc,c);if(x?.temporal_scope?.current_curated)x.temporal_scope.current_curated={...x.temporal_scope.current_curated,...p};if(x?.current_curated?.temporal_scope?.current_curated)x.current_curated.temporal_scope.current_curated={...x.current_curated.temporal_scope.current_curated,...p};if(x?.current_curated?.current_state)x.current_curated.current_state={...x.current_curated.current_state,live_revision:p.live_revision,current_curated_through:p.curated_through};return x}
function patchArchitecture(x:any,action:string){const patch=(o:any)=>{if(!o||typeof o!=='object')return;o.current_curated_overlay=false;o.current_curated_full_snapshot=true;o.full_current_atomic_structure_snapshot=true};patch(x?.public_access);patch(x?.current_curated?.public_access);if(x?.current_curated&&typeof x.current_curated==='object')x.current_curated.architecture='full-current-atomic-structure-snapshot';if(action==='current-curated')x.public_note='Current Curated rev.6 is a primary-evidence-reviewed full current article/atomic-structure snapshot anchored to immutable Frozen Release 3.0.2; corrections and new peer-reviewed additions do not rewrite the frozen snapshot.';return x}
async function loadStructureEnrichment(id:string){const[tax,comps]=await Promise.all([rest(`cuhalide_atlas_structure_taxonomy?structure_id=eq.${encodeURIComponent(id)}&qc_status=eq.passed&select=primary_category,motif_formula,motif_geometry,motif_basis,normalization_confidence,identity_key,normalization_note&limit=1`),rest(`cuhalide_atlas_structure_organic_components?structure_id=eq.${encodeURIComponent(id)}&qc_status=eq.passed&select=display_name,abbreviation,role,donor_atoms,evidence_basis,normalization_confidence&order=role.asc,display_name.asc`)]);return{tax,comps}}
function applyStructureEnrichment(x:any,e:any){if(!x?.item||!e)return x;const t=e.tax?.[0];x.item.motif_details=t?{formula:t.motif_formula,geometry:t.motif_geometry,basis:t.motif_basis,confidence:t.normalization_confidence,identity_key:t.identity_key,normalization_note:t.normalization_note||''}:{formula:'Unresolved',geometry:'Unresolved',basis:'No defensible structure-level motif mapping available.',confidence:'Unresolved',identity_key:'',normalization_note:''};x.item.motif=t&&t.motif_formula&&t.motif_formula!=='Unresolved'?`${t.motif_formula}${t.motif_geometry&&t.motif_geometry!=='Unresolved'?` — ${t.motif_geometry}`:''}`:'Unresolved';x.item.organic_components=(e.comps||[]).map((c:any)=>({name:c.display_name,abbreviation:c.abbreviation||'',role:c.role,donor_atoms:c.donor_atoms||'',confidence:c.normalization_confidence,evidence_basis:c.evidence_basis||''}));return x}
async function fetchCore(incoming:URL,req:Request){const u=new URL(UP);for(const[k,v]of incoming.searchParams.entries())u.searchParams.append(k,v);return fetchSnapshot(u.toString(),{method:req.method,headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:req.headers.get('accept')||'application/json','user-agent':'CuHalide-Atlas-Public-Data-v302-Public/2.13.0'}})}
Deno.serve(async(req:Request)=>{if(!internal(req))return send(req,{ok:false,error:'internal upstream requires service authorization'},401);if(!['GET','HEAD'].includes(req.method))return send(req,{error:'read-only endpoint'},405);try{const incoming=new URL(req.url),action=String(incoming.searchParams.get('action')||'health').toLowerCase();if(action==='motifs'){const cat0=String(incoming.searchParams.get('category')||'').trim(),category=/^ionic$/i.test(cat0)?'Hybrid Ionic':cat0||null;const[cc,c,atlas]=await Promise.all([state(),coverage(),rpc('cuhalide_atlas_motif_atlas_v1',{p_category:category,p_motif:String(incoming.searchParams.get('motif')||'').trim()||null,p_component:String(incoming.searchParams.get('component')||'').trim()||null,p_limit:Math.max(1,Math.min(500,Number(incoming.searchParams.get('limit')||100)||100))})]),p=currentMeta(cc,c);return send(req,{ok:true,release:RELEASE,version:VERSION,current_curated_revision:p.live_revision,curated_through:p.curated_through,architecture:p.architecture,atlas,public_note:'Motif Atlas separates article reports, crystallographic determinations, normalized reported identities, primary-evidence curated organic components, and legacy label-derived candidates. Local Cu-X motif and global connectivity dimensionality are distinct axes. Fractional/mixed-occupancy labels remain motif-unresolved unless independently mapped at structure grain.'})}if(req.method==='HEAD'){const core=await fetchCore(incoming,req);return new Response(null,{status:core.status,headers:hdr(core.headers.get('content-type')||undefined)})}const structureId=String(incoming.searchParams.get('id')||''),corePromise=fetchCore(incoming,req),contextPromise=Promise.all([state(),coverage()]),enrichPromise=action==='structure'&&/^CUH-[A-Za-z0-9_-]+$/i.test(structureId)?loadStructureEnrichment(structureId):Promise.resolve(null),[core,[cc,c],enrichment]=await Promise.all([corePromise,contextPromise,enrichPromise]),raw=core.raw;let x:any;try{x=JSON.parse(raw)}catch{return new Response(raw,{status:core.status,headers:hdr(core.headers.get('content-type')||'text/plain; charset=utf-8')})}x.version=VERSION;x.current_curated_revision=Number(cc?.live_revision||6);x.architecture='full-current-atomic-structure-snapshot';patchTemporal(x,c,cc);patchArchitecture(x,action);if(action==='structure')x=applyStructureEnrichment(x,enrichment);return send(req,x,core.status)}catch(e){console.error('[public-data-v302-public-internal]',e);return send(req,{ok:false,error:'CuHalide Atlas public data service unavailable',release:RELEASE,version:VERSION},503)}});