declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const UP=`${BASE}/functions/v1/cuhalide-atlas-public-data-v302`,RELEASE='3.0.2',VERSION='2.7.0',PUBLIC='https://cuhalide-atlas-v3.vercel.app';
const ALLOWED=new Set([PUBLIC,'http://localhost:8765','http://127.0.0.1:8765']);
function cors(req:Request){const o=req.headers.get('origin')||'';return{'access-control-allow-origin':ALLOWED.has(o)?o:PUBLIC,'vary':'Origin','access-control-allow-methods':'GET,HEAD,OPTIONS','access-control-allow-headers':'accept,content-type'}}
function hdr(req:Request){return{...cors(req),'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow','x-cuhalide-release':RELEASE,'x-cuhalide-public-data-version':VERSION}}
async function health(){const r=await fetch(`${BASE}/rest/v1/rpc/cuhalide_atlas_public_health_v302`,{method:'POST',headers:{apikey:KEY,authorization:`Bearer ${KEY}`,'content-type':'application/json',accept:'application/json'},body:'{}',signal:AbortSignal.timeout(60000)}),t=await r.text();if(!r.ok)throw Error(`health rpc ${r.status}`);const h=JSON.parse(t);return{ok:h.ok===true,release:RELEASE,version:VERSION,counts:h.counts,checks:h.checks,current_curated:h.current_curated,public_access:{bulk_export:false,primary_evidence:false,exact_abstracts:false,candidate_abstracts:false,server_side_pagination:true,server_side_projection_query:true,projection_backed_bootstrap:true,projection_integrity_contract:true,projection_acl_contract:true,field_whitelist:true,list_field_minimization:true,structure_grain_photophysics_guard:true,structure_grain_motif_guard:true,evidence_aware_structure_halogen:true,structure_halogen_evidence_scope:true,structure_halogen_source_conflict_guard:true,halogenated_ligand_false_positive_guard:true,single_letter_halogen_query_guard:true,article_title_structure_search_isolation:true,current_curated_aggregate_only:true}}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(!['GET','HEAD'].includes(req.method))return new Response(JSON.stringify({error:'read-only endpoint'}),{status:405,headers:hdr(req)});try{const incoming=new URL(req.url),action=String(incoming.searchParams.get('action')||'health').toLowerCase();if(action==='health'){const x=await health();return new Response(req.method==='HEAD'?null:JSON.stringify(x),{status:x.ok?200:503,headers:hdr(req)})}const u=new URL(UP);for(const[k,v]of incoming.searchParams.entries())u.searchParams.append(k,v);const r=await fetch(u,{method:req.method,headers:{accept:'application/json','user-agent':'CuHalide-Atlas-Public-Data-v302-Public/2.7.0'},signal:AbortSignal.timeout(60000)}),body=req.method==='HEAD'?null:await r.text();return new Response(body,{status:r.status,headers:hdr(req)})}catch(e){console.error('[public-data-v302-public]',e);return new Response(JSON.stringify({ok:false,error:'CuHalide Atlas public data service unavailable',release:RELEASE,version:VERSION}),{status:503,headers:hdr(req)})}});
