declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const UP=`${BASE}/functions/v1/cuhalide-atlas-current-rag-r7-exact-internal`,PUBLIC_DATA=`${BASE}/functions/v1/cuhalide-atlas-public-data-v3`,REST=`${BASE}/rest/v1`;
const VERSION='current-rag-r7-science-exact-1.1.1',CURRENT='current-curated-r7',RELEASE='3.0.2',PHOTOPHYSICS_CONTRACT='1.3.1';
const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow, noarchive','x-cuhalide-release':RELEASE,'x-cuhalide-current-curated-revision':'7','x-cuhalide-photophysics-contract':PHOTOPHYSICS_CONTRACT,'x-cuhalide-endpoint-state':'internal-service-only'};
const send=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
function internal(req:Request){return req.headers.get('authorization')===`Bearer ${KEY}`&&req.headers.get('apikey')===KEY}
const zh=(s:string)=>/[\u3400-\u9fff]/.test(s),lastUser=(b:any)=>String([...(Array.isArray(b?.messages)?b.messages:[])].reverse().find((m:any)=>m?.role==='user'&&typeof m.content==='string')?.content||'').trim();
function recordId(q:string){const m=q.match(/(?:record\s*|记录\s*)(\d{1,4})\b/i);return m?Number(m[1]):null}
function structureId(q:string){const m=q.match(/CUH-\d{3}-S\d{2}/i);return m?m[0].toUpperCase():null}
function property(q:string){
if(/\bPLQY\b|photoluminescence\s*quantum\s*yield|quantum\s*yield|量子产率/i.test(q))return'plqy';
if(/emission\s*(?:peak|maximum|maxima|wavelength)|发射峰|发射波长/i.test(q))return'emission';
if(/average\s*lifetime|PL\s*lifetime|luminescence\s*lifetime|发光寿命|平均寿命|寿命/i.test(q))return'average_lifetime';
if(/optical\s*(?:band\s*)?gap|Tauc.*gap|光学带隙|光学禁带/i.test(q))return'optical_band_gap';
if(/Stokes\s*shift|斯托克斯位移/i.test(q))return'stokes_shift';
if(/light\s*yield|光产额/i.test(q))return'light_yield';
if(/(?:x[- ]?ray|radiation).*detection\s*limit|detection\s*limit.*(?:x[- ]?ray|radiation)|X射线.*探测限|探测限/i.test(q))return'xray_lod';
if(/spatial\s*resolution|空间分辨率/i.test(q))return'spatial_resolution';
if(/mechanism|mechanistic|emission\s*assignment|发光机理|发光机制|机制|机理/i.test(q))return'mechanism';
if(/peak\s*(?:external\s*quantum\s*efficiency|EQE)|maximum\s*(?:external\s*quantum\s*efficiency|EQE)|EQE\s*max|EQEmax|峰值\s*(?:EQE|外量子效率)|最大\s*(?:EQE|外量子效率)/i.test(q))return'peak_eqe';
if(/average\s*(?:external\s*quantum\s*efficiency|EQE)|mean\s*(?:external\s*quantum\s*efficiency|EQE)|external\s*quantum\s*efficiency|平均\s*(?:EQE|外量子效率)|外量子效率/i.test(q))return'external_quantum_efficiency';
if(/max(?:imum)?\s*luminance|maximum\s*brightness|最大亮度|最高亮度/i.test(q))return'max_luminance';
if(/\bT50\b|half[- ]?life|operational\s*lifetime|器件寿命|半寿命/i.test(q))return't50';
if(/electron\s*mobility|电子迁移率/i.test(q))return'electron_mobility';
if(/hole\s*mobility|空穴迁移率/i.test(q))return'hole_mobility';
if(/TRMC[\s_-]*(?:yield[\s_-]*)?mobility|yield[- ]mobility|TRMC.*迁移率/i.test(q))return'trmc_yield_mobility';
if(/carrier\s*mobility|charge[- ]carrier\s*mobility|charge\s*mobility|载流子迁移率|电荷迁移率/i.test(q))return'charge_carrier_mobility';
if(/trap\s*(?:state\s*)?density|陷阱态密度|缺陷态密度/i.test(q))return'trap_density';
if(/\bV[_-]?TFL\b|trap[- ]filled[- ]limit\s*voltage|陷阱填充极限电压/i.test(q))return'trap_filled_limit_voltage';
if(/electrical\s*conductiv|\bconductivity\b|电导率/i.test(q))return'electrical_conductivity';
if(/relative\s*permittivity|dielectric\s*constant|dielectric\s*permittivity|相对介电常数|介电常数/i.test(q))return'relative_permittivity';
if(/film\s*thickness|thin[- ]film\s*thickness|膜厚|薄膜厚度/i.test(q))return'film_thickness';
if(/arithmetic\s*mean\s*roughness|surface\s*roughness|\bRa\b.*rough|表面粗糙度|算术平均粗糙度/i.test(q))return'arithmetic_mean_roughness';
if(/device\s*(?:active\s*)?area|emitting\s*area|器件面积|发光面积/i.test(q))return'device_active_area';
if(/exciton\s*binding\s*energy|激子结合能/i.test(q))return'exciton_binding_energy';
if(/Huang[-– ]?Rhys|黄昆.*因子|黄昆因子/i.test(q))return'huang_rhys_factor';
if(/phonon\s*energy|声子能量|声子能/i.test(q))return'phonon_energy';
if(/non[- ]?radiative\s*(?:decay\s*)?rate|nonradiative\s*rate|非辐射.*速率/i.test(q))return'nonradiative_rate';
if(/radiative\s*(?:decay\s*)?rate|辐射.*速率/i.test(q))return'radiative_rate';
if(/(?:change|increase|difference|delta|Δ).*interfacial\s*(?:hydrogen|H)[- ]?bond.*energy|interfacial\s*(?:hydrogen|H)[- ]?bond.*(?:energy\s*)?(?:change|increase|difference)|界面.*氢键.*(?:能量|能).*变化|界面.*氢键.*能量增量/i.test(q))return'interfacial_hydrogen_bond_energy_change';
if(/interfacial\s*(?:hydrogen|H)[- ]?bond\s*(?:interaction\s*)?energy|interface.*H[- ]?bond.*energy|界面.*氢键.*能/i.test(q))return'interfacial_hydrogen_bond_energy';
if(/FTIR.*(?:band|peak|position)|红外.*(?:峰位|波数)/i.test(q))return'ftir_band_position';
if(/work\s*function|功函数/i.test(q))return'work_function';
if(/valence[- ]band.*Fermi|VB.*Fermi|价带.*费米/i.test(q))return'valence_band_fermi_offset';
if(/absorption\s*onset\s*energy|吸收边.*能量|吸收起始.*能量/i.test(q))return'absorption_onset_energy';
if(/Fermi\s*level|费米能级/i.test(q))return'fermi_level';
if(/\bVBM\b|valence[- ]band\s*maximum|价带顶/i.test(q))return'vbm_energy';
if(/\bCBM\b|conduction[- ]band\s*minimum|导带底/i.test(q))return'cbm_energy';
if(/\bCCT\b|correlated\s*color\s*temperature|相关色温/i.test(q))return'correlated_color_temperature';
if(/\bCRI\b|color\s*rendering\s*index|显色指数/i.test(q))return'color_rendering_index';
if(/CIE\s*x\b|CIE.*x\s*coordinate|CIE\s*x坐标/i.test(q))return'cie_x';
if(/CIE\s*y\b|CIE.*y\s*coordinate|CIE\s*y坐标/i.test(q))return'cie_y';return null}
const LABELS:any={plqy:['PLQY','PLQY'],emission:['emission peak','发射峰'],average_lifetime:['average lifetime','平均寿命'],optical_band_gap:['optical band gap','光学带隙'],stokes_shift:['Stokes shift','斯托克斯位移'],light_yield:['light yield','光产额'],xray_lod:['X-ray detection limit','X 射线探测限'],spatial_resolution:['spatial resolution','空间分辨率'],mechanism:['mechanism assignment','机制指认'],peak_eqe:['peak EQE','峰值 EQE'],external_quantum_efficiency:['external quantum efficiency','外量子效率'],max_luminance:['maximum luminance','最大亮度'],t50:['T50','T50'],electron_mobility:['electron mobility','电子迁移率'],hole_mobility:['hole mobility','空穴迁移率'],trmc_yield_mobility:['TRMC yield mobility','TRMC 产率-迁移率'],charge_carrier_mobility:['carrier mobility','载流子迁移率'],trap_density:['trap density','陷阱态密度'],trap_filled_limit_voltage:['trap-filled-limit voltage','陷阱填充极限电压'],electrical_conductivity:['electrical conductivity','电导率'],relative_permittivity:['relative permittivity','相对介电常数'],film_thickness:['film thickness','薄膜厚度'],arithmetic_mean_roughness:['surface roughness Ra','表面粗糙度 Ra'],device_active_area:['device area','器件面积'],exciton_binding_energy:['exciton binding energy','激子结合能'],huang_rhys_factor:['Huang–Rhys factor','Huang–Rhys 因子'],phonon_energy:['phonon energy','声子能量'],nonradiative_rate:['non-radiative rate','非辐射速率'],radiative_rate:['radiative rate','辐射速率'],interfacial_hydrogen_bond_energy:['interfacial H-bond energy','界面氢键能'],interfacial_hydrogen_bond_energy_change:['change in interfacial H-bond energy','界面氢键能变化'],ftir_band_position:['FTIR band position','FTIR 峰位'],work_function:['work function','功函数'],valence_band_fermi_offset:['valence-band/Fermi offset','价带-费米能级差'],absorption_onset_energy:['absorption onset energy','吸收起始能量'],fermi_level:['Fermi level','费米能级'],vbm_energy:['VBM energy','价带顶能量'],cbm_energy:['CBM energy','导带底能量'],correlated_color_temperature:['CCT','相关色温'],color_rendering_index:['CRI','显色指数'],cie_x:['CIE x','CIE x'],cie_y:['CIE y','CIE y']};
const label=(k:string,z:boolean)=>LABELS[k]?.[z?1:0]||k;
function unit(u:any){return String(u||'').replace(/^us$/,'μs').replace(/^degC$/,'°C').replace(/MeV-1/g,'MeV⁻¹').replace(/mm-1/g,'mm⁻¹').replace(/s-1/g,'s⁻¹')}
function val(r:any){if(r.value_text)return`${r.value_text}${r.unit?` ${unit(r.unit)}`:''}`;let p='';const q=String(r.qualifier||'');if(/approx|approximately|~|∼/i.test(q))p='≈';else if(/^\s*>/.test(q))p='>';else if(/^\s*</.test(q))p='<';return`${p}${r.value_numeric}${r.unit?` ${unit(r.unit)}`:''}`}
function sortMode(q:string){if(/highest|largest|maximum|best|top|最高|最大|排名|排行/i.test(q))return'desc';if(/lowest|smallest|minimum|最低|最小/i.test(q))return'asc';return'record'}
function stageLabel(r:any,z:boolean){return r?.verification_stage==='two_pass_verified'?(z?'双遍核验':'two-pass verified'):(z?'Pass A 策展':'Pass A curated')}
async function rpc(name:string,body:any={}){const r=await fetch(`${REST}/rpc/${name}`,{method:'POST',headers:{apikey:KEY,authorization:`Bearer ${KEY}`,'content-type':'application/json',accept:'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(30000)}),t=await r.text();if(!r.ok)throw Error(`${name} ${r.status}: ${t.slice(0,240)}`);return JSON.parse(t)}
async function pd(action:string,params:Record<string,string>={}){const u=new URL(PUBLIC_DATA);u.searchParams.set('action',action);for(const[k,v]of Object.entries(params))u.searchParams.set(k,v);const r=await fetch(u,{headers:{accept:'application/json'},signal:AbortSignal.timeout(30000)}),t=await r.text();if(!r.ok)throw Error(`public data ${r.status}`);return JSON.parse(t)}
function sourceCard(r:any){const grain={sample_form:r.sample_form??null,mapping_status:r.mapping_status??null,property_scope:r.property_scope??null,photophysics_analysis_eligible:r.analysis_eligible===true,verification_stage:r.verification_stage||null,two_pass_verified:r.two_pass_verified===true};const scope=r.verification_stage==='two_pass_verified'?'two-pass verified structured scientific data':'Pass A curated structured scientific data';if(r.structure_id)return{type:'structure',id:r.structure_id,record_id:r.record_id,title:r.sample_label||r.structure_id,doi:r.doi||'',curation_layer:'Current Curated',live_revision:7,evidence_scope:scope,...grain};return{type:'article',id:r.record_id,record_id:r.record_id,title:r.sample_label||r.article_title||`Record ${r.record_id}`,doi:r.doi||'',curation_layer:'Current Curated',live_revision:7,evidence_scope:scope,...grain}}
function conflictLine(c:any,z:boolean){const k=String(c?.property_key||'source discrepancy'),l=label(k,z),s=String(c?.adjudication_status||'unresolved'),p=String(c?.preferred_value||'').trim();if(s==='preferred_source_identified')return z?`${l}存在来源差异；策展层采用来源优先级确定的值${p?` ${p}`:''}，同时保留警告。`:`${l} has a source discrepancy; the curated layer uses the source-priority value${p?` ${p}`:''} while retaining the warning.`;if(s==='retain_both')return z?`${l}在主证据中存在无法可靠消解的冲突；两个来源陈述均保留，冲突标量不进入普通数值查询。`:`${l} has an irreducible primary-source conflict; both source statements are retained and the conflicting scalar is withheld from ordinary numeric queries.`;if(s==='not_comparable')return z?`${l}的来源值条件不可直接比较，因此不合并为单一数值。`:`${l} source values are not directly comparable under their reported conditions, so they are not merged into one scalar.`;return z?`${l}存在已策展的来源差异；不进行无证据统一。`:`${l} has a curated source discrepancy; no unsupported harmonization is applied.`}
async function scienceAnswer(q:string,k:string){const z=zh(q),rid=recordId(q),sid=structureId(q),sort=sortMode(q),x=await rpc('cuhalide_atlas_public_photophysics_query_v2',{p_property_key:k,p_record_id:rid,p_structure_id:sid,p_limit:20,p_sort:sort}),rows=Array.isArray(x?.rows)?x.rows:[];if(!rows.length&&(rid||sid)){const id=rid||Number(String(sid).slice(4,7));try{const p=await pd('photophysics',{id:String(id),...(sid?{structure:sid}:{})}),ph=p?.public_state?p:p?.photophysics||p,cs=(Array.isArray(ph?.conflicts)?ph.conflicts:[]).filter((c:any)=>!k||k==='mechanism'||String(c?.property_key||'')===k);if(cs.length){return{ok:true,relevant_current:true,mode:'deterministic-scientific-data',answer:`### ${z?'已策展的来源冲突':'Curated source discrepancy'}\n${cs.map((c:any)=>`- ${conflictLine(c,z)}`).join('\n')}\n\n${z?'> 冲突对象通过策展 QC；无法可靠消解的标量继续 fail-closed，不进入普通数值结果。':'> The conflict object passed curation QC; any scalar that cannot be reliably adjudicated remains fail-closed and is not returned as an ordinary numeric result.'}`,sources:[],scientific_query:x,conflicts:cs,photophysics_contract:PHOTOPHYSICS_CONTRACT}}}catch{}}if(!rows.length)return{ok:true,relevant_current:true,mode:'deterministic-scientific-data',answer:z?`当前公开结构化光物理层（Pass A 策展或双遍核验）中，没有符合该条件的${label(k,z)}数据。`:`No matching ${label(k,z)} data are available in the public structured photophysics layer (Pass A curated or two-pass verified).`,sources:[],scientific_query:x,photophysics_contract:PHOTOPHYSICS_CONTRACT};const l=label(k,z),lines=rows.slice(0,12).map((r:any,i:number)=>{const qual=String(r.qualifier||''),v=k==='mechanism'?String(r.mechanism_label||r.mechanism_code||r.assignment||'mechanism'):val(r);return`- ${sort!=='record'?`${i+1}. `:''}[${r.structure_id?`S:${r.structure_id}`:`A:${r.record_id}`}] **${r.sample_label||r.article_title}** — ${l} ${v}${qual?`; ${qual}`:''}${r.temperature_k!=null?`; ${r.temperature_k} K`:''}; ${stageLabel(r,z)}; ${r.analysis_eligible?(z?'可进入定量关联':'quantitative-correlation eligible'):(z?'描述性/非定量关联资格':'descriptive / not quantitative-correlation eligible')}.`});return{ok:true,relevant_current:true,mode:'deterministic-scientific-data',answer:`### ${z?'策展的':'Curated '}${l}${sort==='desc'?(z?'（降序）':' (descending)'):sort==='asc'?(z?'（升序）':' (ascending)'):''}\n${lines.join('\n')}\n\n${z?'> 公开层允许 Pass A 策展与双遍核验记录，但两种 verification stage 始终明确区分；measurement-level QC、样品粒度和冲突 fail-closed 规则不变。':'> The public layer allows both Pass A curated and two-pass verified records, with verification stage kept explicit. Measurement-level QC, sample grain, and fail-closed conflict rules remain unchanged.'}`,sources:rows.slice(0,12).map(sourceCard),scientific_query:x,photophysics_contract:PHOTOPHYSICS_CONTRACT}}
async function delegate(req:Request,raw?:string){const r=await fetch(UP,{method:raw?'POST':'GET',headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json'},body:raw,signal:AbortSignal.timeout(raw?90000:30000)}),t=await r.text();let x:any;try{x=JSON.parse(t)}catch{x={error:'invalid exact-current response'}};return send({...x,science_exact_version:VERSION,photophysics_contract:PHOTOPHYSICS_CONTRACT},r.status)}
Deno.serve(async(req:Request)=>{if(!internal(req))return send({ok:false,error:'internal service authorization required'},401);if(!['GET','POST'].includes(req.method))return send({error:'method not allowed'},405);try{if(req.method==='GET')return delegate(req);const raw=await req.text();let b:any;try{b=JSON.parse(raw)}catch{return send({error:'invalid JSON'},400)}const q=lastUser(b),k=property(q);if(k)return send({...await scienceAnswer(q,k),release:RELEASE,current_release:CURRENT,version:VERSION,architecture:'full-current-atomic-structure-snapshot',photophysics_contract:PHOTOPHYSICS_CONTRACT,write_access:false});return delegate(req,raw)}catch(e){console.error('[science-exact-r7-v111]',e);return send({ok:false,error:'Current Curated rev.7 structured scientific layer unavailable',current_release:CURRENT,version:VERSION,photophysics_contract:PHOTOPHYSICS_CONTRACT},503)}});