import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,CF_ACCOUNT=Deno.env.get('CLOUDFLARE_ACCOUNT_ID')||'',CF_TOKEN=Deno.env.get('CLOUDFLARE_API_TOKEN')||'';
const EXACT=`${BASE}/functions/v1/cuhalide-atlas-current-rag-r10-science-exact-internal`,CURRENT='current-curated-r10',REV=10,DOCS=1322,EMBED='@cf/baai/bge-m3',RERANK='@cf/baai/bge-reranker-base';
const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow, noarchive','x-cuhalide-release':'3.0.2','x-cuhalide-current-curated-revision':'10','x-cuhalide-photophysics-contract':'1.4.0','x-cuhalide-organic-components-contract':'1.2.0','x-cuhalide-endpoint-state':'internal-service-only'};
function internal(r:Request){return r.headers.get('authorization')===`Bearer ${KEY}`&&r.headers.get('apikey')===KEY} const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const exact=(q:string)=>/(?:literature\s*cutoff|coverage\s*through|curated\s*through|current\s*curated|文献截止|当前策展|当前收录|目前收录|(?:record\s*|记录\s*)\d{1,4}\b|CUH-\d{3}-S\d{2}|10\.\d{4,9}\/|\bCCDC\s*\d+\b|\bhow many\b|有多少|几篇|数量)/i.test(q);
async function callExact(raw?:string){const r=await fetch(EXACT,{method:raw?'POST':'GET',headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json'},body:raw,signal:AbortSignal.timeout(raw?90000:30000)}),t=await r.text();let x:any;try{x=JSON.parse(t)}catch{x={error:'invalid exact response'}}return{r,x}}
async function rpc(n:string,b:any){const r=await fetch(`${BASE}/rest/v1/rpc/${n}`,{method:'POST',headers:{apikey:KEY,authorization:`Bearer ${KEY}`,'content-type':'application/json'},body:JSON.stringify(b),signal:AbortSignal.timeout(30000)}),t=await r.text();if(!r.ok)throw Error(t);return JSON.parse(t)}
async function embed(q:string){const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT}/ai/run/${EMBED}`,{method:'POST',headers:{authorization:`Bearer ${CF_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({text:[q]}),signal:AbortSignal.timeout(15000)}),x=await r.json();const v=(x as any)?.result?.data?.[0];if(!Array.isArray(v)||v.length!==1024)throw Error('embedding unavailable');return v}
async function rerank(q:string,docs:any[]){if(!docs.length)return[];try{const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT}/ai/run/${RERANK}`,{method:'POST',headers:{authorization:`Bearer ${CF_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({query:q,contexts:docs.map(d=>({text:`${d.document_type}:${d.document_key} ${d.title||''}\n${String(d.content||'').slice(0,3500)}`})),top_k:Math.min(20,docs.length)}),signal:AbortSignal.timeout(15000)}),x=await r.json();const a=Array.isArray((x as any)?.result?.response)?(x as any).result.response:[];const out=[];for(const z of a){const i=Number(z.index??z.id??z.context_index);if(Number.isInteger(i)&&docs[i])out.push({...docs[i],rerank_score:Number(z.score??z.relevance_score??0)})}return out.length?out:docs}catch{return docs}}
function lastUser(b:any){const a=Array.isArray(b?.messages)?b.messages:[];return String([...a].reverse().find((m:any)=>m?.role==='user')?.content||'').trim()}
function card(d:any){const c=d.llm_context||{},e=d.evidence||{};return d.document_type==='structure'?{type:'structure',id:d.structure_id,record_id:d.record_id,title:d.title,doi:e.doi||c.doi||'',url:e.doi_url||'',formula:c.formula||'',space_group:c.space_group||'',polar:c.polar||'',dimensionality:c.dimension||'',motif_formula:c.motif_formula||'',curation_layer:'Current Curated',live_revision:10}:{type:'article',id:d.record_id,record_id:d.record_id,title:d.title,doi:e.doi||c.doi||'',url:e.doi_url||'',curation_layer:'Current Curated',live_revision:10}}
Deno.serve(async req=>{if(!internal(req))return json({ok:false,error:'internal service authorization required'},401);try{if(req.method==='GET'){const z=await callExact();return json({...z.x,ok:z.r.ok&&z.x?.ok!==false,current_release:CURRENT,current_curated_revision:REV,active_current_documents:DOCS,active_current_embedded:DOCS,unified_document_count:DOCS,unified_embedded_count:DOCS,architecture:'full-current-atomic-structure-snapshot'})}if(req.method!=='POST')return json({error:'method not allowed'},405);const raw=await req.text();let b:any;try{b=JSON.parse(raw)}catch{return json({error:'invalid JSON'},400)}const q=lastUser(b);if(!q)return json({error:'user message required'},400);if(exact(q)){const z=await callExact(raw);return json({...z.x,current_release:CURRENT,current_curated_revision:REV,architecture:'full-current-atomic-structure-snapshot'},z.r.status)}const v=await embed(q),pool=await rpc('cuhalide_atlas_hybrid_search_current_v4',{p_query_text:q,p_query_embedding:v,p_match_count:30,p_filters:{},p_full_text_weight:1.25,p_semantic_weight:1,p_rrf_k:50}),ranked=(await rerank(q,pool)).slice(0,10);const zh=/[\u3400-\u9fff]/.test(q);const lines=ranked.map((d:any)=>d.document_type==='structure'?`- [S:${d.structure_id}] **${d.title}** — ${zh?'化学式':'formula'} ${d.llm_context?.formula||''}; SG ${d.llm_context?.space_group||'Unresolved'}; ${zh?'维度':'dimension'} ${d.llm_context?.dimension||'Unresolved'}; ${zh?'基元':'motif'} ${d.llm_context?.motif_formula||'Unresolved'}.`:`- [A:${d.record_id}] **${d.title}** — DOI ${d.evidence?.doi||d.llm_context?.doi||''}.`);return json({ok:true,release:'3.0.2',current_release:CURRENT,current_curated_revision:REV,version:'current-rag-r10.0.0',architecture:'full-current-atomic-structure-snapshot',relevant_current:ranked.length>0,answer:ranked.length?`${zh?'### Current Curated rev.10 证据':'### Current Curated rev.10 evidence'}\n${lines.join('\n')}`:'',sources:ranked.map(card),mode:'full-current-hybrid',operational_mode:'FULL',embedding_model:EMBED,reranker_model:RERANK,write_access:false})}catch(e){console.error(e);return json({ok:false,error:'Current Curated rev.10 RAG unavailable',current_release:CURRENT,current_curated_revision:REV},503)}});
