import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,CF_ACCOUNT=Deno.env.get('CLOUDFLARE_ACCOUNT_ID')||'',CF_TOKEN=Deno.env.get('CLOUDFLARE_API_TOKEN')||'';
const EXACT=`${BASE}/functions/v1/cuhalide-atlas-current-rag-r10-science-exact-internal`,CURRENT='current-curated-r10',REV=10,DOCS=1322,EMBED='@cf/baai/bge-m3',RERANK='@cf/baai/bge-reranker-base';
const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow, noarchive','x-cuhalide-release':'3.0.2','x-cuhalide-current-curated-revision':'10','x-cuhalide-photophysics-contract':'1.4.0','x-cuhalide-organic-components-contract':'1.2.0','x-cuhalide-knowledge-contract':'1.2.0','x-cuhalide-endpoint-state':'internal-service-only'};
function internal(r:Request){return r.headers.get('authorization')===`Bearer ${KEY}`&&r.headers.get('apikey')===KEY}const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const exact=(q:string)=>/(?:literature\s*cutoff|coverage\s*through|curated\s*through|current\s*curated|文献截止|当前策展|当前收录|目前收录|(?:record\s*|记录\s*)\d{1,4}\b|CUH-\d{3}-S\d{2}|10\.\d{4,9}\/|\bCCDC\s*\d+\b|\bhow many\b|有多少|几篇|数量)/i.test(q);
async function callExact(raw?:string){const r=await fetch(EXACT,{method:raw?'POST':'GET',headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json'},body:raw,signal:AbortSignal.timeout(raw?90000:30000)}),t=await r.text();let x:any;try{x=JSON.parse(t)}catch{x={error:'invalid exact response'}}return{r,x}}
async function rpc(n:string,b:any){const r=await fetch(`${BASE}/rest/v1/rpc/${n}`,{method:'POST',headers:{apikey:KEY,authorization:`Bearer ${KEY}`,'content-type':'application/json'},body:JSON.stringify(b),signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Evidence service unavailable');return r.json()}
async function embed(q:string){const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT}/ai/run/${EMBED}`,{method:'POST',headers:{authorization:`Bearer ${CF_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({text:[q]}),signal:AbortSignal.timeout(15000)}),x=await r.json();const v=(x as any)?.result?.data?.[0];if(!Array.isArray(v)||v.length!==1024)throw Error('embedding unavailable');return v}
async function rerank(q:string,docs:any[]){if(!docs.length)return{docs:[],applied:false};try{const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT}/ai/run/${RERANK}`,{method:'POST',headers:{authorization:`Bearer ${CF_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({query:q,contexts:docs.map(d=>({text:`${d.document_type}:${d.document_key} ${d.title||''}\n${String(d.content||'').slice(0,3500)}`})),top_k:Math.min(20,docs.length)}),signal:AbortSignal.timeout(15000)}),x=await r.json();const a=Array.isArray((x as any)?.result?.response)?(x as any).result.response:[],out=[];for(const z of a){const i=Number(z.index??z.id??z.context_index);if(Number.isInteger(i)&&docs[i])out.push(docs[i])}return{docs:out.length?out:docs,applied:out.length>0}}catch{return{docs,applied:false}}}
function lastUser(b:any){return String([...(Array.isArray(b?.messages)?b.messages:[])].reverse().find((m:any)=>m?.role==='user')?.content||'').trim()}
function retrievalQuery(b:any,q:string){const users=(Array.isArray(b?.messages)?b.messages:[]).filter((m:any)=>m.role==='user'&&typeof m.content==='string');return(q.length<100&&/^(why|how about|what about|and |then |为什么|那么|那|继续)/i.test(q)&&users.length>1?`${users[users.length-2].content.slice(0,350)} ${q}`:q).slice(0,600)}
function card(d:any){const c=d.llm_context||{},e=d.evidence||{};return d.document_type==='structure'?{type:'structure',id:d.structure_id,record_id:d.record_id,title:d.title,doi:e.doi||c.doi||'',url:e.doi_url||'',formula:c.formula||'',space_group:c.space_group||'',polar:c.polar||'',dimensionality:c.dimension||'',motif_formula:c.motif_formula||'',evidence_scope:'structure identity / crystallography',curation_layer:'Current Curated',live_revision:10}:{type:'article',id:d.record_id,record_id:d.record_id,title:d.title,doi:e.doi||c.doi||'',url:e.doi_url||'',evidence_scope:'article-level curated evidence',curation_layer:'Current Curated',live_revision:10}}
const text=(s:any)=>String(s||'').replace(/[\r\n]+/g,' ').replace(/[<>]/g,'').slice(0,900);
async function knowledge(q:string){const dois=[...new Set(q.match(/10\.\d{4,9}\/[^\s<>]+/gi)||[])].map(x=>x.replace(/[.,;]+$/,''));const queries=dois.length?dois.slice(0,4):[q];const results=await Promise.all(queries.map(p_query=>rpc('cuxplore_knowledge_v1',{p_action:'retrieve',p_query,p_scope:'all',p_limit:8,p_offset:0})));return{...results[0],items:results.flatMap(x=>x.items||[]).slice(0,20)}}
function supplement(k:any,zh:boolean){const items=k?.items||[],notes=items.filter((x:any)=>x.review),related=items.filter((x:any)=>!x.record_id),matched=items.filter((x:any)=>x.primary_match);const lines=[];
if(notes.length){lines.push(zh?'### 来源复核摘要':'### Source-reviewed findings');for(const d of notes.slice(0,5))lines.push(`- ${d.record_id?`[A:${d.record_id}] `:''}**${text(d.title)}** — ${text(d.review.statement)} ${text(d.review.qualification)} (DOI: ${text(d.doi)})`)}
if(matched.length){lines.push(zh?'### 原文检索定位':'### Original-text retrieval');for(const d of matched.slice(0,5)){const m=d.primary_match;lines.push(`- ${d.record_id?`[A:${d.record_id}] `:''}**${text(d.title)}** — ${m.source_role==='supporting_information'?'SI':'MAIN'}, ${m.page_start==null?'page not recorded':`PDF p. ${m.page_start}${m.page_end&&m.page_end!==m.page_start?'-'+m.page_end:''}`}; DOI ${text(d.doi)}.`)}lines.push(zh?'原文匹配用于定位证据，不等于结构或机制已验证。':'Text matches locate evidence; they do not independently validate a structure or mechanism.')}
if(related.length){lines.push(zh?'### 补充文献':'### Additional literature');for(const d of related.slice(0,4))lines.push(`- **${text(d.title)}** — DOI ${text(d.doi)}; ${d.processing?.prose_passages?'indexed source text; no added compound record':d.review?'source-review annotation':'bibliographic context only'}.`)}
const use=[...notes.slice(0,5),...matched.slice(0,5)];return{answer:lines.join('\n'),notes:Math.min(5,notes.length),matched:Math.min(5,matched.length),sources:use.filter((d:any)=>d.record_id).map((d:any)=>({type:'article',id:d.record_id,record_id:d.record_id,title:d.title,doi:d.doi,url:d.url,evidence_scope:d.primary_match?'article-level original-text match':'article-level source-review note',primary_match:d.primary_match||null,curation_layer:'Current Curated',live_revision:10})),related:related.map((d:any)=>({doi:d.doi,title:d.title,url:d.url,evidence_scope:d.review?'article-level reviewed literature':'bibliographic context',primary_match:d.primary_match||null}))}}
Deno.serve(async req=>{if(!internal(req))return json({ok:false,error:'internal service authorization required'},401);try{if(req.method==='GET'){const z=await callExact();return json({...z.x,ok:z.r.ok&&z.x?.ok!==false,current_release:CURRENT,current_curated_revision:REV,active_current_documents:DOCS,active_current_embedded:DOCS,unified_document_count:DOCS,unified_embedded_count:DOCS,architecture:'full-current-atomic-structure-snapshot',knowledge_contract:'1.2.0',display_name:'CuXplore'})}if(req.method!=='POST')return json({error:'method not allowed'},405);const raw=await req.text();if(raw.length>20000)return json({error:'request too large'},413);let b:any;try{b=JSON.parse(raw)}catch{return json({error:'invalid JSON'},400)}const q=lastUser(b);if(!q||q.length>4000)return json({error:'valid user message required'},400);const zh=/[\u3400-\u9fff]/.test(q),rq=retrievalQuery(b,q);
if(exact(q)&&!/(?:10\.\d{4,9}\/)/.test(q)){const z=await callExact(raw);return json({...z.x,current_release:CURRENT,current_curated_revision:REV,architecture:'full-current-atomic-structure-snapshot',retrieval_trace:{method:'structured exact-record / count query',generation_performed:false}},z.r.status)}
const knowledgePromise=knowledge(rq).catch(()=>null);let base:any={answer:'',sources:[]},method='lexical catalog and primary text',fallback=false;
if(exact(q)){const z=await callExact(raw);if(z.r.ok)base=z.x;method='exact record plus source context'}else{try{const v=await embed(rq),pool=await rpc('cuhalide_atlas_hybrid_search_current_v4',{p_query_text:rq,p_query_embedding:v,p_match_count:30,p_filters:{},p_full_text_weight:1.25,p_semantic_weight:1,p_rrf_k:50}),rr=await rerank(rq,pool),ranked=rr.docs.slice(0,8);method=rr.applied?'hybrid structure/article retrieval + reranking + MAIN/SI lexical context':'hybrid structure/article retrieval + MAIN/SI context (reranker unavailable)';const lines=ranked.map((d:any)=>d.document_type==='structure'?`- [S:${d.structure_id}] **${text(d.title)}** — ${zh?'化学式':'formula'} ${text(d.llm_context?.formula)}; SG ${text(d.llm_context?.space_group)||'Unresolved'}; ${zh?'维度':'dimension'} ${text(d.llm_context?.dimension)||'Unresolved'}; ${zh?'基元':'motif'} ${text(d.llm_context?.motif_formula)||'Unresolved'}.`:`- [A:${d.record_id}] **${text(d.title)}** — DOI ${text(d.evidence?.doi||d.llm_context?.doi)}.`);base={answer:lines.length?`${zh?'### 已策展证据':'### Curated evidence'}\n${lines.join('\n')}`:'',sources:ranked.map(card)}}catch{fallback=true;method='lexical source-context fallback; semantic service unavailable'}}
const k=await knowledgePromise,s=supplement(k,zh);let answer=[base.answer,s.answer].filter(Boolean).join('\n\n');const map=new Map();for(const c of [...(base.sources||[]),...s.sources])map.set(`${c.type}:${c.id}`,c);if(!answer)answer=zh?'未检索到可支持回答的证据。请用具体化学名称或 DOI 缩小问题。':'No supporting evidence was retrieved. Refine the chemical terms or use a DOI.';
return json({...base,ok:true,release:'3.0.2',current_release:CURRENT,current_curated_revision:REV,version:'current-rag-r10.2.0',architecture:'full-current-atomic-structure-snapshot',answer,sources:[...map.values()],related_literature:s.related,answer_kind:'retrieval_summary',operational_mode:fallback?'SAFE_FALLBACK':'FULL',fallback,display_name:'CuXplore',knowledge_contract:'1.2.0',retrieval_trace:{query:rq,method,catalog_available:k!==null,catalog_articles:k?.coverage?.catalog_articles||null,review_notes_used:s.notes,primary_text_matches:s.matched,indexed_prose_articles:k?.processing_coverage?.any_prose_articles||null,returned_catalog_sources:k?.items?.length||0,core_semantic_documents:DOCS,generation_performed:false,source_review_is_structured_measurement:false},write_access:false});
}catch(e){console.error('[cuxplore-retrieval]',e);return json({ok:false,error:'Current evidence retrieval unavailable',current_release:CURRENT,current_curated_revision:REV},503)}});
