declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';

const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const CF_ACCOUNT=Deno.env.get('CLOUDFLARE_ACCOUNT_ID')||'',CF_TOKEN=Deno.env.get('CLOUDFLARE_API_TOKEN')||'';
const LEGACY=`${BASE}/functions/v1/cuhalide-atlas-rag-v9-core-internal`;
const RELEASE='3.0.1',VERSION='9.11.0-safe-core-internal',EMBED='@cf/baai/bge-m3',RERANK='@cf/baai/bge-reranker-base';

const CROWN=/crown[- ]?ether|18[- ]?crown|18c6|冠醚/i;
const STE=/self[- ]?trapped|\bste\b|自陷|自俘获/i;
const CUCU=/cu\s*[·.]{1,}\s*cu|cu[-−]\s*cu|cuprophil|铜铜/i;
const CLUSTER=/cluster[- ]?center|3cc|簇中心/i;
const EMISSION=/emission|luminescen|photolum|fluorochrom|plqy|quantum\s*yield|lifetime|radiolum|afterglow|发光|发射|量子产率|寿命|余辉/i;
const SCINT=/scintillat|x[- ]?ray|闪烁|x射线/i;
const THERMO=/thermochrom|temperature[- ]?depend|temperature\s+depend|低温|变温|温度依赖|热致|热变色|heating|cooling/i;
const MECH=/mechanochrom|mechanolum|机械致变|力致变/i;
const NIR=/\bnir(?:-?ii)?\b|near[- ]?infrared|近红外/i;
const CONDUCT=/conductiv|transport propert|电导|导电|输运/i;
const STABILITY=/water[- ]?stable|hydrostab|anti[- ]?water|water stability|moisture[- ]?stable|air[- ]?stable|水稳定|抗水|耐水|湿度稳定/i;
const SEMICON=/semiconductor|semiconducting|半导体/i;
const PHASE_REL=/phase transition|phase transformation|polymorph|reversible phase|相变|晶型|多晶型/i;
const MOTIF=/motif|building\s+unit|structural\s+unit|staircase|chain|network|framework|layer(?:ed)?|dimer|tetramer|cubane|tetrahed|cluster|ladder|基元|构筑单元|结构单元|阶梯链|链状|网络|骨架|层状|二聚|四聚|立方烷|簇/i;
const ASSEMBLY=/directed|assembled|regulated|templated|template|host[- ]?guest|supramolecular|调控|组装|模板|主客体/i;
const CHIRAL=/\bchiral|chirality|手性/i;
const SOFT_SCIENCE=/crown[- ]?ether|18[- ]?crown|18c6|冠醚|self[- ]?trapped|\bste\b|exciton|emission|luminescen|photolum|fluorochrom|plqy|quantum\s*yield|lifetime|radiolum|afterglow|scintillat|thermochrom|mechanochrom|mechanolum|near[- ]?infrared|\bnir(?:-?ii)?\b|conductiv|transport propert|water[- ]?stable|hydrostab|anti[- ]?water|moisture[- ]?stable|semiconductor|phase transition|phase transformation|polymorph|motif|building\s+unit|staircase|\bchain\b|network|framework|layered|dimer|tetramer|cubane|tetrahed|cluster|ladder|directed|assembled|regulated|templated|host[- ]?guest|supramolecular|\bchiral|发光|发射|自陷|激子|量子产率|寿命|闪烁|热致|机械致变|近红外|电导|导电|水稳定|抗水|半导体|相变|晶型|多晶型|基元|构筑单元|阶梯链|链状|网络|骨架|层状|二聚|四聚|簇|调控|组装|模板|主客体|手性/i;
const REL=/relation|relationship|cause|causal|universal|compare|different|difference|关系|因果|普遍|比较|对比|不同|差异/i;
const STRICT=/strict[- ]?polar|严格极性|高置信极性/i,TEMP=/temperature|温度|热致|thermochrom/i;
const STRUCTURE_ID=/CUH-\d{3}-S\d{2}/i;
const STRUCTURE_RECORD_REQUEST=/structure\s*(?:\/\s*phase\s*)?(?:record|row)s?|crystallographic\s+record|and\s+(?:its|their)\s+structures?|结构(?:\/相)?记录|结构条目|及其结构|对应结构/i;

const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow','x-cuhalide-release':RELEASE,'x-cuhalide-rag-core-version':VERSION}});
const zh=(s:string)=>/[\u3400-\u9fff]/.test(s),sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function lastUser(b:any){const ms=Array.isArray(b?.messages)?b.messages:[];return String([...ms].reverse().find((m:any)=>m?.role==='user'&&typeof m.content==='string')?.content||'').trim()}
function client(req:Request){const x=String(req.headers.get('x-cuhalide-client')||'').toLowerCase();return/^[a-f0-9]{64}$/.test(x)?x:''}
async function sha(s:string){const h=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));return[...h].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function rest(path:string,init:RequestInit={}){const r=await fetch(`${BASE}/rest/v1/${path}`,{...init,headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json',...(init.headers||{})},signal:AbortSignal.timeout(22000)}),raw=await r.text();let x:any;try{x=raw?JSON.parse(raw):null}catch{x={raw}};if(!r.ok)throw Error(`REST ${r.status}: ${raw.slice(0,300)}`);return x}
async function rpc(name:string,body:any){return rest(`rpc/${name}`,{method:'POST',body:JSON.stringify(body)})}
async function rate(req:Request,w=2){const c=client(req),fp=c||await sha(`safe-core-v9110|${req.headers.get('user-agent')||'internal'}`);return rpc('cuhalide_atlas_agent_rate_limit',{p_fingerprint:fp,p_weight:w})}

function protectedScience(q:string){if(STE.test(q)&&CUCU.test(q)&&REL.test(q))return true;if(STRICT.test(q)&&TEMP.test(q))return true;if(/\brecord\s*13\b|记录\s*13|CUH-013-S0[1-4]/i.test(q))return true;return false}
function shouldArticleOnly(q:string){return SOFT_SCIENCE.test(q)&&!STRUCTURE_ID.test(q)&&!protectedScience(q)}

function terms(q:string){const a:string[]=[];const add=(...xs:string[])=>xs.forEach(x=>{if(x&&!a.includes(x))a.push(x)});
  if(CROWN.test(q))add('crown ether','crown-ether','18-crown-6','18C6');
  if(STE.test(q))add('self-trapped exciton','self trapped exciton','STE');
  if(CUCU.test(q))add('Cu···Cu','Cu-Cu','cuprophilic');
  if(CLUSTER.test(q))add('cluster-centered','cluster centered','3CC');
  if(THERMO.test(q))add('thermochromic','temperature-dependent','temperature dependent');
  if(MECH.test(q))add('mechanochromic','mechanoluminescence');
  if(SCINT.test(q))add('scintillator','scintillation','X-ray');
  if(NIR.test(q))add('NIR-II','near-infrared');
  if(CONDUCT.test(q))add('conductive','conductivity','transport properties');
  if(STABILITY.test(q))add('water-stable','hydrostable','anti-water','water stability');
  if(SEMICON.test(q))add('semiconductor','semiconducting');
  if(PHASE_REL.test(q))add('phase transition','phase transformation','polymorph');
  if(MOTIF.test(q))add('staircase chain','coordination network','structural motif','building unit');
  if(ASSEMBLY.test(q))add('assembled','directed','templated','regulated');
  if(CHIRAL.test(q))add('chiral','chirality');
  if(EMISSION.test(q))add('emission','luminescence','photoluminescence');
  for(const m of q.matchAll(/\bCu\d+(?:I|Br|Cl)\d+/g))add(m[0]);
  for(const m of q.matchAll(/(?:record\s*|记录\s*)(\d+)/ig))add(`Record ${m[1]}`);
  for(const m of q.matchAll(/\b[A-Z][A-Z0-9]{2,7}\b/g)){if(!['STE','NIR'].includes(m[0]))add(m[0])}
  return a.slice(0,28)
}
function filters(q:string){const f:any={document_types:['article'],release_status:'Core - Verified'};const rec=[...q.matchAll(/(?:record\s*|记录\s*)(\d+)/ig)].map(m=>Number(m[1]));if(rec.length)f.record_ids=[...new Set(rec)];if(/iodide|iodocuprate|cu\s*\(?i\)?[-– ]*i|铜碘|碘化/i.test(q)&&!/mixed[- ]?halide|混卤/i.test(q))f.halogen='I';else if(/bromide|bromocuprate|铜溴|溴化/i.test(q))f.halogen='Br';else if(/chloride|chlorocuprate|铜氯|氯化/i.test(q))f.halogen='Cl';const dm=q.match(/\b([0-3])D\b|([零一二三])维/i);if(dm){const m:any={'零':'0','一':'1','二':'2','三':'3'};f.dimension=(dm[1]||m[dm[2]])+'D'}const ys=(q.match(/\b(?:19|20)\d{2}\b/g)||[]).map(Number);if(ys.length===1){f.year_min=ys[0];f.year_max=ys[0]}else if(ys.length>1){f.year_min=Math.min(...ys);f.year_max=Math.max(...ys)}const ev=(q.match(/(?:evidence|证据(?:等级)?)\s*[-:：]?\s*([ABCD])\b/i)||[])[1];if(ev)f.evidence_level=ev.toUpperCase();return f}
async function embed(q:string){let last:any;for(let i=0;i<2;i++){try{const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT}/ai/run/${EMBED}`,{method:'POST',headers:{authorization:`Bearer ${CF_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({text:[q]}),signal:AbortSignal.timeout(10000)}),raw=await r.text();let x:any;try{x=JSON.parse(raw)}catch{x={}};const v=x?.result?.data?.[0];if(!r.ok||x?.success===false||!Array.isArray(v)||v.length!==1024)throw Error(x?.errors?.[0]?.message||`embedding ${r.status}`);return v}catch(e){last=e;if(!i)await sleep(180)}}throw last}
async function precision(q:string,f:any,n:number){return rpc('cuhalide_atlas_precision_search_v9',{p_release_version:RELEASE,p_terms:terms(q),p_match_count:n,p_filters:f})}
async function hybrid(q:string,v:number[],f:any,n:number){return rpc('cuhalide_atlas_hybrid_search_v9',{p_release_version:RELEASE,p_query_text:q,p_query_embedding:v,p_match_count:n,p_filters:f,p_full_text_weight:1.1,p_semantic_weight:1,p_rrf_k:50})}
function id(d:any){return`A:${d.record_id}`}
function merge(...groups:any[][]){const m=new Map<string,any>();for(const g of groups)for(const d of g||[]){if(d?.document_type!=='article')continue;const k=id(d),o=m.get(k);if(!o||Number(d.precision_score||d.hybrid_score||0)>Number(o.precision_score||o.hybrid_score||0))m.set(k,d)}return[...m.values()]}
function articleText(d:any){return`${d.title||''}\n${d.content||''}\n${JSON.stringify(d.llm_context||{})}`}
function gates(q:string){const gs:RegExp[]=[];if(CROWN.test(q))gs.push(CROWN);if(STE.test(q))gs.push(STE);if(CUCU.test(q))gs.push(CUCU);if(CLUSTER.test(q))gs.push(/cluster[- ]?center|cluster centered|3cc|簇中心/i);if(THERMO.test(q))gs.push(/thermochrom|temperature|77\s*K|295\s*K|温度|热致/i);if(MECH.test(q))gs.push(MECH);if(SCINT.test(q))gs.push(SCINT);if(NIR.test(q))gs.push(NIR);if(CONDUCT.test(q))gs.push(CONDUCT);if(STABILITY.test(q))gs.push(STABILITY);if(SEMICON.test(q))gs.push(SEMICON);if(PHASE_REL.test(q))gs.push(PHASE_REL);if(MOTIF.test(q))gs.push(MOTIF);if(ASSEMBLY.test(q))gs.push(ASSEMBLY);if(CHIRAL.test(q))gs.push(CHIRAL);if(EMISSION.test(q))gs.push(EMISSION);return gs}
function conceptGate(q:string,docs:any[]){const gs=gates(q);if(!gs.length)return docs;return docs.filter(d=>{const t=articleText(d);return gs.every(r=>r.test(t))})}
async function rerank(q:string,docs:any[],n:number){if(!docs.length)return[];try{const contexts=docs.map(d=>({text:`${id(d)} ${d.title||''}\n${articleText(d).slice(0,3000)}`})),r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT}/ai/run/${RERANK}`,{method:'POST',headers:{authorization:`Bearer ${CF_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({query:q,contexts,top_k:Math.min(n,contexts.length)}),signal:AbortSignal.timeout(10000)}),raw=await r.text();let x:any;try{x=JSON.parse(raw)}catch{x={}};if(!r.ok||x?.success===false)throw Error('rerank failed');const arr=Array.isArray(x?.result?.response)?x.result.response:Array.isArray(x?.result)?x.result:Array.isArray(x?.response)?x.response:[];const out:any[]=[];for(const z of arr){const k=Number(z.index??z.id??z.context_index??z.contextIndex);if(Number.isInteger(k)&&docs[k])out.push({...docs[k],rerank_score:Number(z.score??z.relevance_score??0)})}return out.length?out.slice(0,n):docs.slice(0,n)}catch{return docs.slice(0,n)}}
function articleLine(d:any,z:boolean){const c=d.llm_context||{},p:string[]=[];if(c.compounds)p.push(`${z?'体系':'system(s)'} ${c.compounds}`);if(c.dimension)p.push(`${z?'维度':'dimension'} ${c.dimension}`);if(c.reported_structure)p.push(`${z?'结构':'structure'} ${c.reported_structure}`);if(c.space_groups)p.push(`${z?'空间群':'space group(s)'} ${c.space_groups}`);if(c.emission_nm)p.push(`${z?'发射':'emission'} ${c.emission_nm} nm`);if(c.emission_assignment)p.push(`${z?'发光证据':'photophysics'} ${c.emission_assignment}`);if(c.scope_status)p.push(`scope=${c.scope_status}`);if(c.release_status)p.push(`release=${c.release_status}`);if(c.evidence_level)p.push(`${z?'证据':'evidence'} ${c.evidence_level}`);return`- [A:${d.record_id}] **${d.title}** — ${p.join('; ')}`}
function articleCard(d:any){return{type:'article',id:d.record_id,record_id:d.record_id,title:d.title,doi:d.evidence?.doi||d.llm_context?.doi||'',evidence:d.evidence||{},rerank_score:d.rerank_score??null,hybrid_score:d.hybrid_score??null,evidence_scope:'article-grain curated evidence'}}

const STRUCT_SELECT='structure_id,record_id,label,formula,phase,halogen_effective,halogen_basis,halogen_scope,halogen_confidence,dimensionality,dimension_class,space_group,point_group,crystal_system,polar,sg_confidence,mapping_confidence,eligibility,ccdc_cif,doi,doi_url,known_erratum,erratum_note';
async function safeStructuresByIds(ids:string[]){const a=[...new Set(ids.filter(Boolean))].slice(0,40);if(!a.length)return[];const val=encodeURIComponent(`(${a.join(',')})`);return rest(`cuhalide_atlas_public_structures_v301?select=${STRUCT_SELECT}&structure_id=in.${val}&order=structure_id.asc`)}
async function safeStructuresByRecords(ids:number[]){const a=[...new Set(ids.filter(Number.isFinite))].slice(0,12);if(!a.length)return[];const val=encodeURIComponent(`(${a.join(',')})`);return rest(`cuhalide_atlas_public_structures_v301?select=${STRUCT_SELECT}&record_id=in.${val}&eligibility=eq.Core%20-%20Included&order=record_id.asc,structure_id.asc&limit=24`)}
function safeLine(s:any,z:boolean){const p:string[]=[];if(s.formula)p.push(`${z?'化学式':'formula'} ${s.formula}`);if(s.halogen_effective)p.push(`${z?'卤素':'halogen'} ${s.halogen_effective} (${s.halogen_scope||'unresolved'}, ${s.halogen_confidence||'Unresolved'})`);if(s.dimension_class||s.dimensionality)p.push(`${z?'维度':'dimension'} ${s.dimension_class||s.dimensionality}`);if(s.space_group)p.push(`SG ${s.space_group}`);if(s.point_group)p.push(`${z?'点群':'point group'} ${s.point_group}`);if(s.polar)p.push(`polar=${s.polar}`);if(s.sg_confidence)p.push(`SG-confidence=${s.sg_confidence}`);return`- [S:${s.structure_id}] **${s.label||s.structure_id}** — ${p.join('; ')|| (z?'仅结构身份/晶体学字段':'structure identity/crystallography only')}`}
function structureCard(s:any){return{type:'structure',id:s.structure_id,record_id:s.record_id,title:s.label||s.structure_id,formula:s.formula||'',doi:s.doi||'',url:s.doi_url||'',space_group:s.space_group||'',dimensionality:s.dimension_class||s.dimensionality||'',evidence_scope:'structure identity/crystallography only',halogen:s.halogen_effective||'',halogen_scope:s.halogen_scope||'unresolved',halogen_confidence:s.halogen_confidence||'Unresolved'}}

async function articleOnly(q:string,depth:string){const f=filters(q),v=await embed(`CuHalide Atlas release ${RELEASE} article-grain scientific retrieval. ${q}`),n=depth==='deep'?30:24,[p,h]=await Promise.all([precision(q,f,n),hybrid(q,v,f,n)]),rawPool=merge(p,h),pool=conceptGate(q,rawPool),ranked=await rerank(q,pool,depth==='deep'?12:10),z=zh(q);let structs:any[]=[];if(STRUCTURE_RECORD_REQUEST.test(q)&&ranked.length)structs=await safeStructuresByRecords(ranked.slice(0,6).map(d=>Number(d.record_id)));const head=z?'### 检索到的冻结证据':'### Retrieved frozen evidence',boundary=z?'> **证据粒度边界：** 科学性质、发光、稳定性、输运和结构基元等概念只从 article-grain 科学证据检索；结构卡仅在明确要求结构记录时附加，并严格限制为身份/晶体学字段。':'> **Evidence-grain boundary:** scientific properties, photophysics, stability, transport and structural-motif concepts are retrieved from article-grain scientific evidence; structure cards are added only when structure records are explicitly requested and are restricted to identity/crystallography.';const lines=ranked.length?ranked.map(d=>articleLine(d,z)):[z?'- 当前条件下没有 article-grain 冻结记录通过证据概念门控。':'- No article-grain frozen record passed the evidence-concept gate for the current constraints.'];if(structs.length){lines.push('',z?'### 对应的安全结构记录':'### Corresponding safe structure records',...structs.map(s=>safeLine(s,z)))}return{ok:true,release:RELEASE,version:VERSION,answer:[head,...lines,'',boundary].join('\n'),sources:[...ranked.map(articleCard),...structs.map(structureCard)],trace:[{tool:'scientific_evidence_grain_router_v9110',args:{article_science_only:true,legacy_structure_science_excluded:true,explicit_structure_projection:STRUCTURE_RECORD_REQUEST.test(q)}},{tool:'article_precision_hybrid_retrieval',result_count:rawPool.length},{tool:'article_concept_gate',result_count:pool.length},{tool:'bge_reranker',args:{model:RERANK},result_count:ranked.length},{tool:'safe_structure_projection',result_count:structs.length}],provider:'evidence-grain-safe-retrieval-v9',model:'none',embedding_model:EMBED,reranker_model:RERANK,hybrid_rag:true,write_access:false,production:false}}

async function projectLegacyStructures(x:any){const ans=String(x?.answer||''),ids=[...ans.matchAll(/\[S:([A-Za-z0-9_-]+)\]/g)].map(m=>m[1]);for(const s of Array.isArray(x?.sources)?x.sources:[])if(s?.type==='structure'&&s?.id)ids.push(String(s.id));const rows=await safeStructuresByIds(ids),map=new Map(rows.map((r:any)=>[r.structure_id,r])),z=zh(ans);const answer=ans.split('\n').map(line=>{const m=line.match(/^\s*-\s*\[S:([A-Za-z0-9_-]+)\]/);if(!m)return line;const r=map.get(m[1]);return r?safeLine(r,z):`- [S:${m[1]}] ${z?'结构身份/晶体学安全投影不可用；旧结构科学文本已抑制。':'safe structure identity/crystallography projection unavailable; legacy structure science text suppressed.'}`}).join('\n');const sources=(Array.isArray(x?.sources)?x.sources:[]).map((s:any)=>{if(s?.type!=='structure')return s;const r=map.get(String(s.id));return r?structureCard(r):{type:'structure',id:String(s.id||''),record_id:s.record_id||null,title:String(s.title||'Structure'),evidence_scope:'structure identity/crystallography only'}});return{...x,answer,sources,trace:[...(Array.isArray(x?.trace)?x.trace:[]),{tool:'safe_structure_projection_v9110',args:{reconstructed_structure_lines:true,legacy_structure_science_text_suppressed:true},result_count:rows.length}],structure_grain_projection:'identity-and-crystallography-only'}}
async function legacy(req:Request,method:string,body?:string){const headers:any={apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json','user-agent':'CuHalide-Safe-Core/9.11.0'};const c=client(req);if(c)headers['x-cuhalide-client']=c;const r=await fetch(LEGACY,{method,headers,body,signal:AbortSignal.timeout(method==='GET'?35000:85000)}),raw=await r.text();let x:any;try{x=JSON.parse(raw)}catch{x={error:'invalid legacy core response'}};return{r,x}}

Deno.serve(async(req:Request)=>{try{
  if(req.method==='GET'){const {r,x}=await legacy(req,'GET');const ok=r.ok&&x?.ok===true;return json({...x,ok,version:VERSION,legacy_core_version:x?.version||'',agent:'CuHalide Atlas RAG v9 evidence-grain-safe core',checks:{...(x?.checks||{}),structure_safe_scientific_projection:true,legacy_structure_motif_photophysics_excluded:true,conceptual_article_only_isolation:true,article_concept_gate:true,legacy_structure_lines_reconstructed_from_safe_projection:true,broad_science_router:true,mixed_science_structure_projection:true},architecture:{...(x?.architecture||{}),public_scientific_projection:'soft scientific concepts are article-grain; structure lines are reconstructed exclusively from a safe identity/crystallography projection'}},ok?200:503)}
  if(req.method!=='POST')return json({error:'method not allowed'},405);
  const raw=await req.text();let b:any;try{b=JSON.parse(raw)}catch{return json({error:'invalid JSON'},400)}const q=lastUser(b);if(!q)return json({error:'user message required'},400);
  if(shouldArticleOnly(q)){const rl=await rate(req,b?.depth==='deep'?3:2);if(!rl?.allowed)return json({ok:false,error:'Smart RAG rate limit reached',release:RELEASE,version:VERSION,rate_limit:rl},429);return json(await articleOnly(q,b?.depth==='deep'?'deep':'standard'),200)}
  const {r,x}=await legacy(req,'POST',raw);const safe=await projectLegacyStructures(x);return json({...safe,version:VERSION,legacy_core_version:x?.version||'',production:false},r.status)
}catch(e){console.error('[safe-core-v9.11.0]',e);return json({ok:false,error:'Evidence-grain-safe RAG core unavailable',release:RELEASE,version:VERSION},503)}});
