declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const UP='https://tyxnyjyrfzspwcfjpzus.supabase.co/functions/v1/cuhalide-atlas-meta-v302-stable';
const RELEASE='3.0.2',SITE='48',VERSION='48.1';
const PUBLIC='https://cuhalide-atlas-v3.vercel.app';
const ALLOWED=new Set([PUBLIC,'http://localhost:8765','http://127.0.0.1:8765']);
function cors(req:Request){const o=req.headers.get('origin')||'';return{'access-control-allow-origin':ALLOWED.has(o)?o:PUBLIC,'access-control-allow-methods':'GET,HEAD,OPTIONS','access-control-allow-headers':'accept,content-type','vary':'Origin'}}
function headers(req:Request,up?:Headers){return{...cors(req),'content-type':up?.get('content-type')||'application/json; charset=utf-8','cache-control':up?.get('cache-control')||'no-store','x-content-type-options':'nosniff','x-cuhalide-release':up?.get('x-cuhalide-release')||RELEASE,'x-cuhalide-site-version':up?.get('x-cuhalide-site-version')||SITE,'x-cuhalide-meta-version':up?.get('x-cuhalide-meta-version')||VERSION,'x-cuhalide-current-curated-revision':up?.get('x-cuhalide-current-curated-revision')||'1'}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(!['GET','HEAD'].includes(req.method))return new Response('Method Not Allowed',{status:405,headers:headers(req)});try{const incoming=new URL(req.url),u=new URL(UP);for(const[k,v]of incoming.searchParams.entries())u.searchParams.append(k,v);const r=await fetch(u,{method:req.method,headers:{accept:req.headers.get('accept')||'*/*','user-agent':'CuHalide-Atlas-Canonical-Meta/48.1'},signal:AbortSignal.timeout(60000)}),body=req.method==='HEAD'?null:await r.text();return new Response(body,{status:r.status,headers:headers(req,r.headers)})}catch(e){console.error('[canonical-meta-v481]',e);return new Response(JSON.stringify({ok:false,error:'metadata unavailable',release:RELEASE,version:VERSION}),{status:503,headers:headers(req)})}});
