declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,CF_ACCOUNT=Deno.env.get('CLOUDFLARE_ACCOUNT_ID')||'',CF_TOKEN=Deno.env.get('CLOUDFLARE_API_TOKEN')||'';
const EXACT=`${BASE}/functions/v1/cuhalide-atlas-current-rag-r1-internal`,VERSION='current-rag-r1.1.0',RELEASE='3.0.2',EMBED='@cf/baai/bge-m3',RERANK='@cf/baai/bge-reranker-base';
const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow','x-cuhalide-release':RELEASE,'x-cuhalide-current-curated-revision':'1'};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});const zh=(s:string)=>/[\u3400-\u9fff]/.test(s);
function lastUser(b:any){const m=Array.isArray(b?.messages)?b.messages:[];return String([...m].reverse().find((z:any)=>z?.role==='user'&&typeof z.content==='string')?.content||'').trim()}
function exact(q:string){return /literature\s*cutoff|cutoff|coverage\s*through|curated\s*through|current\s*curated|currently\s*curated|文献截止|截止日期|当前策展|当前收录|目前收录|最新策展|覆盖到|策展到|(?:record\s*|记录\s*)3(?:4[7-9]|5\d|6[0-2])\b|CUH-(?:34[7-9]|35\d|36[0-2])-S\d{2}|10\.\d{4,9}\/[\w.()/:;-]+/i.test(q)}
async function callExact(raw?:string){const r=await fetch(EXACT,{method:raw?'POST':'GET',headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json'},body:raw,signal:AbortSignal.timeout(raw?90000:30000)}),t=await r.text();let x:any;try{x=JSON.parse(t)}catch{x={error:'invalid exact-current response'}};return{r,x}}
async function rpc(n:string,b:any){const r=await fetch(`${BASE}/rest/v1/rpc/${n}`,{method:'POST',headers:{apikey:KEY,authorization:`Bearer ${KEY}`,'content-type':'application/json'},body:JSON.stringify(b),signal:AbortSignal.timeout(30000)}),t=await r.text();if(!r.ok)throw Error(t.slice(0,400));return JSON.parse(t)}
async function embed(q:string){const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT}/ai/run/${EMBED}`,{method:'POST',headers:{authorization:`Bearer ${CF_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({text:[q]}),signal:AbortSignal.timeout(12000)}),t=await r.text();let x:any;try{x=JSON.parse(t)}catch{x={}};const v=x?.result?.data?.[0];if(!r.ok||x?.success===false||!Array.isArray(v)||v.length!==1024)throw Error(x?.errors?.[0]?.message||`embedding ${r.status}`);return v}
async function rerank(q:string,docs:any[],n=12){if(!docs.length)return[];try{const contexts=docs.map((d:any)=>({text:`${d.release_version} ${d.document_type}:${d.document_key} ${d.title||''}\n${String(d.content||'').slice(0,3000)}`}));const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${CF_ACCOUNT}/ai/run/${RERANK}`,{method:'POST',headers:{authorization:`Bearer ${CF_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({query:q,contexts,top_k:Math.min(n,contexts.length)}),signal:AbortSignal.timeout(12000)}),t=await r.text();let x:any;try{x=JSON.parse(t)}catch{x={}};if(!r.ok||x?.success===false)throw Error('rerank failed');const arr=Array.isArray(x?.result?.response)?x.result.response:Array.isArray(x?.result)?x.result:Array.isArray(x?.response)?x.response:[];const out:any[]=[];for(const z of arr){const i=Number(z.index??z.id??z.context_index??z.contextIndex);if(Number.isInteger(i)&&docs[i])out.push({...docs[i],rerank_score:Number(z.score??z.relevance_score??0)})}return out.length?out.slice(0,n):docs.slice(0,n)}catch{return docs.slice(0,n)}}
function card(d:any){const c=d.llm_context||{},e=d.evidence||{};if(d.document_type==='article')return{type:'article',id:d.record_id,record_id:d.record_id,title:d.title||'',doi:e.doi||c.doi||'',url:e.doi_url||'',curation_layer:'Current Curated',live_revision:1,coverage_class:c.coverage_class||d.metadata?.coverage_class||'',evidence_scope:'article-grain curated evidence',retrieval_score:d.rerank_score??d.hybrid_score??null};return{type:'structure',id:d.structure_id,record_id:d.record_id,title:d.title||d.structure_id,doi:e.doi||c.doi||'',url:e.doi_url||'',formula:c.formula||'',phase:c.phase||'',space_group:c.space_group||'',dimensionality:c.dimension||'',halogen:c.halogen||'',curation_layer:'Current Curated',live_revision:1,coverage_class:c.coverage_class||d.metadata?.coverage_class||'',evidence_scope:'structure identity/crystallography only',retrieval_score:d.rerank_score??d.hybrid_score??null}}
Deno.serve(async(req:Request)=>{try{if(req.method==='GET'){const z=await callExact();return json({...z.x,version:VERSION,unified_hybrid:true,unified_document_count:1283},z.r.status)}if(req.method!=='POST')return json({error:'method not allowed'},405);const raw=await req.text();let b:any;try{b=JSON.parse(raw)}catch{return json({error:'invalid JSON'},400)}const q=lastUser(b);if(!q)return json({error:'user message required'},400);if(exact(q)){const z=await callExact(raw);return json({...z.x,version:VERSION,unified_hybrid:true},z.r.status)}const v=await embed(q),pool=await rpc('cuhalide_atlas_hybrid_search_current_v1',{p_query_text:q,p_query_embedding:v,p_match_count:24,p_filters:{},p_full_text_weight:1.1,p_semantic_weight:1,p_rrf_k:50}),ranked=await rerank(q,pool,12),inc=ranked.filter((d:any)=>d.release_version==='current-curated-r1'),explicit=/CUH-\d{3}-S\d{2}|structure|crystallograph|phase|结构|晶体|空间群|相/i.test(q),safe=inc.filter((d:any)=>d.document_type==='article'||explicit).slice(0,6),z=zh(q),lines=safe.map((d:any)=>d.document_type==='article'?`- [A:${d.record_id}] **${d.title}** — DOI ${d.evidence?.doi||d.llm_context?.doi||''}; ${z?'覆盖类型':'coverage'}=${d.llm_context?.coverage_class||d.metadata?.coverage_class||'current'}.`:`- [S:${d.structure_id}] **${d.title}** — ${z?'化学式':'formula'} ${d.llm_context?.formula||''}; ${z?'条件':'phase/condition'} ${d.llm_context?.phase||''}; SG ${d.llm_context?.space_group||''}; ${z?'维度':'dimension'} ${d.llm_context?.dimension||''}.`);return json({ok:true,release:RELEASE,current_release:'current-curated-r1',version:VERSION,relevant_incremental:safe.length>0,answer:safe.length?`${z?'### Current Curated rev.1 增量证据':'### Current Curated rev.1 incremental evidence'}\n${lines.join('\n')}\n\n${z?'> 此增量层经过主文/SI/晶体学 QC；不改写 Frozen Release 3.0.2。结构卡只承担身份/晶体学证据。':'> This incremental layer passed primary-article/SI/crystallographic QC and does not rewrite Frozen Release 3.0.2. Structure cards support identity/crystallography only.'}`:'',sources:safe.map(card),mode:'unified-hybrid-supplement',operational_mode:'FULL',embedding_model:EMBED,reranker_model:RERANK,trace:[{tool:'unified_frozen_current_hybrid_search_v1',pool:pool.length,reranked:ranked.length,incremental_in_top:inc.length}],write_access:false})}catch(e){console.error('[current-rag-unified]',e);return json({ok:false,error:'Unified Current Curated RAG supplement unavailable',release:RELEASE,version:VERSION,relevant_incremental:false},503)}});
