declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const UP=`${BASE}/functions/v1/cuhalide-atlas-current-rag-r8-science-exact-internal`;
const CURRENT='current-curated-r9',VERSION='current-rag-r9-science-exact-1.0.1',PHOTOPHYSICS_CONTRACT='1.4.0',ORGANIC_COMPONENTS_CONTRACT='1.2.0';
const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow, noarchive','x-cuhalide-release':'3.0.2','x-cuhalide-current-curated-revision':'9','x-cuhalide-photophysics-contract':PHOTOPHYSICS_CONTRACT,'x-cuhalide-organic-components-contract':ORGANIC_COMPONENTS_CONTRACT,'x-cuhalide-endpoint-state':'internal-service-only'};
const send=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
function internal(req:Request){return req.headers.get('authorization')===`Bearer ${KEY}`&&req.headers.get('apikey')===KEY}
function patch(x:any):any{if(Array.isArray(x))return x.map(patch);if(!x||typeof x!=='object')return x;const o:any={};for(const[k,v]of Object.entries(x)){if(k==='live_revision'||k==='current_curated_revision')o[k]=9;else if(k==='current_release')o[k]=CURRENT;else if(k==='organic_component_contract'||k==='organic_components_contract')o[k]=ORGANIC_COMPONENTS_CONTRACT;else if(typeof v==='string')o[k]=v.replace(/Current Curated rev\.8/g,'Current Curated rev.9').replace(/Current Curated rev\.7/g,'Current Curated rev.9').replace(/current-curated-r8/g,CURRENT).replace(/current-curated-r7/g,CURRENT);else o[k]=patch(v)}return o}
Deno.serve(async(req:Request)=>{if(!internal(req))return send({ok:false,error:'internal service authorization required'},401);if(!['GET','POST'].includes(req.method))return send({error:'method not allowed'},405);try{const raw=req.method==='POST'?await req.text():undefined;const r=await fetch(UP,{method:req.method,headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json'},body:raw,signal:AbortSignal.timeout(req.method==='POST'?90000:30000)}),t=await r.text();let x:any;try{x=JSON.parse(t)}catch{x={error:'invalid science-exact response'}};x=patch(x);x.current_release=CURRENT;x.version=VERSION;x.science_exact_version=VERSION;x.architecture='full-current-atomic-structure-snapshot';x.photophysics_contract=PHOTOPHYSICS_CONTRACT;x.organic_components_contract=ORGANIC_COMPONENTS_CONTRACT;x.current_curated_revision=9;return send(x,r.status)}catch(e){console.error('[current-rag-r9-science-wrapper]',e);return send({ok:false,error:'Current Curated rev.9 structured scientific layer unavailable',current_release:CURRENT,version:VERSION,photophysics_contract:PHOTOPHYSICS_CONTRACT,organic_components_contract:ORGANIC_COMPONENTS_CONTRACT},503)}});