export function integrateKnowledge(html){
 if(typeof html!=='string'||!html.includes('</head>')||html.includes('CUHALIDE_INTEGRATED_KNOWLEDGE_V1'))return html;
 let s=html.replace(/<a\b[^>]*data-study="ipa-pip"[^>]*>[\s\S]*?<\/a>/g,'');
 s=s.replace('</head>','<meta name="cuhalide-knowledge-contract" content="1.3.0"><link rel="stylesheet" href="/ui-knowledge-v1.css"><link rel="stylesheet" href="/cuxplore-v1.css"></head>');
 s=s.replace('</body>','<!-- CUHALIDE_INTEGRATED_KNOWLEDGE_V1 --><script src="/cuxplore-v1.js" defer></script><script src="/ui-knowledge-v1.js" defer></script></body>');
 s=s.replace('<h2>Filters</h2>','<h2>Filters</h2><label class="field"><span>Literature view</span><select id="knowledgeScope"><option value="all" selected>All literature</option><option value="curated">Linked structured data</option><option value="reviewed">Source-reviewed</option><option value="text">Indexed MAIN / SI text</option></select></label><p id="knowledgeFilterNote" class="fine">One DOI-deduplicated literature corpus; source and structured-data availability are shown per article.</p>');
 s=s.replace('<div class="cards" id="articles">','<div id="knowledgeArticles" hidden aria-live="polite"></div><div class="cards" id="articles">');
 const overview='<section class="shell ki-overview" aria-labelledby="kiCoverageHeading"><div class="ki-heading"><div><p class="eyebrow">Connected knowledge</p><h2 id="kiCoverageHeading">Literature, structures and retrieved evidence</h2></div><a href="#articles" class="fine">Search the literature catalog</a></div><div id="knowledgeCoverage" class="ki-coverage" aria-live="polite"><p class="fine">Checking indexed source coverage...</p></div><p id="knowledgeDates" class="fine"></p><p id="knowledgeDenominators" class="fine">Articles use one DOI-deduplicated literature denominator. Full-text coverage, source documents, structures, semantic records and text blocks are coverage metrics, not alternative article counts.</p></section>';
 s=s.replace('<div class="shell dashboard section">',overview+'<div class="shell dashboard section">');
 const retrieve='<section class="shell ki-retrieval panel" aria-labelledby="kiRetrieveHeading"><div class="ki-heading"><div><p class="eyebrow">Source search</p><h2 id="kiRetrieveHeading">Find the evidence behind an answer</h2></div><span class="ki-chip">Source search</span></div><form id="knowledgeForm" class="ki-search"><label class="field"><span>Research question or DOI</span><input id="knowledgeQuery" type="search" maxlength="600" placeholder="Ammonium, crown ether, inorganic connectivity..." required></label><label class="field"><span>Search scope</span><select id="knowledgeRagScope"><option value="all">All literature</option><option value="curated">Linked structured data</option><option value="reviewed">Source-reviewed</option><option value="text">Indexed MAIN / SI text</option></select></label><button type="submit" id="knowledgeRetrieve" class="btn primary">Retrieve evidence</button></form><p id="knowledgeStatus" class="fine" role="status">Ranked literature and source matches appear here. Open a record to inspect its evidence and data coverage.</p><div id="knowledgeResults" class="ki-results"></div><div id="knowledgeSelection" class="ki-selection" hidden><span id="knowledgeSelectionCount"></span><button id="knowledgeUse" class="btn secondary" type="button">Prepare evidence question</button><button id="knowledgeExport" class="btn secondary" type="button">Save context record</button><button id="knowledgeClear" class="btn secondary" type="button">Clear selection</button></div><details class="ki-trace"><summary>Retrieval record and evidence levels</summary><div id="knowledgeTrace" class="fine">No retrieval has been run.</div></details></section>';
 s=s.replace('<div class="shell rag-grid">',retrieve+'<div class="shell rag-grid">');
 s=s.replace('<p class="eyebrow">Evidence used</p><div id="sources">','<p class="eyebrow">Response sources</p><div id="sources">');
 s=s.replace('Talk naturally. The assistant handles ordinary conversation and general scientific explanations directly, then automatically consults CuHalide Atlas whenever a question requires database facts, source-linked evidence or protected scientific boundaries.','Ask a scientific question or first inspect relevant sources below. CuXplore keeps literature, structure and measurement evidence at the correct grain while linking supporting records.');
 s=s.replace('renderSources(x.sources||[]);','renderSources(x.sources||[]);window.CuHalideKnowledge?.showTrace(x);');
 s=s.replace('Curated literature · n = 370','Literature corpus · n = 410').replace('Core-Included structure rows · n = 890','Core-Included structure rows · n = 901').replace('Resolved structure rows · n = 747','Resolved structure rows · n = 761');
 s=s.replace('<strong>91</strong><small>strict-polar rows · 57 articles</small>','<strong>94</strong><small>strict-polar rows · 60 articles</small>').replace('id="pcount">91 rows','id="pcount">94 rows');
 s=s.replace('Current Curated rev.10, curated through 19 August 2026.','Current Curated rev.10, curated through 14 September 2026.');
 s=s.replace('Archived scientific snapshot 3.0.2 remains the immutable historical baseline, verified through 2026-06-30.','Archived scientific snapshot 3.0.2 remains the immutable historical baseline. Its scientific cutoff is 30 June 2026; the archived release was issued on 11 August 2026.');
 s=s.replaceAll('CuHalide Research Assistant','CuXplore');s=s.replaceAll('CuXplore Research Assistant','CuXplore');
 s=s.replace('<a data-route="rag" href="#rag">Research Assistant</a>','<a data-route="rag" href="#rag">CuXplore</a>');
 s=s.replace('<span>04 · Research Assistant</span><strong>Ask across evidence</strong>','<span>04 · CuXplore</span><strong>Ask across evidence</strong>');
 s=s.replace('<h1>CuXplore Research Assistant</h1>','<h1>CuXplore</h1><p class="cx-subtitle">Literature-grounded Cu(I) halide research</p>');
 s=s.replace('Smart RAG 10.0.0 searches the 1,322-document Current Curated rev.10 full-current evidence corpus.','CuXplore searches curated Atlas records together with indexed MAIN/SI text. Source matches support retrieval but do not replace scientific field verification.');
 return s;
}
