declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,ACC=Deno.env.get('CLOUDFLARE_ACCOUNT_ID')||'',TOKEN=Deno.env.get('CLOUDFLARE_API_TOKEN')||'';
const RELEASE='3.0.1',VERSION='qwen-claims-v9-1.3.3',LLM='@cf/qwen/qwen3-30b-a3b-fp8';
const ZH=(s:string)=>/[\u3400-\u9fff]/.test(s),sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const CAUSAL=/\bcaus(?:e|es|ed|ing)\b|\bdrive(?:s|n)?\b|\blead(?:s|ing)?\s+to\b|\bprove(?:s|d)?\b|导致|驱动|证明|必然造成|决定了|根本原因/i;
const UNIVERSAL=/\ball\b|\bevery\b|\buniversal\b|所有.*体系|普遍规律|必然/i;
const SPEC=/\b(?:may|might|could|possibly|potentially|perhaps|likely|suggests?|appears?\s+to)\b|可能|或许|也许|推测|猜测/i;
const RECOMMEND=/\b(?:recommend|recommended|promising|priority|worth|suitable|best candidate)\b|推荐|值得|优先|最有潜力|最佳候选/i;
const ASSIGN=/assign(?:ed|ment)?|attribut(?:e|ed|ion)|ascrib(?:e|ed)|originat|arise\s+from|due\s+to|归属|归因|源于|起源/i;
const RELATION=/correlat|relationship|relation|linked?|associated|interact|bond(?:ing)?|coupl|depend(?:ence|ent)|changes?|modulat|population|coordinates?\s+(?:with|to)|相关|关系|关联|相互作用|成键|耦合|依赖|变化|调制|配位于/i;
const UNKNOWN=/unresolved|unknown|not established|not reported|not available|未解析|未知|未建立|未报告|不可用/i;
const CONCEPTS=[/self[- ]?trapped|\bste\b|自陷|自俘获/i,/cu\s*[·.]{1,}\s*cu|cu[-−]\s*cu|cuprophil|铜铜/i,/cluster[- ]?center|簇中心|3CC/i,/crown[- ]?ether|冠醚|18[- ]?crown|18c6/i,/ferroelectric|铁电/i,/phosphorescen|磷光/i,/vibronic|electron[- ]?phonon|电子[- ]?声子/i,/MLCT|XLCT|LMCT|charge[- ]?transfer|电荷转移/i,/plqy|quantum yield|量子产率/i,/lifetime|寿命/i,/thermochrom|temperature|温度|热致/i];
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow','x-cuhalide-release':RELEASE,'x-cuhalide-claims-version':VERSION}});
const norm=(s:string)=>String(s||'').normalize('NFKC').toLowerCase().replace(/[‐‑‒–—−]/g,'-').replace(/\s+/g,' ').trim();
async function rest(path:string){const r=await fetch(`${BASE}/rest/v1/${path}`,{headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json'},signal:AbortSignal.timeout(15000)}),t=await r.text();if(!r.ok)throw Error(`REST ${r.status}`);return t?JSON.parse(t):[]}
function did(d:any){return d.type==='structure'?`S:${d.id}`:`A:${d.id}`}
function article(c:any){return{'Record ID':c.record_id,'Article Title':c.title,'DOI':c.doi,'Year':c.year,'Journal':c.journal,'Halogen':c.halogen,'Compounds':c.compounds,'Dimension':c.dimension,'Category':c.category,'Reported Structure':c.reported_structure,'Space Groups':c.space_groups,'Emission Wavelength(s) (nm)':c.emission_nm,'Emission Assignment / Conditions':c.emission_assignment,'Organic Component / Role':c.organic_role,'Scope Status':c.scope_status,'Evidence Level':c.evidence_level,'Evidence Sufficiency':c.evidence_sufficiency,'Canonical Release Status':c.release_status}}
function structure(c:any){return{'Record ID':c.record_id,'Structure ID':c.structure_id,'Structure Label / Compound':c.title,'DOI':c.doi,'Year':c.year,'Reported Formula':c.formula,'Halogen':c.halogen,'Structural Dimensionality':c.dimension,'Category':c.category,'Phase / Polymorph / Temperature':c.phase,'Space Group':c.space_group,'Point Group':c.point_group,'Crystal System':c.crystal_system,'Polar':c.polar,'Space-Group Evidence Confidence':c.sg_confidence,'Mapping Confidence':c.mapping_confidence,'Structure Inclusion Status':c.inclusion_status,'Canonical Structure Dataset Eligibility':c.canonical_eligibility}}
function scientific(d:any){const o=d.type==='structure'?structure(d.context||{}):article(d.context||{});return Object.fromEntries(Object.entries(o).filter(([,v])=>v!==undefined&&v!==null&&String(v).trim()!==''))}
function txt(d:any){return Object.entries(scientific(d)).map(([k,v])=>`${k}: ${String(v)}`).join('\n')}
async function load(refs:any[]){const out:any[]=[];for(const s of refs.filter((x:any)=>x?.type==='article'||x?.type==='structure').slice(0,6)){try{const type=s.type,id=String(s.id),filter=type==='article'?`record_id=eq.${encodeURIComponent(id)}`:`structure_id=eq.${encodeURIComponent(id)}`;const rows=await rest(`cuhalide_atlas_rag_documents?release_version=eq.${RELEASE}&document_type=eq.${type}&${filter}&select=document_type,record_id,structure_id,llm_context&limit=1`),r=rows?.[0];if(r)out.push({type,id:type==='article'?r.record_id:r.structure_id,record_id:r.record_id,context:r.llm_context||{}})}catch{}}return out}
function tool(){return{name:'submit_claims',description:'Submit only claims independently supported by one listed source. You must call this function and output no prose.',parameters:{type:'object',properties:{claims:{type:'array',maxItems:4,items:{type:'object',properties:{source_id:{type:'string'},claim_type:{type:'string',enum:['direct_observation','explicit_assignment','explicit_relation','not_established']},text:{type:'string'},support_quote:{type:'string'}},required:['source_id','claim_type','text','support_quote']}}},required:['claims']}}}
function parse(v:any){if(v&&typeof v==='object')return v;if(typeof v==='string')try{return JSON.parse(v)}catch{}return null}
function extract(x:any){const all=[...(x?.result?.tool_calls||[]),...(x?.result?.response?.tool_calls||[]),...(x?.tool_calls||[]),...(x?.response?.tool_calls||[])];for(const z of all)if((z?.name||z?.function?.name)==='submit_claims'){const a=parse(z?.arguments??z?.function?.arguments);if(a&&Array.isArray(a.claims))return a}return null}
async function oneCall(q:string,ds:any[],mandatory:boolean){const zh=ZH(q),context=ds.map(d=>`[${did(d)}]\n${txt(d).slice(0,d.type==='article'?5500:3000)}`).join('\n\n');const system=(zh?'你是':'You are')+` CuHalide Atlas release ${RELEASE} bounded scientific claim extractor. `+(zh?'必须调用 submit_claims，不能输出普通文本。每条 claim 必须仅由一个来源单独支持，support_quote 必须逐字来自该来源。禁止推测、推荐、跨文献机理拼接和普遍因果；未解析保持未解析；极性不等于铁电。claim 可使用中文或英文，语言不是科学有效性的判据。':'You MUST call submit_claims and output no prose. Every claim must be supported by exactly one source and support_quote must be verbatim from that source. No speculation, recommendation, cross-paper mechanism stitching, universal causality, or inference of unresolved values; polar does not mean ferroelectric.');const prompt=`${zh?'问题':'QUESTION'}:\n${q}\n\n${zh?'可用来源':'ALLOWED SOURCES'}:\n${context}\n\n${mandatory?(zh?'强制要求：现在调用 submit_claims。即使只能安全提交一条 direct_observation，也必须提交；不要返回普通文本。':'MANDATORY: call submit_claims now. If only one direct_observation is safely supported, submit that one; do not return prose.') : ''}`;const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${ACC}/ai/run/${LLM}`,{method:'POST',headers:{authorization:`Bearer ${TOKEN}`,'content-type':'application/json'},body:JSON.stringify({messages:[{role:'system',content:system},{role:'user',content:prompt}],tools:[tool()],temperature:0,max_tokens:850}),signal:AbortSignal.timeout(24000)}),x=await r.json().catch(()=>({}));if(!r.ok||x?.success===false)throw Error(x?.errors?.[0]?.message||`Workers AI ${r.status}`);return extract(x)}
async function call(q:string,ds:any[]){let last:any=null;const plans=[ds.slice(0,4),ds.slice(0,2),ds.slice(0,1)];for(let i=0;i<plans.length;i++){if(!plans[i].length)continue;try{const a=await oneCall(q,plans[i],i>0);if(a)return{raw:a,used:plans[i].map(did),attempt:i+1}}catch(e){last=e}if(i<plans.length-1)await sleep(160)}throw last||Error('submit_claims tool call missing after adaptive retries')}
function tokenSet(s:string){return new Set(norm(s).replace(/[^a-z0-9\u3400-\u9fff]+/g,' ').split(/\s+/).filter(x=>x.length>1))}
function jac(a:string,b:string){const A=tokenSet(a),B=tokenSet(b);let n=0;for(const x of A)if(B.has(x))n++;return n/Math.max(1,A.size+B.size-n)}
function validate(raw:any,ds:any[],q:string){const map=new Map(ds.map(d=>[did(d),d])),accepted:any[]=[],checks:any[]=[],pairs=new Set<string>();for(const c of Array.isArray(raw?.claims)?raw.claims.slice(0,8):[]){const sid=String(c?.source_id||''),kind=String(c?.claim_type||''),claim=String(c?.text||'').trim().slice(0,800),quote=String(c?.support_quote||'').trim().slice(0,500),d=map.get(sid),pair=`${sid}|${kind}`;let why='';if(!d||!claim||!['direct_observation','explicit_assignment','explicit_relation','not_established'].includes(kind))why='unknown_source_or_invalid_claim';else if(pairs.has(pair))why='duplicate_source_claim_type';const source=d?txt(d):'';if(!why&&(!quote||norm(quote).length<8||!norm(source).includes(norm(quote))))why='support_quote_not_in_source';if(!why)for(const n of claim.match(/\d+(?:\.\d+)?/g)||[])if(!q.includes(n)&&!source.includes(n)){why=`number_not_in_source:${n}`;break}if(!why&&kind!=='not_established')for(const re of CONCEPTS)if(re.test(claim)&&!re.test(source)){why='concept_not_in_source';break}if(!why&&CAUSAL.test(claim))why='causal_language_disallowed';if(!why&&UNIVERSAL.test(claim))why='universal_language_disallowed';if(!why&&SPEC.test(claim))why='speculative_language_disallowed';if(!why&&RECOMMEND.test(claim))why='recommendation_disallowed';if(!why&&kind==='explicit_assignment'&&!ASSIGN.test(quote))why='assignment_not_explicit_in_quote';if(!why&&kind==='explicit_relation'&&!RELATION.test(quote))why='relation_not_explicit_in_quote';if(!why&&kind==='direct_observation'&&(ASSIGN.test(claim)||RELATION.test(claim)))why='relational_claim_wrong_type';if(!why&&kind==='not_established'&&!UNKNOWN.test(quote))why='absence_not_explicit_in_quote';if(!why&&accepted.some(x=>jac(x.text,claim)>.68))why='near_duplicate';if(why){checks.push({pass:false,source_id:sid,claim_type:kind,reason:why});continue}accepted.push({source_id:sid,claim_type:kind,text:claim});pairs.add(pair);checks.push({pass:true,source_id:sid,claim_type:kind,support_quote_verified:true,language_match:ZH(q)===ZH(claim)});if(accepted.length>=4)break}return{accepted,checks}}
Deno.serve(async(req:Request)=>{try{if(req.method!=='POST')return json({error:'method not allowed'},405);const b=await req.json().catch(()=>({})),q=String(b?.query||'').trim(),refs=Array.isArray(b?.sources)?b.sources:[];if(!q||!refs.length)return json({error:'query and sources required'},400);const ds=await load(refs);if(!ds.length)return json({ok:true,release:RELEASE,version:VERSION,model:'none',claims:[],checks:[],error:'no curated scientific context',source_count:0,write_access:false});let run:any=null,error='';try{run=await call(q,ds)}catch(e){error=String(e)}const v=run?validate(run.raw,ds,q):{accepted:[],checks:[]};return json({ok:true,release:RELEASE,version:VERSION,model:v.accepted.length?LLM:'none',claims:v.accepted,checks:v.checks,error,source_count:ds.length,adaptive_attempt:run?.attempt||0,adaptive_source_ids:run?.used||[],context_policy:'internal-rag-scientific-whitelist-v2',language_policy:'preferred-language-not-a-scientific-rejection-criterion',structure_grain_policy:'structure photophysics and motif excluded unless independently mapped',write_access:false})}catch(e){console.error('[qwen-claims-v9-1.3.3]',e);return json({ok:false,error:'claim service unavailable',release:RELEASE,version:VERSION},503)}});
