declare const Deno:any;
export const BASE=Deno.env.get('SUPABASE_URL')!, SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
export const DATA=`${BASE}/functions/v1/cuhalide-atlas-data-stable`;
export const VERSION='4.0.0', RELEASE='3.0.0';
export const ALLOWED=new Set(['https://cuhalide-atlas-v3.vercel.app','http://127.0.0.1:8765','http://localhost:8765']);
export type Row=Record<string,any>;
export type Source={type:'article'|'structure'|'web',id?:string|number,record_id?:string|number,title?:string,doi?:string,url?:string};
export type Plan=ReturnType<typeof plan>;
export const CENTRO=new Set(['-1','2/m','mmm','4/m','4/mmm','-3','-3m','6/m','6/mmm','m-3','m-3m']);
let CACHE:Promise<{articles:Row[],structures:Row[],polar:Row[]}>|null=null;
export function cors(req:Request){const o=req.headers.get('origin')||'';return{'access-control-allow-origin':ALLOWED.has(o)?o:'https://cuhalide-atlas-v3.vercel.app','vary':'Origin','access-control-allow-headers':'content-type, accept','access-control-allow-methods':'GET,POST,OPTIONS'}}
export function json(req:Request,x:any,status=200){return new Response(JSON.stringify(x),{status,headers:{...cors(req),'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}})}
export async function sha(text:string){const h=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)));return[...h].map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function rpc(name:string,body:any){const r=await fetch(`${BASE}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:SERVICE,authorization:`Bearer ${SERVICE}`,'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`${name} ${r.status}`);return await r.json()}
export async function data(action:string,params:Record<string,any>={}){const u=new URL(DATA);u.searchParams.set('action',action);for(const[k,v]of Object.entries(params))if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,String(v));const r=await fetch(u,{headers:{accept:'application/json'}});const t=await r.text();let x:any;try{x=JSON.parse(t)}catch{x={error:t}}if(!r.ok)throw new Error(x.error||`${action} ${r.status}`);return x}
export async function corpus(){if(CACHE)return CACHE;CACHE=(async()=>{const[a,s,p]=await Promise.all([data('articles'),data('structures'),data('polar')]);if(a.items?.length!==346||s.items?.length!==878||p.items?.length!==67)throw new Error(`corpus invariant ${a.items?.length}/${s.items?.length}/${p.items?.length}`);return{articles:a.items as Row[],structures:s.items as Row[],polar:p.items as Row[]}})().catch(e=>{CACHE=null;throw e});return CACHE}
export const norm=(v:any)=>String(v??'').normalize('NFKC').toLowerCase().replace(/[−–—]/g,'-').replace(/\s+/g,' ').trim();
export const compact=(v:any,n=120)=>{const s=String(v??'').replace(/\s+/g,' ').trim();return s.length>n?s.slice(0,n-1)+'…':s};
export function verified(s:Row){return s['Canonical Structure Dataset Eligibility']==='Core - Included'&&s['Structure Inclusion Status']==='Included'&&s['Space-Group Status']==='Resolved'&&['High','Medium'].includes(s['Space-Group Evidence Confidence'])&&['High','Medium'].includes(s['Mapping Confidence'])}
export function pointGroup(s:Row){const p=String(s['Point Group']||'').trim();return p&&!/unresolved/i.test(p)?p:''}
export function centro(s:Row){const p=pointGroup(s);return Boolean(p&&CENTRO.has(p))}
export function noncentro(s:Row){const p=pointGroup(s);return Boolean(p&&!CENTRO.has(p))}
export function nums(v:any){return(String(v??'').match(/\d+(?:\.\d+)?/g)||[]).map(Number).filter(Number.isFinite)}
export function explicitRelation(x:string){return/关系|区别|差别|relation|relationship|difference|versus|vs\.?/i.test(x)}
export function plan(q:string,sgs:string[]=[]){const x=norm(q),nonRx=/non[- ]?centrosymmetric|non centrosymmetric|noncentrosymmetric|非中心对称/i,noncentrosymmetric=nonRx.test(x),rest=x.replace(/non[- ]?centrosymmetric|non centrosymmetric|noncentrosymmetric|非中心对称/ig,' '),centrosymmetric=/\bcentrosymmetric\b|中心对称/i.test(rest),relation=explicitRelation(x),strictPolar=/strict\s+polar|严格极性/i.test(x),polarLevelCompare=strictPolar&&/(?:verified|generic|一般|普通)[^。；;]{0,30}(?:polar|极性)|(?:polar|极性)[^。；;]{0,30}(?:verified|generic|一般|普通)/i.test(x);const conjunctionNonpolar=/(?:但|且|并且|and|but)\s*(?:non[- ]?polar|非极性)/i.test(x),conjunctionPolar=/(?:且|并且|and)\s*(?:polar|极性)/i.test(x),explicitNonpolar=/non[- ]?polar\s+(?:structures?|subset)|非极性(?:结构|子集)|只(?:看|筛).*非极性/i.test(x)||conjunctionNonpolar,explicitPolar=/\bpolar\s+(?:structures?|subset)|极性(?:结构|子集)|只(?:看|筛).*极性/i.test(x)||conjunctionPolar,sym=noncentrosymmetric||centrosymmetric,nonpolar=sym?explicitNonpolar&&!relation:/non[- ]?polar|非极性/i.test(x),polar=strictPolar||(sym?!nonpolar&&explicitPolar&&!relation:!nonpolar&&(/\bpolar\b|极性/i.test(x)));const years=(q.match(/\b(?:19|20)\d{2}\b/g)||[]).map(Number);const eMin=(q.match(/(?:>|≥|above|over|大于|高于|超过)\s*(\d{3,4})\s*nm/i)||[])[1],eMax=(q.match(/(?:<|≤|below|under|小于|低于)\s*(\d{3,4})\s*nm/i)||[])[1],ev=(q.match(/(?:evidence|证据(?:等级)?)\s*[-:：]?\s*([ABCD])\b/i)||[])[1]?.toUpperCase()||'';let scope='';if(/\bboundary\b|边界/.test(x))scope='Boundary';else if(/outside target scope|范围外/.test(x))scope='Outside Target Scope';else if(/\bexcluded\b|排除/.test(x))scope='Excluded';else if(/\bincluded\b|纳入/.test(x))scope='Included';const keywordMap:[RegExp,string][]=[[/crown ether|冠醚|18-crown-6/i,'crown'],[/scintillat|闪烁/i,'scintillat'],[/thermochrom|热致变色|热变色/i,'thermochrom'],[/mechanochrom|力致变色/i,'mechanochrom'],[/cluster[- ]?center|簇中心/i,'cluster'],[/quantum yield|plqy|量子产率/i,'plqy'],[/lifetime|寿命/i,'lifetime'],[/temperature[- ]?dependent|temperature dependent|温度依赖|变温/i,'temperature'],[/cu\s*[·.]{1,}\s*cu|cuprophilic|铜铜相互作用/i,'cu']];return{x,recordIds:[...q.matchAll(/(?:record\s*|记录\s*)(\d+)/ig)].map(m=>+m[1]),structureIds:[...q.matchAll(/CUH-\d{3}-S\d{2}/ig)].map(m=>m[0].toUpperCase()),count:/how many|\bcount\b|number of|多少|几条|几篇/i.test(x),compare:/compare|versus|\bvs\b|比较|对比/.test(x),articleIntent:/\barticles?\b|\bpapers?\b|文献|论文|文章/.test(x),polar,nonpolar,strictPolar,polarLevelCompare,centrosymmetric,noncentrosymmetric,ferroelectric:!relation&&/ferroelectric|铁电/i.test(x),iodide:/iodide|碘化|铜碘|cu\(i\)-i/i.test(x),bromide:/bromide|溴化|铜溴/i.test(x),chloride:/chloride|氯化|铜氯/i.test(x),d0:/\b0d\b|零维/i.test(x),d1:/\b1d\b|一维/i.test(x),d2:/\b2d\b|二维/i.test(x),d3:/\b3d\b|三维/i.test(x),ste:/self[- ]?trapped|\bste\b|自陷|自俘获/i.test(x),cu2:/cu2i4|cu₂i₄|dicopper|双铜|二铜/i.test(x),years,evidence:ev,scope,emissionMin:eMin?+eMin:0,emissionMax:eMax?+eMax:0,spaceGroup:sgs.find(s=>x.includes(norm(s)))||'',keywords:keywordMap.filter(([r])=>r.test(q)).map(([,k])=>k),relation}}
export function wavelength(v:any,p:Plan){const n=nums(v);if(p.emissionMin&&!n.some(x=>x>=p.emissionMin))return false;if(p.emissionMax&&!n.some(x=>x<=p.emissionMax))return false;return true}
export function kw(row:Row,p:Plan){const t=norm(row['Search Text']||Object.values(row).join(' '));return p.keywords.every(k=>t.includes(k))}
export function articleFilter(a:Row,p:Plan){const y=+a.Year||0;if(p.years.length===1&&y!==p.years[0])return false;if(p.years.length>=2&&(y<Math.min(...p.years)||y>Math.max(...p.years)))return false;if(p.evidence&&String(a['Evidence Level']||'').trim().charAt(0).toUpperCase()!==p.evidence)return false;if(p.scope&&a['Scope Status']!==p.scope)return false;if(p.iodide&&!norm(a['Halogen Type']).includes('i'))return false;if(p.bromide&&!norm(a['Halogen Type']).includes('br'))return false;if(p.chloride&&!norm(a['Halogen Type']).includes('cl'))return false;if(p.d0&&!norm(a['Structural Dimensionality']).includes('0d'))return false;if(p.d1&&!norm(a['Structural Dimensionality']).includes('1d'))return false;if(p.d2&&!norm(a['Structural Dimensionality']).includes('2d'))return false;if(p.d3&&!norm(a['Structural Dimensionality']).includes('3d'))return false;if(!wavelength(a['Emission Wavelength(s) (nm)'],p)||!kw(a,p))return false;return true}
export function structureFilter(s:Row,p:Plan){const y=+s.Year||0;if(p.years.length===1&&y!==p.years[0])return false;if(p.years.length>=2&&(y<Math.min(...p.years)||y>Math.max(...p.years)))return false;if(p.spaceGroup&&s['Space Group (Canonical)']!==p.spaceGroup)return false;if(p.iodide&&s.Halogen!=='I')return false;if(p.bromide&&s.Halogen!=='Br')return false;if(p.chloride&&s.Halogen!=='Cl')return false;if(p.d0&&s['Structural Dimensionality']!=='0D')return false;if(p.d1&&s['Structural Dimensionality']!=='1D')return false;if(p.d2&&s['Structural Dimensionality']!=='2D')return false;if(p.d3&&s['Structural Dimensionality']!=='3D')return false;if((p.polar||p.nonpolar||p.strictPolar||p.centrosymmetric||p.noncentrosymmetric)&&!verified(s))return false;if(p.polar&&s['Polar Space Group?']!=='Yes')return false;if(p.strictPolar&&!(s['Polar Space Group?']==='Yes'&&s['Space-Group Evidence Confidence']==='High'&&s['Mapping Confidence']==='High'))return false;if(p.nonpolar&&s['Polar Space Group?']!=='No')return false;if(p.centrosymmetric&&!centro(s))return false;if(p.noncentrosymmetric&&!noncentro(s))return false;if(p.ste&&!/ste|self-trapped/i.test(norm(Object.values(s).join(' '))))return false;if(p.cu2&&!/(cu2|cu₂|dicopper)/i.test(String(s['Search Text']||Object.values(s).join(' '))))return false;if(!wavelength(s['Emission Wavelength(s) (nm)'],p)||!kw(s,p))return false;return true}
export function tokens(q:string){return[...new Set(norm(q).split(/[^a-z0-9α-ω一-龥+./-]+/).filter(x=>x.length>1))]}
export function score(row:Row,ts:string[],kind:'article'|'structure'){const weights=kind==='article'?['Title','Reported Compound(s) / Formula(s)','Reported Structure','Emission Assignment / Conditions','Space Group(s)','Original Abstract']:['Structure Label / Compound','Reported Formula','Structural Motif / Reported Structure','Space Group (Canonical)','Emission Assignment / Conditions','Article Title'];let s=0;for(let i=0;i<weights.length;i++){const t=norm(row[weights[i]]);for(const x of ts)if(t.includes(x))s+=Math.max(1,7-i)}return s}
export function sources(aa:Row[],ss:Row[]):Source[]{const sr=ss.slice(0,12).map(s=>({type:'structure' as const,id:s['Structure ID'],record_id:s['Record ID'],title:s['Structure Label / Compound'],doi:s.DOI})),ar=aa.slice(0,ss.length?8:20).map(a=>({type:'article' as const,id:a['Record ID'],title:a.Title,doi:a.DOI}));return[...sr,...ar].slice(0,20)}
export function ferroMention(row:Row){return/ferroelectric|铁电/i.test(norm(Object.values(row).join(' ')))}
export function ferroDirect(row:Row){const t=norm(Object.values(row).join(' '));return ferroMention(row)&&/(switchable|switching|polarization reversal|p[-–— ]?e loop|hysteresis|coercive|spontaneous polarization|remanent polarization|可切换|极化翻转|电滞回线|矫顽|自发极化|剩余极化)/i.test(t)}
export function aCite(a:Row){return`[A:${a['Record ID']}]`}export function sCite(s:Row){return`[S:${s['Structure ID']}]`}
export function contextQuery(msgs:any[]){const last=String(msgs.at(-1)?.content||''),follow=/(这个|它|该体系|上述|前者|后者|上一条|上一组|继续|进一步|那么|what about|how about|that|those|former|latter|continue|further)/i.test(last);if(!follow)return{query:last,used:false};const prev=[...msgs.slice(0,-1)].reverse().find((m:any)=>m.role==='user'&&String(m.content||'').trim());return{query:prev?`${prev.content}\nFollow-up: ${last}`:last,used:Boolean(prev)}}
