declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const UP='https://tyxnyjyrfzspwcfjpzus.supabase.co/functions/v1/cuhalide-atlas-smart-rag-v302-current-public';
const RELEASE='3.0.2',VERSION='9.13.0';
const PUBLIC='https://cuhalide-atlas-v3.vercel.app';
const ALLOWED=new Set([PUBLIC,'http://localhost:8765','http://127.0.0.1:8765']);
function cors(req:Request){const o=req.headers.get('origin')||'';return{'access-control-allow-origin':ALLOWED.has(o)?o:PUBLIC,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'accept,content-type,x-cuhalide-client','vary':'Origin'}}
function headers(req:Request,up?:Headers){return{...cors(req),'content-type':up?.get('content-type')||'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow','x-cuhalide-release':up?.get('x-cuhalide-release')||RELEASE,'x-cuhalide-rag-version':up?.get('x-cuhalide-rag-version')||VERSION,'x-cuhalide-current-curated-revision':up?.get('x-cuhalide-current-curated-revision')||'1'}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(!['GET','POST'].includes(req.method))return new Response(JSON.stringify({error:'method not allowed'}),{status:405,headers:headers(req)});try{const raw=req.method==='POST'?await req.text():undefined;if(raw&&raw.length>20000)return new Response(JSON.stringify({error:'request body too large',release:RELEASE,version:VERSION}),{status:413,headers:headers(req)});const h:any={accept:'application/json','content-type':'application/json','user-agent':'CuHalide-Atlas-Canonical-RAG/9.13.0'};const client=String(req.headers.get('x-cuhalide-client')||'').toLowerCase();if(/^[a-f0-9]{64}$/.test(client))h['x-cuhalide-client']=client;const r=await fetch(UP,{method:req.method,headers:h,body:raw,signal:AbortSignal.timeout(req.method==='GET'?35000:120000)}),body=await r.text();return new Response(body,{status:r.status,headers:headers(req,r.headers)})}catch(e){console.error('[canonical-rag-v9130]',e);return new Response(JSON.stringify({ok:false,error:'Smart RAG unavailable',release:RELEASE,version:VERSION}),{status:503,headers:headers(req)})}});
