declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';

const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,REST=`${BASE}/rest/v1`;
const CONVERSATION=`${BASE}/functions/v1/cuhalide-atlas-conversation-v1-internal`;
const RELEASE='3.0.2',PUBLIC_DATA_VERSION='2.10.0',EVIDENCE_VERSION='9.15.0',ASSISTANT_VERSION='10.0.0',META_VERSION='48.4',CURRENT_REVISION=3;
const PUBLIC='https://cuhalide-atlas-v3.vercel.app',DB_TIMEOUT_MS=5000,CONVERSATION_TIMEOUT_MS=3000;
const ALLOWED=new Set([PUBLIC,'http://localhost:8765','http://127.0.0.1:8765','http://127.0.0.1:4173']);
const AUTH={apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json'};

function cors(req:Request){const o=req.headers.get('origin')||'';return{'access-control-allow-origin':ALLOWED.has(o)?o:PUBLIC,'vary':'Origin','access-control-allow-methods':'GET,HEAD,OPTIONS','access-control-allow-headers':'accept,content-type'}}
function headers(req:Request){return{...cors(req),'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow','x-cuhalide-release':RELEASE,'x-cuhalide-public-data-version':PUBLIC_DATA_VERSION,'x-cuhalide-rag-version':EVIDENCE_VERSION,'x-cuhalide-assistant-version':ASSISTANT_VERSION,'x-cuhalide-meta-version':META_VERSION,'x-cuhalide-current-curated-revision':String(CURRENT_REVISION),'x-cuhalide-health-mode':'deterministic-contract'}}
const send=(req:Request,x:any,status=200)=>new Response(req.method==='HEAD'?null:JSON.stringify(x),{status,headers:headers(req)});

async function dbJson(url:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{...AUTH,...(init.headers||{})},cache:'no-store',signal:AbortSignal.timeout(DB_TIMEOUT_MS)}),raw=await r.text();let x:any;try{x=raw?JSON.parse(raw):null}catch{x={error:raw.slice(0,300)}}if(!r.ok)throw new Error(`${new URL(url).pathname} ${r.status}: ${x?.message||x?.error||raw.slice(0,180)}`);return x}
async function rpc(name:string,body:any={}){return dbJson(`${REST}/rpc/${name}`,{method:'POST',body:JSON.stringify(body)})}
async function currentState(){const rows=await dbJson(`${REST}/cuhalide_atlas_current_curated_state?state_key=eq.current&select=*&limit=1`);return rows?.[0]||null}

function frozenMetadata(){return{version:RELEASE,release_date:'2026-08-11',literature_cutoff:'2026-06',cutoff_inclusive_through:'2026-06-30',immutable:true,article_audit_records:346,chemically_included_articles:335,canonical_verified_articles:332,structure_phase_rows:878,core_included_structure_rows:816,resolved_space_group_rows:650,verified_space_group_rows:625,verified_polar_rows:87,strict_polar_rows:67,strict_polar_articles:42,parent_release:'3.0.1',scientific_lineage_root:'3.0.0',public_access_policy:'query-and-view; complete normalized corpus and primary evidence remain private'}}
function temporalScope(cc:any,current:any){return{frozen_release:{version:RELEASE,literature_cutoff:'2026-06',cutoff_inclusive_through:'2026-06-30',immutable:true},current_curated:cc?{base_release:cc.base_release,curated_through:cc.current_curated_through,live_revision:Number(cc.live_revision),status:cc.status,coverage_backfills:Number(current?.batch?.coverage_backfills||19),post_cutoff_additions:Number(current?.batch?.post_cutoff_additions||8)}:null,literature_watch:{metadata_only:true,schedule:'Daily · 02:17 UTC',live_status_endpoint:'/api/public-data?action=status',note:'Discovery status is intentionally outside deterministic core health.'}}}
function exactCurrent(c:any){const x=c?.counts||{};return c?.ok===true&&Number(c?.batch?.live_revision)===3&&String(c?.batch?.curated_through)==='2026-08-14'&&Number(x.article_audit_records)===373&&Number(x.chemically_included_articles)===362&&Number(x.canonical_verified_articles)===359&&Number(x.structure_phase_rows)===949&&Number(x.core_included_structure_rows)===887&&Number(x.resolved_space_group_rows)===719&&Number(x.verified_space_group_rows)===694&&Number(x.verified_polar_rows)===97&&Number(x.strict_polar_rows)===77&&Number(x.strict_polar_articles)===46&&Number(x.rag_documents)===1322&&Number(x.rag_embedded)===1322}
function exactFrozen(f:any){const x=f?.counts||{};return f?.ok===true&&f?.release===RELEASE&&Number(x.articles)===346&&Number(x.canonical_articles)===332&&Number(x.structures)===878&&Number(x.core_included_structures)===816&&Number(x.resolved_space_groups)===650&&Number(x.verified)===625&&Number(x.strict_polar)===67&&f?.checks?.record13_physical_correction===true&&f?.checks?.structure_grain_photophysics_guard===true&&f?.checks?.structure_grain_motif_guard===true}
async function contracts(){const[frozen,current,cc]=await Promise.all([rpc('cuhalide_atlas_public_health_v302',{}),rpc('cuhalide_atlas_current_curated_health_v1',{}),currentState()]);const frozenOk=exactFrozen(frozen),currentOk=exactCurrent(current),stateOk=Boolean(cc)&&cc.base_release===RELEASE&&Number(cc.live_revision)===3&&String(cc.current_curated_through)==='2026-08-14'&&cc.status==='ready';return{ok:frozenOk&&currentOk&&stateOk,frozenOk,currentOk,stateOk,frozen,current,cc}}
async function conversationContract(){try{const r=await fetch(CONVERSATION,{headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','user-agent':'CuHalide-Atlas-Runtime-Contract/1.0.0'},cache:'no-store',signal:AbortSignal.timeout(CONVERSATION_TIMEOUT_MS)}),raw=await r.text();let x:any={};try{x=raw?JSON.parse(raw):{}}catch{}return{ok:r.ok&&x?.ok===true,version:String(x?.version||''),model:String(x?.model||'none'),status:r.status}}catch(e){return{ok:false,version:'',model:'none',status:0,error:String(e)}}}

function publicHealthBody(c:any){return{ok:c.ok,release:RELEASE,version:PUBLIC_DATA_VERSION,current_curated_revision:CURRENT_REVISION,frozen_release:{counts:c.frozen?.counts||{},checks:c.frozen?.checks||{},metadata:frozenMetadata()},current_curated:{...c.current,current_state:c.cc?{base_release:c.cc.base_release,current_curated_through:c.cc.current_curated_through,live_revision:c.cc.live_revision,status:c.cc.status}:null},temporal_scope:temporalScope(c.cc,c.current),public_access:{bulk_export:false,primary_evidence:false,exact_abstracts:false,candidate_abstracts:false,server_side_pagination:true,field_whitelist:true,current_curated_overlay:true,frozen_release_immutable:true,structure_grain_photophysics_guard:true,structure_grain_motif_guard:true},health_mode:'deterministic-db-contract'}}

async function bootstrapBody(req:Request,u:URL){const frozen=String(u.searchParams.get('scope')||'').toLowerCase()==='frozen';const[bootstrap,c]=await Promise.all([rpc(frozen?'cuhalide_atlas_public_bootstrap_v302':'cuhalide_atlas_public_bootstrap_current_v1',{}),contracts()]);if(!c.ok)throw new Error('scientific contracts are not healthy');const cc=c.cc;return{ok:true,release:frozenMetadata(),version:PUBLIC_DATA_VERSION,current_curated_revision:CURRENT_REVISION,current_curated:cc?{base_release:cc.base_release,current_curated_through:cc.current_curated_through,article_audit_records:cc.article_audit_records,chemically_included_articles:cc.chemically_included_articles,canonical_verified_articles:cc.canonical_verified_articles,structure_phase_rows:cc.structure_phase_rows,core_included_structure_rows:cc.core_included_structure_rows,resolved_space_group_rows:cc.resolved_space_group_rows,verified_space_group_rows:cc.verified_space_group_rows,verified_polar_rows:cc.verified_polar_rows,strict_polar_rows:cc.strict_polar_rows,strict_polar_articles:cc.strict_polar_articles,live_revision:cc.live_revision,status:cc.status}:null,temporal_scope:temporalScope(cc,c.current),overview:bootstrap?.overview||{},filters:{article:{halogens:bootstrap?.filters?.article?.halogens||[],dimensions:bootstrap?.filters?.article?.dimensions||[],categories:bootstrap?.filters?.article?.categories||[],evidence:['A','B','C','D'],scope:['Included','Excluded','Boundary','Outside Target Scope'],release_status:['Current canonical','Core - Verified','Current Curated - Verified','Excluded - Curated Audit','Pending - Primary Evidence Unavailable','Context - Boundary','Outside Target Scope']},structure:{halogens:bootstrap?.filters?.structure?.halogens||[],dimensions:bootstrap?.filters?.structure?.dimensions||[],space_groups:bootstrap?.filters?.structure?.space_groups||[],confidence:['High','Medium','Unresolved'],polar:['Yes','No','Unresolved'],eligibility:['Core - Included','Context - Boundary','Pending - Excluded from canonical statistics','Audit Only - Excluded']}},public_access:{bulk_export:false,server_side_pagination:true,field_whitelist:true,current_curated_overlay:!frozen,frozen_scope_available:true,primary_evidence:false,exact_abstracts:false},health_mode:'deterministic-db-contract'}}

async function assistantBody(){const[c,conversation]=await Promise.all([contracts(),conversationContract()]),cc=c.cc,current=c.current||{},evidenceOk=c.ok;return{ok:evidenceOk,release:RELEASE,version:EVIDENCE_VERSION,assistant_version:ASSISTANT_VERSION,service:'CuHalide Research Assistant',operational_mode:conversation.ok?'CONVERSATION_AND_EVIDENCE':(evidenceOk?'EVIDENCE_ONLY':'UNAVAILABLE'),conversation:{ok:conversation.ok,version:conversation.version,model:conversation.model},evidence:{ok:evidenceOk,engine_version:EVIDENCE_VERSION,operational_mode:evidenceOk?'CONTRACT_READY':'UNAVAILABLE'},current_curated:{layer:'current-curated-r3',live_revision:3,curated_through:'2026-08-14',documents:98,embedded:98},corpus:{frozen_documents:1224,current_incremental_documents:98,unified_documents:1322,unified_embedded:1322},temporal_scope:temporalScope(cc,current),capabilities:{natural_conversation:true,automatic_evidence_routing:true,general_scientific_explanation:true,multi_turn_context:true,evidence_grounded_retrieval:true,deterministic_exact_and_protected_boundaries:true,current_curated_retrieval:true,unified_frozen_current_ranking:true,deterministic_temporal_scope:true,deterministic_motif_atlas:true,structure_grain_motif:true,frozen_release_immutable:true,literature_watch_auto_route:true,structure_grain_evidence_guard:true,fractional_motif_conservatism:true,separate_conversation_identity:true,live_web:false},checks:{...(current?.checks||{}),conversation_layer_reachable:conversation.ok,evidence_layer_reachable:evidenceOk,evidence_contract_ready:evidenceOk,current_curated_rag:evidenceOk,current_curated_embeddings:Number(current?.counts?.rag_embedded||0)===1322,unified_document_contract:Number(current?.counts?.rag_documents||0)===1322,unified_embedding_contract:Number(current?.counts?.rag_embedded||0)===1322},public_access:'read-only conversational and query interface',write_access:false,health_mode:'deterministic-db-contract; protected POST QA verifies live evidence routing'}}

async function healthBody(){const[c,conversation]=await Promise.all([contracts(),conversationContract()]),cc=c.cc,current=c.current||{},checks={public_data:c.ok,frozen_release_contract:c.frozenOk,current_curated_contract:c.currentOk&&c.stateOk,smart_rag:c.ok,smart_rag_current_layer:Number(current?.counts?.rag_documents||0)===1322&&Number(current?.counts?.rag_embedded||0)===1322,rag_embeddings_complete:current?.checks?.rag_embeddings_complete===true,site_bundle_contract:true,research_assistant_gateway:c.ok,natural_conversation_contract:true,automatic_evidence_routing:true,conversation_layer_reachable:conversation.ok};return{ok:c.ok,status:c.ok?'PASS':'FAIL',site_readiness:c.ok?'PASS':'OUT_OF_SYNC',release:RELEASE,release_date:'2026-08-11',site_version:'48',meta_version:META_VERSION,public_origin:PUBLIC,gateway_meta_version:'48.5',health_mode:'deterministic-db-contract',site_probe_mode:'bundled-release contract; protected Chromium/Lighthouse independently verify rendered site',temporal_scope:temporalScope(cc,current),frozen_release:{literature_cutoff:'2026-06',cutoff_inclusive_through:'2026-06-30',counts:frozenMetadata()},public_data:{ok:c.ok,version:PUBLIC_DATA_VERSION,access:'query-and-view'},smart_rag:{ok:c.ok,version:EVIDENCE_VERSION,operational_mode:c.ok?'CONTRACT_READY':'UNAVAILABLE',unified_documents:Number(current?.counts?.rag_documents||0)},research_assistant:{ok:c.ok,version:ASSISTANT_VERSION,evidence_engine_version:EVIDENCE_VERSION,operational_mode:conversation.ok?'CONVERSATION_AND_EVIDENCE':(c.ok?'EVIDENCE_ONLY':'UNAVAILABLE'),conversation:{ok:conversation.ok,version:conversation.version,model:conversation.model},evidence:{ok:c.ok,engine_version:EVIDENCE_VERSION,operational_mode:c.ok?'CONTRACT_READY':'UNAVAILABLE'},capabilities:{natural_conversation:true,automatic_evidence_routing:true,general_scientific_explanation:true,multi_turn_context:true,evidence_grounded_retrieval:true,deterministic_exact_and_protected_boundaries:true,current_curated_retrieval:true,literature_watch_auto_route:true,structure_grain_evidence_guard:true,fractional_motif_conservatism:true,separate_conversation_identity:true,live_web:false}},current_curated:{base_release:cc?.base_release||RELEASE,current_curated_through:cc?.current_curated_through||'2026-08-14',live_revision:Number(cc?.live_revision||3),status:cc?.status||'unavailable',counts:current?.counts||{},batch:current?.batch||{}},motif_atlas:{ok:c.ok,version:'1.2',taxonomy_rows:949,resolved:816,unresolved:133},historical_corrections_count:4,current_errata_count:0,checks,write_access:false}}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(!['GET','HEAD'].includes(req.method))return send(req,{error:'read-only endpoint'},405);try{const u=new URL(req.url),action=String(u.searchParams.get('action')||'health').toLowerCase();if(action==='public-health'){const c=await contracts(),body=publicHealthBody(c);return send(req,body,c.ok?200:503)}if(action==='bootstrap')return send(req,await bootstrapBody(req,u),200);if(action==='assistant'){const body=await assistantBody();return send(req,body,body.ok?200:503)}if(action==='health'){const body=await healthBody();return send(req,body,body.ok?200:503)}return send(req,{error:'unknown runtime contract action'},404)}catch(e){console.error('[runtime-contract-v1]',e);return send(req,{ok:false,status:'FAIL',error:'CuHalide Atlas deterministic runtime contract is temporarily unavailable.',release:RELEASE,public_data_version:PUBLIC_DATA_VERSION,evidence_version:EVIDENCE_VERSION,assistant_version:ASSISTANT_VERSION},503)}});
