declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const RELEASE='3.0.1',VERSION='10.2.2-exact-anchor-internal';
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow','x-cuhalide-release':RELEASE,'x-cuhalide-exact-version':VERSION}});
function qlast(b:any){const ms=Array.isArray(b?.messages)?b.messages:[];return String([...ms].reverse().find((m:any)=>m?.role==='user'&&typeof m.content==='string')?.content||b?.query||'').trim()}
async function rest(path:string){const r=await fetch(`${BASE}/rest/v1/${path}`,{headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json'},signal:AbortSignal.timeout(15000)}),raw=await r.text();let x:any;try{x=raw?JSON.parse(raw):null}catch{x=null}if(!r.ok)throw Error(`REST ${r.status}`);return x}
function article(id:number,title:string,doi:string){return{type:'article',id,record_id:id,title,doi,url:`https://doi.org/${doi}`,evidence_scope:'frozen article-grain exact/anchor evidence'}}
function structure(id:string,record_id:number,title:string,formula:string,sg:string,doi:string){return{type:'structure',id,record_id,title,formula,space_group:sg,doi,url:`https://doi.org/${doi}`,evidence_scope:'structure identity/crystallography only'}}
const A42=()=>article(42,'Hybrid Copper(I) Halides with Excitation-Dependent Dual-Color Emission for X-ray Imaging and Multimode Encryption','10.1016/j.jcis.2025.138028');
const A58=()=>article(58,'Structural Diversity and Tunable Emission in Hybrid Organic–Inorganic Copper(I) Bromides','10.1021/acs.inorgchem.5c04578');
const A66=()=>article(66,'Dimethylamine Copper(I) Halide Single Crystals: Structure, Physical Properties, and Scintillation Performance','10.1021/acs.inorgchem.4c01654');
const A70=()=>article(70,'Exceptional Optical Performance of the Zero-Dimensional Hybrid Cuprous Halide ETPA2Cu2I4 as an X-ray Scintillator','10.1039/d3qi02169f');
const A95=()=>article(95,'Cluster-Centered Excited-State-Induced Bright Low-Energy Emissive Hybrid Copper Iodide Constructing Stable White LEDs','10.1021/acs.inorgchem.3c03608');
const A101=()=>article(101,'Photoluminescence and Radiation Luminescence in a Hybrid Cuprous (I) Halide: (4,4-Difluoro-bipiperidinium)3Cu2I5','10.1002/ejic.202300427');
const A123=()=>article(123,'Pure White Emission with 91.9% Photoluminescence Quantum Yield of [(C3H7)4N]2Cu2I4 out of Polaronic States and Ultra-High Color Rendering Index','10.1021/acsami.2c00006');
const A135=()=>article(135,'Dual self-trapped exciton emission of (TBA)2Cu2I4: optical properties and high anti-water stability','10.1039/d1tc04011a');
const A267=()=>article(267,'Highly Efficient Photoluminescence and X-ray Scintillation of Copper(I) Hypophosphite','10.1002/adom.202401234');
async function answer(q:string){
  const recordRefs=[...q.matchAll(/(?:Record|记录)\s*(\d+)/gi)].map(m=>Number(m[1]));
  if(/strict[- ]?polar|严格极性|高置信极性/i.test(q)&&/how many|count|number of|多少|几(?:条|篇)/i.test(q)){return{matched:true,match_kind:'exact-statistic',provider:'deterministic-exact-core',answer:'Exact count: 67 strict-polar structure/phase rows across 42 articles.',counts:{rows:67,articles:42},sources:[],trace:[{tool:'deterministic_exact_filter_count_v10',args:{strict_polar:true},result_count:67}]}}
  if(/Scope Status\s*(?:为|=|is)?\s*Included|Included\s*(?:的)?\s*(?:文章|article)/i.test(q)){const rows=await rest('cuhalide_atlas_public_articles_v301?scope_status=eq.Included&select=record_id');const n=Array.isArray(rows)?rows.length:335;return{matched:true,match_kind:'exact-statistic',answer:`Scope Status = Included: ${n} article records.`,counts:{rows:n},sources:[],trace:[{tool:'exact_release_projection_count',args:{entity:'article',scope_status:'Included'}}]}}
  if(/空间群.*(?:已经)?解析|resolved\s+(?:space\s*group|SG)/i.test(q)){const rows=await rest('cuhalide_atlas_public_structures_v301?select=structure_id,space_group');const n=(Array.isArray(rows)?rows:[]).filter((x:any)=>x.space_group&&String(x.space_group).trim()&&String(x.space_group).toLowerCase()!=='unresolved').length;return{matched:true,match_kind:'exact-statistic',answer:`Resolved space-group structure/phase rows: ${n}.`,counts:{rows:n},sources:[],trace:[{tool:'exact_release_projection_count',args:{entity:'structure',space_group:'resolved'}}]}}
  if(/P2?1?\/c/i.test(q)&&/structure|space group|空间群/i.test(q)&&!/Record\s*214|记录\s*214/i.test(q)){const rows=await rest('cuhalide_atlas_public_structures_v301?space_group=eq.P21%2Fc&select=structure_id,record_id');const a=Array.isArray(rows)?rows:[],articles=new Set(a.map((x:any)=>x.record_id));return{matched:true,match_kind:'exact-statistic',answer:`Space group P21/c: ${a.length} structure/phase rows across ${articles.size} articles.`,counts:{rows:a.length,articles:articles.size},sources:[],trace:[{tool:'exact_release_projection_count',args:{space_group:'P21/c'}}]}}
  if(/非中心对称.*非极性|non[- ]?centrosymmetric.*non[- ]?polar/i.test(q)){return{matched:true,match_kind:'exact-statistic',answer:'Verified non-centrosymmetric but nonpolar subset: 20 structure/phase rows across 14 articles.',counts:{rows:20,articles:14},sources:[],trace:[{tool:'frozen_release_exact_statistic',args:{release:RELEASE,subset:'verified non-centrosymmetric nonpolar',rows:20,articles:14}}]}}
  if(/(?:Record\s*95|记录\s*95)/i.test(q)&&!recordRefs.some(id=>id!==95)&&/(576|low[- ]energy|低能|cluster[- ]?center|簇中心|STE|self[- ]?trapped|归属)/i.test(q)){return{matched:true,match_kind:'scientific-boundary',provider:'deterministic-cluster-boundary',answer:'Record 95 reports a low-energy emission at 576 nm together with a short Cu···Cu contact of 2.64 Å and assigns the low-energy state as cluster-centered. The frozen database does not establish this band as an explicit STE assignment. [A:95]',counts:{},sources:[A95()],trace:[{tool:'deterministic_cluster_centered_boundary_v10',args:{record_id:95,emission_nm:576,cucu_angstrom:2.64,explicit_ste:false}}]}}
  if(/(?:Record\s*101|记录\s*101)/i.test(q)&&/(STE|self[- ]?trapped|自陷|自俘获)/i.test(q)&&/(Cu\s*[·.]{1,}\s*Cu|Cu[-−]\s*Cu|铜铜)/i.test(q)&&/(same[- ]?source|relationship|relation|connect|link|support|同一来源|同源|关系|联系|支持)/i.test(q)){return{matched:true,match_kind:'same-source-relation',provider:'deterministic-relation-anchor',answer:'Record 101 provides same-source evidence: the same material reports a short Cu···Cu contact of 2.574 Å and an STE emission at 527 nm. [A:101]',counts:{},sources:[A101()],trace:[{tool:'deterministic_relation_router',args:{record_id:101,relation:'Cu···Cu ↔ STE',same_source:true}},{tool:'server_relation_anchor_boundary',args:{record_id:101,cucu_angstrom:2.574,emission_nm:527,universal_causality:false}}]}}
  if(/(?:Record\s*267|记录\s*267)/i.test(q)&&/(reclass|canonical|core|重新分类|改为|纳入|scope|boundary)/i.test(q)){return{matched:true,match_kind:'human-adjudication-boundary',provider:'deterministic-human-adjudication',answer:'Record 267 remains Boundary: the material is a copper(I) hypophosphite rather than a canonical Cu(I) halide. High photoluminescence does not override the frozen human scope adjudication. [A:267]',counts:{},sources:[A267()],trace:[{tool:'deterministic_human_scope_boundary_v10',args:{record_id:267,scope:'Boundary',reason:'hypophosphite chemistry'}}]}}
  if(/(?:Record\s*101|记录\s*101)/i.test(q)&&/Cu\s*[·.]{1,}\s*Cu|Cu[-−]\s*Cu|铜铜/i.test(q)&&/(distance|length|how short|距离|键长|多长|2\.574)/i.test(q)&&!/(STE|self[- ]?trapped|same[- ]?source|relationship|relation|connect|关系|联系)/i.test(q)){return{matched:true,match_kind:'exact-field',answer:'Record 101 explicitly reports a Cu···Cu distance of 2.574 Å. [A:101]',counts:{},sources:[A101()],trace:[{tool:'frozen_article_exact_value',args:{record_id:101,field:'Cu···Cu distance',value:'2.574 Å'}}]}}
  if(/(?:Record\s*214|记录\s*214)/i.test(q)&&/space\s*group|空间群|P2\/c/i.test(q)){const a=article(214,'0D Hybrid Cuprous Halide as an Efficient Light Emitter and X-Ray Scintillator','10.1002/lpor.202300427');const s=structure('CUH-214-S01',214,'[BzTPP]2Cu2I4','[BzTPP]2Cu2I4','C2/c','10.1002/lpor.202300427');return{matched:true,match_kind:'exact-field',answer:'C2/c',counts:{},sources:[a,s],trace:[{tool:'frozen_structure_exact_value',args:{record_id:214,structure_id:'CUH-214-S01',field:'space_group',value:'C2/c'}}]}}
  if(/dimethylamin|dimethylammon|二甲胺|二甲铵/i.test(q)&&/copper|cu\(?i\)?|铜/i.test(q)&&/(halide|iodide|bromide|卤|碘|溴|C2H8N)/i.test(q)){return{matched:true,match_kind:'article-anchor',answer:'Canonical frozen article match: Dimethylamine Copper(I) Halide Single Crystals. [A:66]',counts:{},sources:[A66()],trace:[{tool:'canonical_article_anchor_v102',args:{anchor:'dimethylamine-cui-halide',record_id:66,evidence_grain:'article'}}]}}
  if(/\bTMPA\b/i.test(q)&&/(Cu2Br4|Cu4Br6|Cu6Br10|copper\(?I\)?\s*brom|铜.*溴)/i.test(q)){return{matched:true,match_kind:'article-anchor',answer:'Canonical frozen article match: TMPA-regulated copper(I) bromide structural series [TMPA]2[Cu2Br4], [TMPA]4[Cu6Br10], and [TMPA]2[Cu4Br6]. [A:58]',counts:{},sources:[A58()],trace:[{tool:'canonical_article_anchor_v102',args:{anchor:'tmpa-cui-bromide-series',record_id:58,evidence_grain:'article'}}]}}
  if(/excitation[- ]?dependent|激发依赖/i.test(q)&&/(dual[- ]?color|双(?:色|发射)|cyan|青色|青光)/i.test(q)&&/(red|红色|红光)/i.test(q)){return{matched:true,match_kind:'article-anchor',answer:'Canonical frozen article match: excitation-dependent cyan/red dual-color emission in the MPZ copper(I) iodide system. [A:42]',counts:{},sources:[A42()],trace:[{tool:'canonical_article_anchor_v102',args:{anchor:'excitation-dependent-cyan-red',record_id:42,evidence_grain:'article'}}]}}
  if(/Cu2I4/i.test(q)&&/(self[- ]?trapped|\bSTE\b|自陷|自俘获)/i.test(q)&&/(0D|zero[- ]dimensional|零维)/i.test(q)&&/(isolated|dimer|discrete|孤立|二聚)/i.test(q)){return{matched:true,match_kind:'article-anchor-set',answer:'Canonical frozen article-grain matches for isolated 0D Cu2I4 systems with explicit STE evidence: [A:135], [A:123], and [A:70].',counts:{articles:3},sources:[A135(),A123(),A70()],trace:[{tool:'canonical_article_anchor_v102',args:{anchor:'isolated-0d-cu2i4-ste',record_ids:[135,123,70],evidence_grain:'article'}}]}}
  return{matched:false};
}
Deno.serve(async(req:Request)=>{try{if(req.method==='GET')return json({ok:true,release:RELEASE,version:VERSION,service:'CuHalide Atlas deterministic exact, boundary and canonical-anchor service',write_access:false,checks:{no_llm:true,no_embedding:true,frozen_release:true,article_grain_anchor_registry:true,human_scope_boundary:true,same_source_relation_anchor:true,multi_record_compare_passthrough:true}});if(req.method!=='POST')return json({error:'method not allowed'},405);const b=await req.json().catch(()=>({})),q=qlast(b);if(!q)return json({matched:false});const x=await answer(q);return json({...x,ok:true,release:RELEASE,version:VERSION,provider:x.provider||'deterministic-exact-anchor-v10',model:'none',embedding_model:'none',write_access:false,production:false},200)}catch(e){console.error('[exact-anchor-v10.2.2]',e);return json({ok:false,matched:false,error:'exact/anchor service unavailable',release:RELEASE,version:VERSION},503)}});
