declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const RELEASE='3.0.2',VERSION='2.8.0',REST=`${BASE}/rest/v1`;
const CANDIDATES=`${BASE}/functions/v1/cuhalide-atlas-candidates-v2`;
const FROZEN_ARTICLES='cuhalide_atlas_public_articles_v302',FROZEN_STRUCTURES='cuhalide_atlas_public_structures_v302',CURRENT_ARTICLES='cuhalide_atlas_public_articles_current_v1',CURRENT_STRUCTURES='cuhalide_atlas_public_structures_current_v1';
const MOTIF_BOUNDARY='No independently mapped structure-grain motif is exposed in the public interface; consult the article-level structural summary and primary evidence for motif interpretation.';
const headers=()=>({'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow, noarchive','x-cuhalide-release':RELEASE,'x-cuhalide-public-data-version':VERSION,'x-cuhalide-public-access':'internal-upstream','x-cuhalide-endpoint-state':'internal-upstream'});
const send=(req:Request,x:any,s=200)=>new Response(req.method==='HEAD'?null:JSON.stringify(x),{status:s,headers:headers()});
const txt=(v:any)=>String(v??'').trim();
function internal(req:Request){return req.headers.get('authorization')===`Bearer ${KEY}`&&req.headers.get('apikey')===KEY}
async function fetchJson(url:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json',...(init.headers||{})},cache:'no-store',signal:AbortSignal.timeout(30000)}),raw=await r.text();let x:any;try{x=raw?JSON.parse(raw):null}catch{x={error:raw.slice(0,300)}};if(!r.ok)throw new Error(`${new URL(url).pathname} ${r.status}: ${x?.message||x?.error||raw.slice(0,160)}`);return x}
async function rpc(name:string,body:any={}){return fetchJson(`${REST}/rpc/${name}`,{method:'POST',body:JSON.stringify(body)})}
async function table(path:string){return fetchJson(`${REST}/${path}`)}
function frozenRelease(){return{version:RELEASE,release_date:'2026-08-11',literature_cutoff:'2026-06',cutoff_inclusive_through:'2026-06-30',immutable:true,article_audit_records:346,chemically_included_articles:335,canonical_verified_articles:332,structure_phase_rows:878,core_included_structure_rows:816,resolved_space_group_rows:650,verified_space_group_rows:625,verified_polar_rows:87,strict_polar_rows:67,strict_polar_articles:42,parent_release:'3.0.1',scientific_lineage_root:'3.0.0',public_access_policy:'query-and-view; complete normalized corpus and primary evidence remain private'}}
async function currentState(){const rows=await table('cuhalide_atlas_current_curated_state?state_key=eq.current&select=*&limit=1');return rows?.[0]||null}
async function temporalScope(){const[cc,watch]=await Promise.all([currentState(),fetchJson(`${CANDIDATES}?action=status`)]);return{frozen_release:{version:RELEASE,literature_cutoff:'2026-06',cutoff_inclusive_through:'2026-06-30',immutable:true},current_curated:cc?{base_release:cc.base_release,curated_through:cc.current_curated_through,live_revision:cc.live_revision,status:cc.status,coverage_backfills:Number(cc.live_revision)>=1?14:0,post_cutoff_additions:Number(cc.live_revision)>=1?2:0}:null,literature_watch:{metadata_only:true,last_sync:watch?.last_sync?{completed_at:watch.last_sync.completed_at,status:watch.last_sync.status}:null,schedule:'Daily · 02:17 UTC'}}}
function useFrozen(u:URL){return String(u.searchParams.get('scope')||'').toLowerCase()==='frozen'}
function qArticle(u:URL,pageSize?:number){let rs=u.searchParams.get('release_status')||null;if(useFrozen(u)&&rs==='Current canonical')rs='Core - Verified';return rpc(useFrozen(u)?'cuhalide_atlas_public_articles_query_v302':'cuhalide_atlas_public_articles_query_current_v1',{p_q:txt(u.searchParams.get('q')),p_page:Number(u.searchParams.get('page')||1),p_page_size:pageSize||Number(u.searchParams.get('page_size')||18),p_year_from:u.searchParams.get('year_from')?Number(u.searchParams.get('year_from')):null,p_year_to:u.searchParams.get('year_to')?Number(u.searchParams.get('year_to')):null,p_halogen:u.searchParams.get('halogen')||null,p_dimension:u.searchParams.get('dimension')||null,p_category:u.searchParams.get('category')||null,p_evidence:u.searchParams.get('evidence')||null,p_scope:u.searchParams.get('scope_status')||null,p_release_status:rs,p_sort:u.searchParams.get('sort')||'year_desc'})}
function qStructure(u:URL,strict=false,pageSize?:number,recordId?:number|null){return rpc(useFrozen(u)?'cuhalide_atlas_public_structures_query_v302':'cuhalide_atlas_public_structures_query_current_v1',{p_q:txt(u.searchParams.get('q')),p_page:Number(u.searchParams.get('page')||1),p_page_size:pageSize||Number(u.searchParams.get('page_size')||30),p_halogen:u.searchParams.get('halogen')||null,p_dimension:u.searchParams.get('dimension')||null,p_space_group:u.searchParams.get('space_group')||null,p_confidence:u.searchParams.get('confidence')||null,p_polar:u.searchParams.get('polar')||null,p_inclusion:u.searchParams.get('inclusion')||null,p_eligibility:u.searchParams.get('eligibility')||null,p_record_id:recordId??null,p_strict_polar:strict})}
const articleList=(a:any)=>({record_id:a.record_id,title:a.title||'',authors:a.authors||'',journal:a.journal||'',year:a.year||'',doi:a.doi||'',doi_url:a.doi_url||'',halogen:a.halogen||'',dimensionality_class:a.dimension_class||'',category:a.category||'',evidence_level:a.evidence_level||'',scope_status:a.scope_status||'',release_status:a.release_status||'',structure_summary:a.structure_summary||'',curation_layer:a.curation_layer||'Frozen Release',coverage_class:a.coverage_class||'frozen_release',live_revision:Number(a.live_revision||0)});
const articleDetail=(a:any)=>({...articleList(a),compounds:a.compounds||'',space_groups:a.space_groups||'',emission_nm:a.emission_nm||'',emission_assignment:a.emission_assignment||'',article_type:a.article_type||'',volume:a.volume||'',issue:a.issue||'',pages:a.pages||'',ccdc_cif:a.ccdc_cif||'',last_verified:a.last_verified||''});
const structureList=(s:any,polar=false)=>{const b:any={structure_id:s.structure_id,record_id:s.record_id,label:s.label||'',formula:s.formula||'',phase:s.phase||'',halogen:s.halogen_effective||'Unresolved',halogen_scope:s.halogen_scope||'unresolved',halogen_confidence:s.halogen_confidence||'Unresolved',halogen_basis:s.halogen_basis||'unresolved',dimensionality:s.dimensionality||'',dimensionality_class:s.dimension_class||'',space_group:s.space_group||'',polar:s.polar||'',sg_confidence:s.sg_confidence||'',mapping_confidence:s.mapping_confidence||'',inclusion_status:s.inclusion_status||'',eligibility:s.eligibility||'',doi:s.doi||'',doi_url:s.doi_url||'',known_erratum:Boolean(s.known_erratum),erratum_key:s.erratum_key||'',curation_layer:s.curation_layer||'Frozen Release',coverage_class:s.coverage_class||'frozen_release',live_revision:Number(s.live_revision||0),chemical_identity_status:s.chemical_identity_status||'frozen_release_identity'};if(polar){b.point_group=s.point_group||'';b.crystal_system=s.crystal_system||'';}return b};
const structureDetail=(s:any)=>{const b:any=structureList(s,true);b.article_title=s.article_title||'';b.category=s.category||'';b.halogen_note=s.halogen_note||'';b.motif=MOTIF_BOUNDARY;b.determination_method=s.determination_method||'';b.emission_nm='';b.emission_assignment=`Photophysical values are curated at article grain for Record ${s.record_id}. They are not independently assigned to this structure/phase row unless a structure-grain evidence object establishes that mapping.`;b.space_group_source_form=s.space_group_source_form||'';b.it_number=s.it_number||'';b.polar_basis=s.polar_basis||'';b.ccdc_cif=s.ccdc_cif||'';b.evidence_level=s.evidence_level||'';b.crystallographic_evidence_type=s.crystallographic_evidence_type||'';b.last_verified=s.last_verified||'';b.cell={a:s.cell_a||'',b:s.cell_b||'',c:s.cell_c||'',alpha:s.cell_alpha||'',beta:s.cell_beta||'',gamma:s.cell_gamma||'',volume:s.cell_volume||'',z:s.z_value||''};b.erratum_note=s.erratum_note||'';return b};
async function currentHealth(){return rpc('cuhalide_atlas_current_curated_health_v1',{})}
async function frozenHealth(){return rpc('cuhalide_atlas_public_health_v302',{})}
Deno.serve(async(req:Request)=>{if(!internal(req))return send(req,{ok:false,error:'internal upstream requires service authorization'},401);if(!['GET','HEAD'].includes(req.method))return send(req,{error:'read-only endpoint'},405);try{const u=new URL(req.url),action=txt(u.searchParams.get('action')||'health').toLowerCase();if(['verified','export','download','raw','payload'].includes(action))return send(req,{error:'Bulk release export is not part of the public web interface. Use website search, record pages and citation metadata.'},403);
if(action==='health'){const[frozen,current,cc,temporal]=await Promise.all([frozenHealth(),currentHealth(),currentState(),temporalScope()]);const ok=frozen?.ok===true&&current?.ok===true&&Boolean(cc)&&['ready','updating','validated_base_pending_publish','frozen_for_release'].includes(cc.status);return send(req,{ok,release:RELEASE,version:VERSION,frozen_release:{counts:frozen?.counts||{},checks:frozen?.checks||{},metadata:frozenRelease()},current_curated:{...current,current_state:cc?{base_release:cc.base_release,current_curated_through:cc.current_curated_through,live_revision:cc.live_revision,status:cc.status}:null},temporal_scope:temporal,public_access:{bulk_export:false,primary_evidence:false,exact_abstracts:false,candidate_abstracts:false,server_side_pagination:true,field_whitelist:true,current_curated_overlay:true,frozen_release_immutable:true,structure_grain_photophysics_guard:true,structure_grain_motif_guard:true}},ok?200:503)}
if(action==='bootstrap'){const[b,cc,temporal]=await Promise.all([rpc(useFrozen(u)?'cuhalide_atlas_public_bootstrap_v302':'cuhalide_atlas_public_bootstrap_current_v1',{}),currentState(),temporalScope()]);return send(req,{ok:true,release:frozenRelease(),current_curated:cc?{base_release:cc.base_release,current_curated_through:cc.current_curated_through,article_audit_records:cc.article_audit_records,chemically_included_articles:cc.chemically_included_articles,canonical_verified_articles:cc.canonical_verified_articles,structure_phase_rows:cc.structure_phase_rows,core_included_structure_rows:cc.core_included_structure_rows,resolved_space_group_rows:cc.resolved_space_group_rows,verified_space_group_rows:cc.verified_space_group_rows,verified_polar_rows:cc.verified_polar_rows,strict_polar_rows:cc.strict_polar_rows,strict_polar_articles:cc.strict_polar_articles,live_revision:cc.live_revision,status:cc.status}:null,temporal_scope:temporal,overview:b.overview||{},filters:{article:{halogens:b.filters?.article?.halogens||[],dimensions:b.filters?.article?.dimensions||[],categories:b.filters?.article?.categories||[],evidence:['A','B','C','D'],scope:['Included','Excluded','Boundary','Outside Target Scope'],release_status:['Current canonical','Core - Verified','Current Curated - Verified','Excluded - Curated Audit','Pending - Primary Evidence Unavailable','Context - Boundary','Outside Target Scope']},structure:{halogens:b.filters?.structure?.halogens||[],dimensions:b.filters?.structure?.dimensions||[],space_groups:b.filters?.structure?.space_groups||[],confidence:['High','Medium','Unresolved'],polar:['Yes','No','Unresolved'],eligibility:['Core - Included','Context - Boundary','Pending - Excluded from canonical statistics','Audit Only - Excluded']}},public_access:{bulk_export:false,server_side_pagination:true,field_whitelist:true,current_curated_overlay:!useFrozen(u),frozen_scope_available:true,primary_evidence:false,exact_abstracts:false}})}
if(action==='articles'){const x=await qArticle(u);return send(req,{...x,items:(x.items||[]).map(articleList),release:RELEASE,data_scope:useFrozen(u)?'frozen_release':'current_curated',fields:'public-list-minimal-v11'})}
if(action==='structures'||action==='polar'){const x=await qStructure(u,action==='polar');return send(req,{...x,items:(x.items||[]).map((s:any)=>structureList(s,action==='polar')),release:RELEASE,data_scope:useFrozen(u)?'frozen_release':'current_curated',fields:action==='polar'?'public-polar-list-v11':'public-list-minimal-v11'})}
if(action==='article'){const id=txt(u.searchParams.get('id'));if(!/^\d+$/.test(id))return send(req,{error:'valid article id required'},400);const tableName=useFrozen(u)?FROZEN_ARTICLES:CURRENT_ARTICLES;const rows=await table(`${tableName}?record_id=eq.${encodeURIComponent(id)}&select=*`),a=rows?.[0];return a?send(req,{item:articleDetail(a),release:RELEASE,data_scope:a.curation_layer==='Current Curated'?'current_curated':'frozen_release',fields:'public-record-detail-v11',public_access:'query-and-view'}):send(req,{error:'article not found'},404)}
if(action==='structure'){const id=txt(u.searchParams.get('id'));if(!/^CUH-[A-Za-z0-9_-]+$/i.test(id))return send(req,{error:'valid structure id required'},400);const tableName=useFrozen(u)?FROZEN_STRUCTURES:CURRENT_STRUCTURES;const rows=await table(`${tableName}?structure_id=eq.${encodeURIComponent(id)}&select=*`),s=rows?.[0];return s?send(req,{item:structureDetail(s),release:RELEASE,data_scope:s.curation_layer==='Current Curated'?'current_curated':'frozen_release',fields:'public-record-detail-v11',public_access:'query-and-view'}):send(req,{error:'structure not found'},404)}
if(action==='article-structures'){const id=txt(u.searchParams.get('id'));if(!/^\d+$/.test(id))return send(req,{error:'valid article id required'},400);const su=new URL('https://local/');const x=await qStructure(su,false,50,Number(id));let items=(x.items||[]).map((s:any)=>structureList(s,false));if(!useFrozen(u)){const links=await table(`cuhalide_atlas_current_curated_links?record_id=eq.${encodeURIComponent(id)}&select=structure_id,relation_type,note`);if(links?.length){const ids=links.map((z:any)=>z.structure_id).join(',');const frozen=await table(`${FROZEN_STRUCTURES}?structure_id=in.(${ids})&select=*`);const lm=new Map(links.map((z:any)=>[z.structure_id,z]));items.push(...(frozen||[]).map((s:any)=>({...structureList(s,false),article_relation:lm.get(s.structure_id)?.relation_type||'known_identity_reference',article_relation_note:lm.get(s.structure_id)?.note||''})))}}return send(req,{items,count:items.length,release:RELEASE,fields:'public-related-structure-list-v11'})}
if(action==='search'){const q=txt(u.searchParams.get('q'));if(!q)return send(req,{articles:[],structures:[],q,release:RELEASE});const au=new URL('https://local/'),su=new URL('https://local/');au.searchParams.set('q',q);su.searchParams.set('q',q);if(useFrozen(u)){au.searchParams.set('scope','frozen');su.searchParams.set('scope','frozen')}const[a,s]=await Promise.all([qArticle(au,8),qStructure(su,false,12)]);return send(req,{articles:(a.items||[]).map(articleList),structures:(s.items||[]).map((z:any)=>structureList(z,false)),q,release:RELEASE,data_scope:useFrozen(u)?'frozen_release':'current_curated',fields:'public-search-minimal-v11'})}
if(action==='current-curated'){const[cc,h,temporal]=await Promise.all([currentState(),currentHealth(),temporalScope()]);return send(req,{ok:Boolean(cc)&&h?.ok===true,release:RELEASE,current_curated:cc?{...cc,note:undefined}:null,current_health:h,temporal_scope:temporal,public_note:'Current Curated is a primary-evidence-reviewed rolling overlay on frozen release 3.0.2; it does not rewrite the frozen snapshot.'},cc?200:503)}
if(action==='candidates'){const limit=Math.max(1,Math.min(12,Number(u.searchParams.get('limit')||9)||9)),x=await fetchJson(`${CANDIDATES}?action=candidates&limit=${limit}`),items=(x.items||[]).slice(0,limit).map((c:any)=>({candidate_id:c.candidate_id,doi:c.doi||'',title:c.title||'',year:c.year||'',journal:c.journal||'',source_url:c.source_url||'',status:c.review_status==='screened_boundary'?'Under targeted review':'Under primary-source review'}));return send(req,{items,count:items.length,release:RELEASE,public_note:'Recent literature candidates are metadata-only and remain outside Current Curated until primary-evidence review and QC.'})}
if(action==='status'){const[x,cc,temporal]=await Promise.all([fetchJson(`${CANDIDATES}?action=status`),currentState(),temporalScope()]),c=x.candidate_counts||{};return send(req,{ok:true,release:{version:RELEASE,date:'2026-08-11',literature_cutoff:'2026-06'},current_curated:cc?{base_release:cc.base_release,current_curated_through:cc.current_curated_through,live_revision:cc.live_revision,status:cc.status}:null,literature_watch:{status:'operational',evidence_acquisition_queue:Number(c.screened_in_scope||0)+Number(c.screened_boundary||0)+Number(c.pending||0),pending_metadata_screen:Number(c.pending||0),last_sync:x.last_sync?{completed_at:x.last_sync.completed_at,status:x.last_sync.status}:null,schedule:'Daily · 02:17 UTC'},temporal_scope:temporal,public_note:'Frozen cutoff, Current Curated coverage, and Literature Watch discovery are distinct time layers.',write_access:false})}
if(action==='errata'){const rows=await table('cuhalide_atlas_release_errata?release_version=eq.3.0.1&planned_correction_release=eq.3.0.2&select=erratum_key,record_id,structure_id,field_name,published_value,corrected_value,status,severity,affects_release_counts,affects_canonical_denominator,planned_correction_release&order=structure_id.asc');const items=(rows||[]).map((x:any)=>({...x,resolved_in_release:'3.0.2'}));return send(req,{ok:true,count:items.length,items,release:RELEASE,history_release:'3.0.1',public_note:'Historical 3.0.1 errata physically incorporated into frozen release 3.0.2.'})}
return send(req,{error:'unknown public action'},404)}catch(e){console.error('[public-data-v302-internal]',e);return send(req,{ok:false,error:'CuHalide Atlas public data service unavailable',release:RELEASE,version:VERSION},503)}});