import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const UP=`${BASE}/functions/v1/cuhalide-atlas-current-rag-r9-science-exact-internal`,CURRENT='current-curated-r10',VERSION='current-rag-r10-science-exact-1.0.1';
const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow, noarchive','x-cuhalide-release':'3.0.2','x-cuhalide-current-curated-revision':'10','x-cuhalide-photophysics-contract':'1.4.0','x-cuhalide-organic-components-contract':'1.2.0','x-cuhalide-endpoint-state':'internal-service-only'};
const ID_RE=/CUH-\d{3}-S\d{2}/gi;
function internal(req:Request){return req.headers.get('authorization')===`Bearer ${KEY}`&&req.headers.get('apikey')===KEY}
function patch(x:any):any{if(Array.isArray(x))return x.map(patch);if(!x||typeof x!=='object')return x;const o:any={};for(const[k,v]of Object.entries(x)){if(k==='live_revision'||k==='current_curated_revision')o[k]=10;else if(k==='current_release')o[k]=CURRENT;else if(typeof v==='string')o[k]=v.replace(/Current Curated rev\.9/g,'Current Curated rev.10').replace(/current-curated-r9/g,CURRENT).replace(/current-rag-r9/g,'current-rag-r10');else o[k]=patch(v)}return o}
function messages(b:any){return Array.isArray(b?.messages)?b.messages.filter((m:any)=>m&&typeof m.content==='string'&&['user','assistant'].includes(String(m.role))):[]}
function lastUserIndex(ms:any[]){for(let i=ms.length-1;i>=0;i--)if(ms[i]?.role==='user')return i;return -1}
function idsFrom(q:string){const out:string[]=[];for(const m of q.matchAll(ID_RE)){const id=String(m[0]).toUpperCase();if(!out.includes(id))out.push(id)}return out}
function targetBody(raw:string,id:string){let b:any;try{b=JSON.parse(raw)}catch{return raw}const ms=messages(b).map((m:any)=>({...m})),i=lastUserIndex(ms);if(i<0)return raw;let q=String(ms[i].content||'');q=q.replace(/\b(?:using\s+only\s+)?current\s+curated(?:\s+(?:rev\.?\s*10|evidence|data|layer|snapshot))?\b\s*[:,;-]?/gi,' ').replace(/(?:仅|只)?(?:使用|依据|根据)?\s*当前策展(?:版|层|数据|证据)?\s*[，,:：;-]?/g,' ');q=q.replace(ID_RE,(m)=>m.toUpperCase()===id?id:' ');q=q.replace(/\s+/g,' ').replace(/\s+([,.;:?!])/g,'$1').trim();if(!q.includes(id))q=`${q} ${id}`.trim();ms[i].content=q;b.messages=ms;return JSON.stringify(b)}
async function upstream(method:string,body?:string){const r=await fetch(UP,{method,headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json'},body,signal:AbortSignal.timeout(method==='POST'?90000:30000)}),t=await r.text();let x:any;try{x=JSON.parse(t)}catch{x={ok:false,error:'invalid science-exact response'}};return{r,x:patch(x)}}
function finalize(x:any){x=patch(x);x.current_release=CURRENT;x.version=VERSION;x.science_exact_version=VERSION;x.architecture='full-current-atomic-structure-snapshot';x.current_curated_revision=10;return x}
Deno.serve(async req=>{if(!internal(req))return new Response(JSON.stringify({ok:false,error:'internal service authorization required'}),{status:401,headers:H});try{const raw=req.method==='POST'?await req.text():undefined;if(req.method==='POST'&&raw){let b:any;try{b=JSON.parse(raw)}catch{b=null}const ms=messages(b),i=lastUserIndex(ms),q=i>=0?String(ms[i].content||''):'';const ids=idsFrom(q);if(ids.length){const results=await Promise.all(ids.map(id=>upstream('POST',targetBody(raw,id))));const failed=results.find(z=>!z.r.ok||z.x?.ok===false);if(failed){const x=finalize(failed.x);return new Response(JSON.stringify(x),{status:failed.r.status,headers:H})}const answers=results.map(z=>String(z.x?.answer||'').trim()).filter(Boolean);const seen=new Set<string>(),sources:any[]=[];for(const z of results)for(const s of Array.isArray(z.x?.sources)?z.x.sources:[]){const k=`${s?.type||''}|${s?.id||''}|${s?.record_id||''}|${s?.doi||''}`;if(!seen.has(k)){seen.add(k);sources.push(patch(s))}}const first=results[0].x||{};const x=finalize({...first,ok:true,answer:answers.join('\n'),sources,multi_identifier:ids.length>1,requested_structure_ids:ids});return new Response(JSON.stringify(x),{status:200,headers:H})}}
const z=await upstream(req.method,raw);const x=finalize(z.x);return new Response(JSON.stringify(x),{status:z.r.status,headers:H})}catch(e){console.error(e);return new Response(JSON.stringify({ok:false,error:'Current Curated rev.10 structured scientific layer unavailable',current_release:CURRENT,version:VERSION}),{status:503,headers:H})}});