declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const RELEASE='3.0.2',VERSION='2.3.0';
const CORS={'access-control-allow-origin':'*','access-control-allow-headers':'content-type, accept, authorization, apikey','access-control-allow-methods':'GET,HEAD,OPTIONS'};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...CORS,'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow','x-cuhalide-release':RELEASE,'x-cuhalide-candidate-version':VERSION}});
async function db(path:string,init:RequestInit={}){return fetch(`${BASE}/rest/v1/${path}`,{...init,headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json',...(init.headers||{})},signal:AbortSignal.timeout(15000)})}
async function rowsFor(status:string,limit:number){const select='candidate_id,doi,title,year,journal,authors,abstract,source,source_url,relevance_score,review_status,review_notes,discovered_at,reviewed_at,updated_at,source_payload';const r=await db(`cuhalide_atlas_candidate_queue?select=${select}&review_status=eq.${encodeURIComponent(status)}&order=relevance_score.desc,reviewed_at.desc.nullslast,discovered_at.desc&limit=${limit}`);if(!r.ok)throw new Error(`candidate ${status} ${r.status}: ${await r.text()}`);return await r.json()}
async function counts(){const r=await db('rpc/cuhalide_atlas_candidate_counts_v4',{method:'POST',body:'{}'});const raw=await r.text();if(!r.ok)throw new Error(`candidate counts ${r.status}: ${raw}`);const x=raw?JSON.parse(raw):{};for(const k of ['pending','screened_in_scope','screened_boundary','excluded','rejected'])if(!Number.isFinite(Number(x?.[k])))throw new Error(`candidate count missing: ${k}`);return x}
async function candidates(limit:number){const n=Math.max(1,Math.min(200,limit||50));const [inside,boundary,pending]=await Promise.all([rowsFor('screened_in_scope',n),rowsFor('screened_boundary',n),rowsFor('pending',Math.min(n,30))]);const rank:any={screened_in_scope:0,screened_boundary:1,pending:2};return[...inside,...boundary,...pending].sort((a:any,b:any)=>(rank[a.review_status]-rank[b.review_status])||(Number(b.relevance_score||0)-Number(a.relevance_score||0))||Number(a.candidate_id)-Number(b.candidate_id)).slice(0,n).map((c:any)=>({...c,candidate_evidence_status:c.review_status==='screened_in_scope'?'metadata-screened; primary evidence not yet acquired':c.review_status==='screened_boundary'?'metadata boundary; targeted primary-source review required':'newly discovered; metadata screen pending',release_inclusion_authorized:false,screening_version:c.source_payload?.candidate_screen_v4?.screening_version||'candidate-screen-v4'}))}
function acquisitionTotal(c:any){return Number(c.screened_in_scope||0)+Number(c.screened_boundary||0)+Number(c.pending||0)}
async function status(){const [c,runR]=await Promise.all([counts(),db('cuhalide_atlas_sync_runs?select=run_id,source,started_at,completed_at,status,candidates_found,candidates_inserted,details&order=started_at.desc&limit=1')]);const runs=runR.ok?await runR.json():[];return{ok:true,release:{version:RELEASE,date:'2026-08-11'},candidate_counts:c,public_candidate_records:acquisitionTotal(c),last_sync:runs[0]||null,screening_version:'candidate-screen-v4',monitor_version:VERSION,policy:'Metadata-screened candidates remain separate from Frozen Release and Current Curated. screened_in_scope and screened_boundary authorize primary-evidence acquisition/review only; scientific inclusion is never automatic.',evidence_boundary:'No candidate becomes a Current Curated or frozen-release record until main article, SI and/or CIF evidence is acquired as appropriate and compound-level curation/QC is completed.',external_human_independence:false,release_inclusion_authorized:false,write_access:false}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});if(!['GET','HEAD'].includes(req.method))return json({error:'read-only endpoint'},405);try{const u=new URL(req.url),action=(u.searchParams.get('action')||'status').toLowerCase(),limit=Number(u.searchParams.get('limit')||50);if(action==='status')return json(await status());if(action==='candidates'){const [items,c]=await Promise.all([candidates(limit),counts()]);return json({items,count:items.length,candidate_counts:c,public_candidate_records:acquisitionTotal(c),release:RELEASE,screening_version:'candidate-screen-v4',release_inclusion_authorized:false,evidence_boundary:'Metadata-screened acquisition candidates only; primary article/SI/CIF review and QC are required before any scientific inclusion.'})}return json({error:'unknown action',supported:['status','candidates']},404)}catch(e){console.error('[candidates-v2.3]',e);return json({ok:false,error:'candidate service unavailable',release:RELEASE,version:VERSION},503)}});
