declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const LEGACY=`${BASE}/functions/v1/cuhalide-atlas-smart-rag-v9-public-canary`,CORE302=`${BASE}/functions/v1/cuhalide-atlas-rag-v302-core-adapter-internal`,CONTRACT302=`${BASE}/functions/v1/cuhalide-atlas-rag-contract-health-v302-internal`;
const RELEASE='3.0.2',VERSION='9.12.0-public-internal';
const R13=/(?:\brecord\s*13\b|记录\s*13|CUH-013-S0[1-4]|pip6Cu10I16|pyr4Cu4Br8|pyr4Cu4I8|pyrCu2Br3)/i,DIM=/dimensionality|dimension|\b[0-3]D\b|zero[- ]dimensional|维度|零维|未解析|unresolved/i;
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow','x-cuhalide-release':RELEASE,'x-cuhalide-rag-version':VERSION}});
function lastUser(b:any){const ms=Array.isArray(b?.messages)?b.messages:[];return String([...ms].reverse().find((m:any)=>m?.role==='user'&&typeof m.content==='string')?.content||'').trim()}
async function call(url:string,method='GET',body?:string,client=''){const headers:any={apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json','user-agent':'CuHalide-Atlas-v302-Gateway/9.12.0'};if(client)headers['x-cuhalide-client']=client;const r=await fetch(url,{method,headers,body,signal:AbortSignal.timeout(method==='GET'?35000:90000)}),raw=await r.text();let x:any;try{x=JSON.parse(raw)}catch{x={error:'invalid upstream response'}};return{r,x}}
function client(req:Request){const x=String(req.headers.get('x-cuhalide-client')||'').toLowerCase();return/^[a-f0-9]{64}$/.test(x)?x:''}
async function structs(ids:string[]){if(!ids.length)return[];const u=new URL(`${BASE}/rest/v1/cuhalide_atlas_public_structures_v302`);u.searchParams.set('structure_id',`in.(${[...new Set(ids)].join(',')})`);u.searchParams.set('select','structure_id,record_id,label,formula,halogen_effective,halogen_scope,halogen_confidence,dimension_class,dimensionality,space_group,doi,doi_url');const r=await fetch(u,{headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json'},signal:AbortSignal.timeout(15000)}),t=await r.text();if(!r.ok)throw Error(`structure projection ${r.status}`);return JSON.parse(t)}
function scard(s:any){return{type:'structure',id:s.structure_id,record_id:s.record_id,title:s.label||s.structure_id,formula:s.formula||'',doi:s.doi||'',url:s.doi_url||'',space_group:s.space_group||'',dimensionality:s.dimension_class||s.dimensionality||'',halogen:s.halogen_effective||'Unresolved',halogen_scope:s.halogen_scope||'unresolved',halogen_confidence:s.halogen_confidence||'Unresolved',evidence_scope:'structure identity/crystallography only'}}
function currentText(v:any){return String(v||'').replace(/Release 3\.0\.1/g,'Release 3.0.2').replace(/release 3\.0\.1/g,'release 3.0.2').replace(/frozen Release 3\.0\.1/g,'frozen Release 3.0.2').replace(/frozen release 3\.0\.1/g,'frozen release 3.0.2')}
async function normalize(x:any){const src=Array.isArray(x?.sources)?x.sources:[],ids=src.filter((s:any)=>s?.type==='structure').map((s:any)=>String(s.id||'')).filter(Boolean),rows=await structs(ids),m=new Map(rows.map((s:any)=>[s.structure_id,scard(s)]));return{...x,release:RELEASE,version:VERSION,answer:currentText(x?.answer),sources:src.map((s:any)=>s?.type==='structure'?(m.get(String(s.id||''))||s):s),production:false,release_compatibility:{base_engine_release:'3.0.1',current_release:RELEASE,article_hash_mismatches:0,unchanged_structure_hash_mismatches:0,record13_physical_corrections:4}}}
Deno.serve(async(req:Request)=>{try{if(req.method==='GET'){const[l,c,h]=await Promise.all([call(LEGACY),call(CORE302),call(CONTRACT302)]),ok=l.r.ok&&c.r.ok&&h.r.ok&&c.x?.ok===true&&h.x?.ok===true;return json({ok,release:RELEASE,version:VERSION,agent:'CuHalide Atlas Smart RAG release-3.0.2 internal gateway',upstream_version:l.x?.version||'',core_version:c.x?.version||'',operational_mode:l.x?.provider_circuit?.state==='quota_exhausted'?'SAFE_FALLBACK':'FULL',provider_circuit:l.x?.provider_circuit||{},checks:{release_302_core:c.x?.ok===true,release_302_context_contract:h.x?.ok===true,quota_circuit_breaker:true,client_isolated_rate_path:true,structure_grain_photophysics_guard:true,release_302_record13_physical_correction:true,compatibility_hash_contract:true},write_access:false,production:false},ok?200:503)}if(req.method!=='POST')return json({error:'method not allowed'},405);const raw=await req.text();let b:any;try{b=JSON.parse(raw)}catch{return json({error:'invalid JSON'},400)}const q=lastUser(b),c=client(req);if(!q)return json({error:'user message required'},400);if(R13.test(q)&&DIM.test(q)){const z=await call(CORE302,'POST',raw,c);return json(await normalize(z.x),z.r.status)}const z=await call(LEGACY,'POST',raw,c);return json(await normalize(z.x),z.r.status)}catch(e){console.error('[v302-public-internal]',e);return json({ok:false,error:'Smart RAG release-3.0.2 internal gateway unavailable',release:RELEASE,version:VERSION},503)}});
