declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,REST=`${BASE}/rest/v1`;
const UP=`${BASE}/functions/v1/cuhalide-atlas-public-data-v302-public`,RELEASE='3.0.2',VERSION='2.16.0',REV='7',PUBLIC='https://cuhalide-atlas-v3.vercel.app',PHOTOPHYSICS_CONTRACT='1.3.0',ORGANIC_COMPONENTS_CONTRACT='1.0.0';
const ALLOWED=new Set([PUBLIC,'http://localhost:8765','http://127.0.0.1:8765']);
const AUTH={apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json'};
const DEPICTIONS:Record<string,{key:string;formula:string;charge:number}>={'acetonitrile':{key:'oc-acetonitrile',formula:'C2H3N',charge:0},'me2nh2':{key:'oc-me2nh2',formula:'C2H8N+',charge:1},'gua':{key:'oc-gua',formula:'CH6N3+',charge:1},'tetraethylammonium':{key:'oc-tetraethylammonium',formula:'C8H20N+',charge:1},'tetrapropylammonium':{key:'oc-tetrapropylammonium',formula:'C12H28N+',charge:1},'18c6':{key:'oc-18c6',formula:'C12H24O6',charge:0},'toluene':{key:'oc-toluene',formula:'C7H8',charge:0},'2-methylpyridine':{key:'oc-2-methylpyridine',formula:'C6H7N',charge:0},'2-ethylpyridine':{key:'oc-2-ethylpyridine',formula:'C7H9N',charge:0},'26-dimethylpyridine':{key:'oc-26-dimethylpyridine',formula:'C7H9N',charge:0},'35-dimethylpyridine':{key:'oc-35-dimethylpyridine',formula:'C7H9N',charge:0},'3-pic':{key:'oc-3-pic',formula:'C6H7N',charge:0},'4-pic':{key:'oc-4-pic',formula:'C6H7N',charge:0},'quinoline':{key:'oc-quinoline',formula:'C9H7N',charge:0},'4-phenoxypyridine':{key:'oc-4-phenoxypyridine',formula:'C11H9NO',charge:0},'pph3':{key:'oc-pph3',formula:'C18H15P',charge:0},'bis-diphenylphosphino-methane':{key:'oc-bis-diphenylphosphino-methane',formula:'C25H22P2',charge:0},'1-2-bis-diphenylphosphino-benzene':{key:'oc-1-2-bis-diphenylphosphino-benzene',formula:'C30H24P2',charge:0},'1-3-di-4-pyridyl-propane':{key:'oc-1-3-di-4-pyridyl-propane',formula:'C13H14N2',charge:0},'bpp':{key:'oc-bpp',formula:'C13H14N2',charge:0},'phs-c3-sph':{key:'oc-phs-c3-sph',formula:'C15H16S2',charge:0},'phs-c5-sph':{key:'oc-phs-c5-sph',formula:'C17H20S2',charge:0},'ptols-c5-stolp':{key:'oc-ptols-c5-stolp',formula:'C19H24S2',charge:0},'1-4-dibenzyl-dabco-dication':{key:'oc-1-4-dibenzyl-dabco-dication',formula:'C20H26N2+2',charge:2},'1-4-bis-4-chlorobenzyl-dabco-dication':{key:'oc-1-4-bis-4-chlorobenzyl-dabco-dication',formula:'C20H24Cl2N2+2',charge:2},'pr2-dabco':{key:'oc-pr2-dabco',formula:'C12H26N2+2',charge:2}};
function cors(req:Request){const o=req.headers.get('origin')||'';return{'access-control-allow-origin':ALLOWED.has(o)?o:PUBLIC,'access-control-allow-methods':'GET,HEAD,OPTIONS','access-control-allow-headers':'accept,content-type','vary':'Origin'}}
function hdr(req:Request,ct='application/json; charset=utf-8'){return{...cors(req),'content-type':ct,'cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow','x-cuhalide-release':RELEASE,'x-cuhalide-public-data-version':VERSION,'x-cuhalide-public-access':'query-and-view','x-cuhalide-current-curated-revision':REV,'x-cuhalide-photophysics-contract':PHOTOPHYSICS_CONTRACT,'x-cuhalide-organic-components-contract':ORGANIC_COMPONENTS_CONTRACT}}
const send=(req:Request,x:any,s=200)=>new Response(req.method==='HEAD'?null:JSON.stringify(x),{status:s,headers:hdr(req)});
function patch(x:any){if(!x||typeof x!=='object')return x;x.version=VERSION;x.current_curated_revision=7;x.architecture=x.architecture||'full-current-atomic-structure-snapshot';if(typeof x.public_note==='string')x.public_note=x.public_note.replace(/rev\.6/g,'rev.7').replace(/2026-08-18/g,'2026-08-19');if(x.current_curated&&typeof x.current_curated==='object'&&x.current_curated.current_state)x.current_curated.current_state.live_revision=7;return x}
async function rpc(name:string,body:any={}){const r=await fetch(`${REST}/rpc/${name}`,{method:'POST',headers:AUTH,body:JSON.stringify(body),signal:AbortSignal.timeout(30000)}),raw=await r.text();let x:any;try{x=raw?JSON.parse(raw):null}catch{x={error:'invalid contract response'}}if(!r.ok)throw Error(`${name} ${r.status}: ${x?.message||x?.error||raw.slice(0,160)}`);return x}
function positiveInt(v:string|null){const n=Number(v);return Number.isInteger(n)&&n>0?n:null}
function structureIds(raw:string|null){const out=[...new Set(String(raw||'').split(',').map(x=>x.trim()).filter(Boolean))];if(!out.length||out.length>40)return null;if(out.some(x=>!/^[A-Za-z0-9_-]{3,80}$/.test(x)))return null;return out}
async function photophysics(recordId:number,structureId:string|null){return rpc('cuhalide_atlas_public_photophysics_record_v2',{p_record_id:recordId,p_structure_id:structureId||null})}
async function organicComponents(ids:string[]){const rows:any[]=await rpc('cuhalide_atlas_public_organic_components_v1',{p_structure_ids:ids});return rows.map(row=>{const d=DEPICTIONS[String(row.component_key||'').toLowerCase()];return{structure_id:row.structure_id,component_key:row.component_key,display_name:row.display_name,abbreviation:row.abbreviation||null,role:row.role,normalization_confidence:row.normalization_confidence,depiction:d?{status:'verified_connectivity',key:d.key,molecular_formula:d.formula,formal_charge:d.charge,stereochemistry:'not_applicable_or_not_encoded',renderer:'RDKit 2025.09.4 coordinate layout + browser SVG'}:{status:'unresolved'}}});}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(!['GET','HEAD'].includes(req.method))return send(req,{error:'read-only endpoint'},405);try{const u=new URL(req.url),action=String(u.searchParams.get('action')||'health').toLowerCase();if(action==='photophysics-health'){const x=await rpc('cuhalide_atlas_public_photophysics_health_v2');return send(req,{...x,release:RELEASE,public_data_version:VERSION,current_curated_revision:Number(REV)});}if(action==='photophysics'){const id=positiveInt(u.searchParams.get('id')||u.searchParams.get('record_id'));if(!id)return send(req,{ok:false,error:'valid record id required'},400);const structure=String(u.searchParams.get('structure')||u.searchParams.get('structure_id')||'').trim()||null;const x=await photophysics(id,structure);return send(req,{...x,release:RELEASE,public_data_version:VERSION,current_curated_revision:Number(REV)});}if(action==='organic-components'){const ids=structureIds(u.searchParams.get('structure_ids')||u.searchParams.get('structure_id'));if(!ids)return send(req,{ok:false,error:'1-40 valid structure ids required'},400);const items=await organicComponents(ids);return send(req,{ok:true,contract_version:ORGANIC_COMPONENTS_CONTRACT,release:RELEASE,public_data_version:VERSION,current_curated_revision:Number(REV),requested_structure_count:ids.length,mapped_structure_count:new Set(items.map(x=>x.structure_id)).size,items});}const r=await fetch(UP+u.search,{method:req.method,headers:{accept:req.headers.get('accept')||'application/json','user-agent':`CuHalide-Atlas-Canonical-Public-Data/${VERSION}`},signal:AbortSignal.timeout(60000)});if(req.method==='HEAD')return new Response(null,{status:r.status,headers:hdr(req,r.headers.get('content-type')||undefined)});const raw=await r.text();let x:any;try{x=JSON.parse(raw)}catch{return new Response(raw,{status:r.status,headers:hdr(req,r.headers.get('content-type')||'text/plain; charset=utf-8')})}x=patch(x);if(r.ok&&x?.item&&(action==='article'||action==='structure')){const rid=positiveInt(String(x.item.record_id||u.searchParams.get('id')||''));if(rid){const sid=action==='structure'?String(x.item.structure_id||u.searchParams.get('id')||'').trim()||null:null;try{x.photophysics=await photophysics(rid,sid)}catch(e){console.error('[photophysics-attach]',e);x.photophysics={ok:false,public_state:'temporarily_unavailable',samples:[],conflicts:[]}}if(action==='structure'&&sid){try{x.organic_components=await organicComponents([sid])}catch(e){console.error('[organic-components-attach]',e);x.organic_components=[]}}}}return send(req,x,r.status)}catch(e){console.error('[canonical-public-data-v2160]',e);return send(req,{ok:false,error:'public data unavailable',release:RELEASE,version:VERSION},503)}});