-- CuHalide Atlas material-grain photophysics layer v1.
-- Design target: Current Curated rev.7+; Frozen Release 3.0.2 remains immutable.
-- Scientific rule: article-level properties are never copied to materials or structures without explicit mapping.
-- All tables in this migration are private curation tables. Public projection is intentionally deferred until QC.

create table if not exists public.cuhalide_atlas_material_entities (
  material_id bigint generated by default as identity primary key,
  record_id integer not null,
  material_key text not null,
  reported_label text not null default '',
  formula text not null default '',
  material_scope text not null default 'material'
    check (material_scope in ('material','polymorph','phase','sample','family','article_aggregate')),
  structure_id text,
  structure_mapping_scope text not null default 'unresolved'
    check (structure_mapping_scope in ('exact','material_only','family','article_only','unresolved','not_applicable')),
  mapping_confidence text not null default 'Unresolved'
    check (mapping_confidence in ('High','Medium','Low','Unresolved')),
  verification_status text not null default 'unresolved'
    check (verification_status in ('verified','partially_verified','unresolved','evidence_unavailable','not_applicable')),
  qc_status text not null default 'pending'
    check (qc_status in ('pending','passed','failed','recheck','not_applicable')),
  live_revision bigint not null default 7 check (live_revision >= 7),
  curator_note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (record_id, material_key)
);

create index if not exists cuhalide_atlas_material_entities_record_idx
  on public.cuhalide_atlas_material_entities(record_id, material_id);
create index if not exists cuhalide_atlas_material_entities_structure_idx
  on public.cuhalide_atlas_material_entities(structure_id)
  where structure_id is not null and btrim(structure_id) <> '';
create index if not exists cuhalide_atlas_material_entities_qc_idx
  on public.cuhalide_atlas_material_entities(qc_status, verification_status, mapping_confidence);

create table if not exists public.cuhalide_atlas_photophysics_measurements (
  measurement_id bigint generated by default as identity primary key,
  material_id bigint not null references public.cuhalide_atlas_material_entities(material_id) on delete cascade,
  record_id integer not null,
  structure_id text,
  property_code text not null check (property_code in (
    'emission_peak_nm','emission_range_nm','excitation_peak_nm','excitation_range_nm',
    'absorption_peak_nm','absorption_edge_nm','fwhm_nm','plqy_fraction','lifetime_us',
    'xel_lifetime_us','stokes_shift_nm','bandgap_ev','activation_energy_ev','cie_x','cie_y',
    'light_yield_ph_mev','detection_limit_ngyair_s','spatial_resolution_lp_mm','afterglow_ms',
    'eqe_fraction','cri','cct_k','thermal_sensitivity_pct_k','radiative_rate','nonradiative_rate',
    'dose_response','other_numeric','other_text'
  )),
  component_label text not null default '',
  numeric_value double precision,
  numeric_value_low double precision,
  numeric_value_high double precision,
  text_value text not null default '',
  unit text not null default '',
  value_origin text not null default 'reported'
    check (value_origin in ('reported','derived')),
  derivation_note text not null default '',
  measurement_mode text not null default 'other'
    check (measurement_mode in ('PL','PLE','UV_VIS','TRPL','temperature_PL','XEL','scintillation','device','other')),
  sample_state text not null default 'unspecified'
    check (sample_state in ('single_crystal','polycrystalline_crystal','powder','film','solution','nanocrystal','composite','device','other','unspecified')),
  temperature_k double precision check (temperature_k is null or temperature_k > 0),
  excitation_nm double precision check (excitation_nm is null or excitation_nm > 0),
  atmosphere text not null default '',
  condition_text text not null default '',
  is_primary_result boolean not null default true,
  mapping_confidence text not null default 'Unresolved'
    check (mapping_confidence in ('High','Medium','Low','Unresolved')),
  evidence_confidence text not null default 'Unresolved'
    check (evidence_confidence in ('High','Medium','Low','Unresolved')),
  verification_status text not null default 'unresolved'
    check (verification_status in ('verified','partially_verified','unresolved','evidence_unavailable','not_applicable')),
  public_eligible boolean not null default false,
  live_revision bigint not null default 7 check (live_revision >= 7),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    numeric_value is not null
    or numeric_value_low is not null
    or numeric_value_high is not null
    or btrim(text_value) <> ''
  ),
  check (
    value_origin = 'reported'
    or (value_origin = 'derived' and btrim(derivation_note) <> '')
  )
);

create index if not exists cuhalide_atlas_photophysics_measurements_material_idx
  on public.cuhalide_atlas_photophysics_measurements(material_id, property_code);
create index if not exists cuhalide_atlas_photophysics_measurements_record_idx
  on public.cuhalide_atlas_photophysics_measurements(record_id, property_code);
create index if not exists cuhalide_atlas_photophysics_measurements_property_idx
  on public.cuhalide_atlas_photophysics_measurements(property_code, numeric_value)
  where verification_status = 'verified';
create index if not exists cuhalide_atlas_photophysics_measurements_public_idx
  on public.cuhalide_atlas_photophysics_measurements(public_eligible, property_code)
  where public_eligible;

create table if not exists public.cuhalide_atlas_photophysics_mechanisms (
  mechanism_id bigint generated by default as identity primary key,
  material_id bigint not null references public.cuhalide_atlas_material_entities(material_id) on delete cascade,
  record_id integer not null,
  structure_id text,
  emission_component text not null default '',
  mechanism_code text not null check (mechanism_code in (
    'STE','CC','MC','MLCT','HLCT','XLCT','LMCT','LLCT','TADF','phosphorescence','fluorescence',
    'triplet_charge_transfer','cuprophilic','mixed','other','unresolved'
  )),
  claim_basis text not null default 'reported_author_assignment'
    check (claim_basis in ('reported_author_assignment','experimentally_supported','computationally_supported','curator_interpretation','unresolved')),
  assignment_text text not null default '',
  mapping_confidence text not null default 'Unresolved'
    check (mapping_confidence in ('High','Medium','Low','Unresolved')),
  evidence_confidence text not null default 'Unresolved'
    check (evidence_confidence in ('High','Medium','Low','Unresolved')),
  verification_status text not null default 'unresolved'
    check (verification_status in ('verified','partially_verified','unresolved','evidence_unavailable','not_applicable')),
  public_eligible boolean not null default false,
  live_revision bigint not null default 7 check (live_revision >= 7),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cuhalide_atlas_photophysics_mechanisms_material_idx
  on public.cuhalide_atlas_photophysics_mechanisms(material_id, mechanism_code);
create index if not exists cuhalide_atlas_photophysics_mechanisms_record_idx
  on public.cuhalide_atlas_photophysics_mechanisms(record_id, mechanism_code);

create table if not exists public.cuhalide_atlas_photophysics_evidence (
  photophysics_evidence_id bigint generated by default as identity primary key,
  material_id bigint not null references public.cuhalide_atlas_material_entities(material_id) on delete cascade,
  measurement_id bigint references public.cuhalide_atlas_photophysics_measurements(measurement_id) on delete cascade,
  mechanism_id bigint references public.cuhalide_atlas_photophysics_mechanisms(mechanism_id) on delete cascade,
  record_id integer not null,
  source_type text not null check (source_type in ('main_article','supporting_information','data_file','cif','publisher_metadata','other')),
  source_file_key text not null default '',
  source_sha256 text not null default '',
  page_locator text not null default '',
  section_locator text not null default '',
  table_locator text not null default '',
  figure_locator text not null default '',
  source_value text not null default '',
  verbatim_excerpt text not null default '',
  locator_status text not null default 'encoded'
    check (locator_status in ('encoded','record_level_only','not_applicable','unavailable')),
  verification_status text not null default 'unresolved'
    check (verification_status in ('verified','partially_verified','unresolved','evidence_unavailable','not_applicable')),
  created_at timestamptz not null default now(),
  check (measurement_id is not null or mechanism_id is not null)
);

create index if not exists cuhalide_atlas_photophysics_evidence_measurement_idx
  on public.cuhalide_atlas_photophysics_evidence(measurement_id);
create index if not exists cuhalide_atlas_photophysics_evidence_mechanism_idx
  on public.cuhalide_atlas_photophysics_evidence(mechanism_id);
create index if not exists cuhalide_atlas_photophysics_evidence_record_idx
  on public.cuhalide_atlas_photophysics_evidence(record_id);

create table if not exists public.cuhalide_atlas_photophysics_review (
  record_id integer primary key,
  review_status text not null default 'unreviewed'
    check (review_status in ('unreviewed','in_progress','primary_evidence_missing','not_applicable','qc_pending','qc_passed','qc_failed')),
  main_article_status text not null default 'unreviewed'
    check (main_article_status in ('unreviewed','read','missing','not_applicable')),
  supporting_information_status text not null default 'unreviewed'
    check (supporting_information_status in ('unreviewed','read','missing','not_applicable')),
  material_mapping_status text not null default 'unresolved'
    check (material_mapping_status in ('unresolved','partial','complete','not_applicable')),
  property_mapping_status text not null default 'unresolved'
    check (property_mapping_status in ('unresolved','partial','complete','not_applicable')),
  expected_material_count integer check (expected_material_count is null or expected_material_count >= 0),
  curated_material_count integer not null default 0 check (curated_material_count >= 0),
  measurement_count integer not null default 0 check (measurement_count >= 0),
  mechanism_count integer not null default 0 check (mechanism_count >= 0),
  unresolved_item_count integer not null default 0 check (unresolved_item_count >= 0),
  reviewer text not null default '',
  review_note text not null default '',
  first_reviewed_at timestamptz,
  last_reviewed_at timestamptz,
  qc_at timestamptz,
  live_revision bigint not null default 7 check (live_revision >= 7),
  updated_at timestamptz not null default now()
);

create index if not exists cuhalide_atlas_photophysics_review_status_idx
  on public.cuhalide_atlas_photophysics_review(review_status, record_id);

-- Fail closed. These are private curation/evidence tables; only service_role may read/write them.
alter table public.cuhalide_atlas_material_entities enable row level security;
alter table public.cuhalide_atlas_photophysics_measurements enable row level security;
alter table public.cuhalide_atlas_photophysics_mechanisms enable row level security;
alter table public.cuhalide_atlas_photophysics_evidence enable row level security;
alter table public.cuhalide_atlas_photophysics_review enable row level security;

drop policy if exists material_entities_deny_untrusted on public.cuhalide_atlas_material_entities;
create policy material_entities_deny_untrusted on public.cuhalide_atlas_material_entities
  as restrictive for all to anon, authenticated using (false) with check (false);
drop policy if exists photophysics_measurements_deny_untrusted on public.cuhalide_atlas_photophysics_measurements;
create policy photophysics_measurements_deny_untrusted on public.cuhalide_atlas_photophysics_measurements
  as restrictive for all to anon, authenticated using (false) with check (false);
drop policy if exists photophysics_mechanisms_deny_untrusted on public.cuhalide_atlas_photophysics_mechanisms;
create policy photophysics_mechanisms_deny_untrusted on public.cuhalide_atlas_photophysics_mechanisms
  as restrictive for all to anon, authenticated using (false) with check (false);
drop policy if exists photophysics_evidence_deny_untrusted on public.cuhalide_atlas_photophysics_evidence;
create policy photophysics_evidence_deny_untrusted on public.cuhalide_atlas_photophysics_evidence
  as restrictive for all to anon, authenticated using (false) with check (false);
drop policy if exists photophysics_review_deny_untrusted on public.cuhalide_atlas_photophysics_review;
create policy photophysics_review_deny_untrusted on public.cuhalide_atlas_photophysics_review
  as restrictive for all to anon, authenticated using (false) with check (false);

revoke all on public.cuhalide_atlas_material_entities from anon, authenticated;
revoke all on public.cuhalide_atlas_photophysics_measurements from anon, authenticated;
revoke all on public.cuhalide_atlas_photophysics_mechanisms from anon, authenticated;
revoke all on public.cuhalide_atlas_photophysics_evidence from anon, authenticated;
revoke all on public.cuhalide_atlas_photophysics_review from anon, authenticated;

grant select, insert, update, delete on public.cuhalide_atlas_material_entities to service_role;
grant select, insert, update, delete on public.cuhalide_atlas_photophysics_measurements to service_role;
grant select, insert, update, delete on public.cuhalide_atlas_photophysics_mechanisms to service_role;
grant select, insert, update, delete on public.cuhalide_atlas_photophysics_evidence to service_role;
grant select, insert, update, delete on public.cuhalide_atlas_photophysics_review to service_role;
grant usage, select on all sequences in schema public to service_role;
