create table if not exists public.cuhalide_atlas_conversation_usage (
  id bigint generated by default as identity primary key,
  fingerprint_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists cuhalide_atlas_conversation_usage_fingerprint_created_idx
  on public.cuhalide_atlas_conversation_usage (fingerprint_hash, created_at desc);
create index if not exists cuhalide_atlas_conversation_usage_created_idx
  on public.cuhalide_atlas_conversation_usage (created_at desc);

alter table public.cuhalide_atlas_conversation_usage enable row level security;
revoke all on table public.cuhalide_atlas_conversation_usage from public, anon, authenticated;

create or replace function public.cuhalide_atlas_conversation_rate_limit_v10(p_fingerprint text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  h integer;
  d integer;
  g integer;
  hour_limit constant integer := 60;
  day_limit constant integer := 240;
  global_day_limit constant integer := 1200;
begin
  if p_fingerprint is null or p_fingerprint !~ '^[a-f0-9]{64}$' then
    return jsonb_build_object('allowed', false, 'reason', 'invalid_fingerprint');
  end if;

  delete from public.cuhalide_atlas_conversation_usage
   where created_at < now() - interval '2 days';

  select count(*)::int into h
    from public.cuhalide_atlas_conversation_usage
   where fingerprint_hash = p_fingerprint
     and created_at >= now() - interval '1 hour';

  select count(*)::int into d
    from public.cuhalide_atlas_conversation_usage
   where fingerprint_hash = p_fingerprint
     and created_at >= now() - interval '1 day';

  select count(*)::int into g
    from public.cuhalide_atlas_conversation_usage
   where created_at >= now() - interval '1 day';

  if h + 1 > hour_limit or d + 1 > day_limit or g + 1 > global_day_limit then
    return jsonb_build_object(
      'allowed', false,
      'hour_count', h,
      'day_count', d,
      'global_day_count', g,
      'hour_limit', hour_limit,
      'day_limit', day_limit,
      'global_day_limit', global_day_limit
    );
  end if;

  insert into public.cuhalide_atlas_conversation_usage(fingerprint_hash)
  values (p_fingerprint);

  return jsonb_build_object(
    'allowed', true,
    'hour_count', h + 1,
    'day_count', d + 1,
    'global_day_count', g + 1,
    'hour_limit', hour_limit,
    'day_limit', day_limit,
    'global_day_limit', global_day_limit
  );
end;
$function$;

revoke all on function public.cuhalide_atlas_conversation_rate_limit_v10(text) from public, anon, authenticated;
grant execute on function public.cuhalide_atlas_conversation_rate_limit_v10(text) to service_role;

comment on function public.cuhalide_atlas_conversation_rate_limit_v10(text) is
'Conversation-only rate limiter for CuHalide Research Assistant v10. Keeps ordinary LLM chat usage separate from the stricter scientific evidence-query quota.';
