-- CuHalide Atlas rolling Current Curated workflow.
-- Applied to production on 2026-08-11 after validation of frozen release 3.0.2.
-- Private operational tables: no anon/authenticated access.

create table if not exists public.cuhalide_atlas_current_curated_state (
  state_key text primary key default 'current' check (state_key = 'current'),
  base_release text not null,
  current_curated_through date not null,
  article_audit_records integer not null check (article_audit_records >= 0),
  chemically_included_articles integer not null check (chemically_included_articles >= 0),
  canonical_verified_articles integer not null check (canonical_verified_articles >= 0),
  structure_phase_rows integer not null check (structure_phase_rows >= 0),
  core_included_structure_rows integer not null check (core_included_structure_rows >= 0),
  resolved_space_group_rows integer not null check (resolved_space_group_rows >= 0),
  verified_space_group_rows integer not null check (verified_space_group_rows >= 0),
  verified_polar_rows integer not null check (verified_polar_rows >= 0),
  strict_polar_rows integer not null check (strict_polar_rows >= 0),
  strict_polar_articles integer not null check (strict_polar_articles >= 0),
  rag_documents integer not null check (rag_documents >= 0),
  rag_embedded integer not null check (rag_embedded >= 0),
  live_revision bigint not null default 0 check (live_revision >= 0),
  status text not null check (status in ('validated_base_pending_publish','ready','updating','qc_failed','frozen_for_release')),
  last_qc_at timestamptz,
  note text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.cuhalide_atlas_curation_queue (
  queue_id bigint generated by default as identity primary key,
  normalized_doi text,
  title text not null default '',
  source_url text not null default '',
  journal text not null default '',
  publication_date date,
  discovered_at timestamptz not null default now(),
  discovery_source text not null default '',
  source_status text not null default 'unknown' check (source_status in ('peer_reviewed_final','early_view','preprint','unknown')),
  workflow_status text not null default 'DISCOVERED' check (workflow_status in ('DISCOVERED','DEDUPED','TRIAGED','NOTIFIED','PRIMARY_EVIDENCE_RECEIVED','EXTRACTED','QC_PASSED','LIVE_CURATED','FORMAL_RELEASE','REJECTED','BLOCKED')),
  scope_confidence text not null default 'Unresolved' check (scope_confidence in ('High','Medium','Low','Unresolved')),
  main_article_received boolean not null default false,
  si_received boolean not null default false,
  cif_received boolean not null default false,
  candidate_reference text not null default '',
  scope_notes text not null default '',
  qc_notes text not null default '',
  notified_at timestamptz,
  primary_evidence_received_at timestamptz,
  extracted_at timestamptz,
  qc_passed_at timestamptz,
  live_curated_at timestamptz,
  formal_release text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists cuhalide_atlas_curation_queue_doi_uq
  on public.cuhalide_atlas_curation_queue (lower(normalized_doi))
  where normalized_doi is not null and btrim(normalized_doi) <> '';
create index if not exists cuhalide_atlas_curation_queue_status_idx
  on public.cuhalide_atlas_curation_queue (workflow_status, discovered_at desc);

create table if not exists public.cuhalide_atlas_current_curated_changes (
  change_id bigint generated by default as identity primary key,
  queue_id bigint references public.cuhalide_atlas_curation_queue(queue_id) on delete set null,
  change_batch text not null,
  entity_grain text not null check (entity_grain in ('article','structure','rag','metadata')),
  record_id integer,
  structure_id text,
  change_type text not null check (change_type in ('insert','update','reindex','metadata')),
  field_name text,
  old_value jsonb,
  new_value jsonb,
  evidence_basis text not null default '',
  source_doi text not null default '',
  qc_status text not null default 'pending' check (qc_status in ('pending','passed','failed','reverted')),
  created_at timestamptz not null default now(),
  qc_at timestamptz
);
create index if not exists cuhalide_atlas_current_curated_changes_batch_idx
  on public.cuhalide_atlas_current_curated_changes(change_batch, change_id);
create index if not exists cuhalide_atlas_current_curated_changes_queue_id_idx
  on public.cuhalide_atlas_current_curated_changes(queue_id);

alter table public.cuhalide_atlas_current_curated_state enable row level security;
alter table public.cuhalide_atlas_curation_queue enable row level security;
alter table public.cuhalide_atlas_current_curated_changes enable row level security;

drop policy if exists current_curated_state_deny_untrusted on public.cuhalide_atlas_current_curated_state;
create policy current_curated_state_deny_untrusted on public.cuhalide_atlas_current_curated_state
  as restrictive for all to anon, authenticated using (false) with check (false);
drop policy if exists curation_queue_deny_untrusted on public.cuhalide_atlas_curation_queue;
create policy curation_queue_deny_untrusted on public.cuhalide_atlas_curation_queue
  as restrictive for all to anon, authenticated using (false) with check (false);
drop policy if exists current_curated_changes_deny_untrusted on public.cuhalide_atlas_current_curated_changes;
create policy current_curated_changes_deny_untrusted on public.cuhalide_atlas_current_curated_changes
  as restrictive for all to anon, authenticated using (false) with check (false);

revoke all on public.cuhalide_atlas_current_curated_state from anon, authenticated;
revoke all on public.cuhalide_atlas_curation_queue from anon, authenticated;
revoke all on public.cuhalide_atlas_current_curated_changes from anon, authenticated;
grant select, insert, update, delete on public.cuhalide_atlas_current_curated_state to service_role;
grant select, insert, update, delete on public.cuhalide_atlas_curation_queue to service_role;
grant select, insert, update, delete on public.cuhalide_atlas_current_curated_changes to service_role;
grant usage, select on all sequences in schema public to service_role;
