import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,ROOT=`${BASE}/functions/v1`;
const CURRENT=`${ROOT}/cuhalide-atlas-current-rag-r10-unified-internal`,FROZEN=`${ROOT}/cuhalide-atlas-smart-rag-v302-public`,PUBLIC_DATA=`${ROOT}/cuhalide-atlas-public-data-v3`;
const RELEASE='3.0.2',VERSION='10.0.0',CURRENT_RELEASE='current-curated-r10',REV=10,DOCS=1322,PH='1.4.0',OC='1.2.0';
const FROZEN_INTENT=/(?:Frozen(?:\s+Release)?|release\s*3\.0\.2|3\.0\.2\s*(?:release|snapshot)|historical\s+(?:snapshot|release)|冻结(?:发布|快照)?|历史快照|归档快照)/i;
const LATEST=/(?:latest|newest|recent|new papers?|new literature|literature watch|最新|最近|新文献|新论文)/i;
const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow, noarchive','x-cuhalide-release':RELEASE,'x-cuhalide-rag-version':VERSION,'x-cuhalide-current-curated-revision':'10','x-cuhalide-photophysics-contract':PH,'x-cuhalide-organic-components-contract':OC,'x-cuhalide-knowledge-contract':'1.2.0'};
const send=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
async function call(url:string,method='GET',body?:string){const r=await fetch(url,{method,headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json'},body,signal:AbortSignal.timeout(method==='GET'?35000:100000)}),t=await r.text();let x:any;try{x=JSON.parse(t)}catch{x={error:'invalid upstream response'}}return{r,x}}
async function rpc(name:string,body:any={}){const r=await fetch(`${BASE}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:KEY,authorization:`Bearer ${KEY}`,'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(30000)}),t=await r.text();if(!r.ok)throw Error('Evidence contract unavailable');return JSON.parse(t)}
async function pd(action:string,params:Record<string,string>={}){const u=new URL(PUBLIC_DATA);u.searchParams.set('action',action);for(const[k,v]of Object.entries(params))u.searchParams.set(k,v);const r=await fetch(u,{headers:{accept:'application/json'},signal:AbortSignal.timeout(25000)}),t=await r.text();if(!r.ok)throw Error(`public-data ${action}`);return JSON.parse(t)}
function lastUser(b:any){const ms=Array.isArray(b?.messages)?b.messages:[];return String([...ms].reverse().find((m:any)=>m?.role==='user'&&typeof m.content==='string')?.content||'').trim()}
async function watch(q:string){if(!LATEST.test(q))return{answer:'',sources:[]};try{const x=await pd('candidates',{limit:'6'}),items=Array.isArray(x?.items)?x.items:[];if(!items.length)return{answer:'',sources:[]};const z=/[\u3400-\u9fff]/.test(q),lines=[z?'### Literature Watch（候选元数据）':'### Literature Watch (candidate metadata)'];for(const c of items)lines.push(`- ${c.doi?`**${c.doi}** — `:''}${c.title||''}${c.year?` (${c.year})`:''}.`);lines.push('',z?'> 候选仅为发现元数据，未经 Current Curated review/QC 的记录不是策展证据。':'> Candidates are discovery metadata only; records not promoted through Current Curated review/QC are not curated evidence.');return{answer:lines.join('\n'),sources:items.map((c:any)=>({type:'web',id:c.doi||c.candidate_id,title:c.title||'',doi:c.doi||'',url:c.source_url||'',year:c.year||'',journal:c.journal||'',status:'Literature Watch candidate; metadata-only'}))}}catch{return{answer:'',sources:[]}}}
Deno.serve(async req=>{if(!['GET','POST'].includes(req.method))return send({error:'method not allowed'},405);try{if(req.method==='GET'){const [cur,h,ph,oc]=await Promise.all([call(CURRENT),rpc('cuhalide_atlas_current_curated_health_v1'),pd('photophysics-health'),pd('organic-components-health')]);const currentOk=cur.r.ok&&cur.x?.ok===true&&Number(cur.x?.active_current_documents||0)===DOCS&&Number(cur.x?.active_current_embedded||0)===DOCS;const ok=currentOk&&h?.ok===true&&ph?.ok===true&&oc?.ok===true;return send({ok,release:RELEASE,version:VERSION,knowledge_contract:'1.2.0',display_name:'CuXplore',service:'CuHalide Smart RAG',operational_mode:ok?'FULL':'UNAVAILABLE',current_curated:{layer:CURRENT_RELEASE,live_revision:REV,curated_through:'2026-09-14',architecture:'full-current-atomic-structure-snapshot',documents:DOCS,embedded:DOCS},corpus:{active_current_documents:DOCS,active_current_embedded:DOCS},photophysics:{ok:ph?.ok===true,version:PH},organic_components:{ok:oc?.ok===true,version:OC},checks:{current_curated_rag:currentOk,current_curated_database:h?.ok===true,photophysics_contract:ph?.ok===true,organic_components_contract:oc?.ok===true},write_access:false},ok?200:503)}const raw=await req.text();if(raw.length>20000)return send({ok:false,error:'Request body too large.'},413);let b:any;try{b=JSON.parse(raw)}catch{return send({ok:false,error:'Invalid JSON request.'},400)}const q=lastUser(b);if(!q)return send({ok:false,error:'User message required.'},400);if(FROZEN_INTENT.test(q)){const z=await call(FROZEN,'POST',raw);return send({...z.x,route:'frozen-3.0.2',current_release:CURRENT_RELEASE,current_curated_revision:REV},z.r.status)}const cur=await call(CURRENT,'POST',raw),w=await watch(q);let answer=String(cur.x?.answer||'').trim(),sources=Array.isArray(cur.x?.sources)?cur.x.sources:[];if(w.answer){answer+=`${answer?'\n\n':''}${w.answer}`;sources=[...sources,...w.sources].slice(0,24)}return send({...cur.x,ok:cur.r.ok&&cur.x?.ok!==false,release:RELEASE,version:VERSION,knowledge_contract:'1.2.0',current_release:CURRENT_RELEASE,current_curated_revision:REV,answer,sources,route:LATEST.test(q)?'current-plus-literature-watch':'current',fallback:cur.x?.fallback===true,write_access:false},cur.r.status)}catch(e){console.error('[smart-rag-integrated]',e);return send({ok:false,error:'CuHalide Smart RAG is temporarily unavailable.',release:RELEASE,version:VERSION,knowledge_contract:'1.2.0',current_release:CURRENT_RELEASE,current_curated_revision:REV,operational_mode:'UNAVAILABLE'},503)}});
