declare const Deno:any;
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
const BASE=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const UP=`${BASE}/functions/v1/cuhalide-atlas-current-rag-r7-exact-internal`;
const CURRENT='current-curated-r8',VERSION='current-rag-r8-exact-1.0.0',PHOTOPHYSICS_CONTRACT='1.3.3';
const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-robots-tag':'noindex, nofollow, noarchive','x-cuhalide-release':'3.0.2','x-cuhalide-current-curated-revision':'8','x-cuhalide-photophysics-contract':PHOTOPHYSICS_CONTRACT,'x-cuhalide-publication-state':'prepublication-review','x-cuhalide-endpoint-state':'internal-service-only'};
const send=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
function internal(req:Request){return req.headers.get('authorization')===`Bearer ${KEY}`&&req.headers.get('apikey')===KEY}
function patch(x:any):any{if(Array.isArray(x))return x.map(patch);if(!x||typeof x!=='object')return x;const out:any={};for(const[k,v]of Object.entries(x)){if(k==='live_revision'||k==='current_curated_revision')out[k]=8;else if(k==='current_release')out[k]=CURRENT;else out[k]=patch(v)}return out}
Deno.serve(async(req:Request)=>{if(!internal(req))return send({ok:false,error:'internal service authorization required'},401);if(!['GET','POST'].includes(req.method))return send({error:'method not allowed'},405);try{const raw=req.method==='POST'?await req.text():undefined;const r=await fetch(UP,{method:req.method,headers:{apikey:KEY,authorization:`Bearer ${KEY}`,accept:'application/json','content-type':'application/json'},body:raw,signal:AbortSignal.timeout(req.method==='POST'?90000:30000)}),t=await r.text();let x:any;try{x=JSON.parse(t)}catch{x={error:'invalid exact-current response'}};x=patch(x);x.current_release=CURRENT;x.version=VERSION;x.architecture='full-current-atomic-structure-snapshot';x.photophysics_contract=PHOTOPHYSICS_CONTRACT;return send(x,r.status)}catch(e){console.error('[current-rag-r8-exact-wrapper]',e);return send({ok:false,error:'Current Curated rev.8 deterministic layer unavailable',current_release:CURRENT,version:VERSION,photophysics_contract:PHOTOPHYSICS_CONTRACT},503)}});