declare const Deno:any;
const BASE=Deno.env.get('SUPABASE_URL')!;
const KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const REL='3.0.0';
const KIND='web_site_frozen_v36';
const SHA='450f9deb74050dbd5c26403224d2bf943488e052241084dcde41644274b42891';
const DATA=`${BASE}/functions/v1/cuhalide-atlas-data-stable`;
const AGENT=`${BASE}/functions/v1/cuhalide-atlas-smart-rag`;
const META=`${BASE}/functions/v1/cuhalide-atlas-meta`;
const RELEASE_URL='https://cuhalide-atlas-v3.vercel.app/?release=3.0.0';
const CORS={'access-control-allow-origin':'*','access-control-allow-headers':'authorization, x-client-info, apikey, content-type','access-control-allow-methods':'GET,HEAD,POST,OPTIONS'};
const SECURITY={'x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'strict-origin-when-cross-origin','permissions-policy':'camera=(), microphone=(), geolocation=()','cross-origin-opener-policy':'same-origin','cross-origin-resource-policy':'same-origin','x-robots-tag':'index, follow, max-image-preview:large'};
const CACHE='public, max-age=600, s-maxage=3600, stale-while-revalidate=86400';
let CACHE_HTML:Promise<string>|null=null;
async function sha256(s:string){const h=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));return[...h].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function html(){if(CACHE_HTML)return CACHE_HTML;CACHE_HTML=(async()=>{const u=`${BASE}/rest/v1/cuhalide_atlas_payload_chunks?kind=eq.${KIND}&release_version=eq.${REL}&chunk_index=eq.0&select=chunk_index,total_chunks,encoding,data,payload_sha256`;const r=await fetch(u,{headers:{apikey:KEY,authorization:`Bearer ${KEY}`}});if(!r.ok)throw new Error(`site snapshot ${r.status}: ${await r.text()}`);const rows=await r.json();if(rows.length!==1)throw new Error(`site snapshot rows ${rows.length}/1`);const x=rows[0];if(x.chunk_index!==0||x.total_chunks!==1||x.encoding!=='plain-html'||x.payload_sha256!==SHA)throw new Error('site snapshot metadata mismatch');const h=String(x.data||'');if(await sha256(h)!==SHA)throw new Error('site snapshot sha mismatch');const required=[DATA,AGENT,`${META}?asset=manifest`,`monitorAPI('bootstrap')`,'application/ld+json','rel="preconnect"','Complete structure and space-group register','Smart RAG active','CUHALIDE_UI_V31_START','CUHALIDE_EVIDENCE_COMPARE_V33','CUHALIDE_VERSIONED_PERMALINK_V34','CUHALIDE_RELEASE_METADATA_V35','Copy stable record link','View stored evidence','Interpret in Smart RAG','Release provenance bundle','citation_title','Release bootstrap unavailable for article deep link.','this view only juxtaposes stored release fields','Not stored in release 3.0.0',"searchParams.set('release','3.0.0')","requestedRelease!=='3.0.0'","hasDeepLink || requestedRelease==='3.0.0'",RELEASE_URL,`"@id":"${RELEASE_URL}"`,`"identifier":"${RELEASE_URL}"`,'Centrosymmetry & polarity','Derived symmetry view','<strong>518</strong> are centrosymmetric','<strong>Verified polar:</strong> 87','<strong>Strict polar:</strong> 67','CuHalide_Smart_RAG_'];for(const token of required)if(!h.includes(token))throw new Error(`site snapshot invariant missing: ${token}`);if(h.includes('>\\n  <link rel="alternate"')||h.includes("monitorAPI('status'), monitorAPI('overview')")||h.includes("behavior:'instant'")||h.includes(`${BASE}/functions/v1/cuhalide-atlas-agent`)||h.includes('Research Agent')||h.includes('CuHalide_Agent_'))throw new Error('site snapshot contains deprecated or malformed path');return h})().catch(e=>{CACHE_HTML=null;throw e});return CACHE_HTML}
function json(x:any,status=200){return new Response(JSON.stringify(x),{status,headers:{...CORS,...SECURITY,'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function proxyData(req:Request){const i=new URL(req.url),t=new URL(DATA);for(const[k,v]of i.searchParams)t.searchParams.append(k,v);const h=new Headers(req.headers);h.delete('host');return fetch(t,{method:req.method,headers:h,body:['GET','HEAD'].includes(req.method)?undefined:req.body,redirect:'follow'})}
async function proxyMeta(asset:string){const map:Record<string,string>={health:'health','release-manifest':'manifest',sitemap:'sitemap',robots:'robots',citation:'citation'};const key=map[asset];if(!key)return null;return fetch(`${META}?asset=${key}`,{headers:{accept:asset==='sitemap'?'application/xml':asset==='robots'||asset==='citation'?'text/plain':'application/json'}})}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});try{const u=new URL(req.url),asset=u.searchParams.get('asset')||'';if(asset){const r=await proxyMeta(asset);if(r)return new Response(req.method==='HEAD'?null:await r.text(),{status:r.status,headers:{...CORS,...SECURITY,'content-type':r.headers.get('content-type')||'text/plain; charset=utf-8','cache-control':asset==='health'?'no-store':'public, max-age=3600'}})}if(u.searchParams.get('action'))return proxyData(req);if(!['GET','HEAD'].includes(req.method))return json({error:'read-only site route'},405);const h=await html();return new Response(req.method==='HEAD'?null:h,{status:200,headers:{...CORS,...SECURITY,'content-type':'text/html; charset=utf-8','cache-control':CACHE,'etag':`W/"cuhalide-site-v36-${SHA.slice(0,16)}"`,'x-cuhalide-site-version':'36','x-cuhalide-site-snapshot':SHA,'content-security-policy':`default-src 'self' data:; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self' ${BASE}; base-uri 'self'; form-action 'self'; frame-ancestors 'none'`}})}catch(e){console.error('[cuhalide-site-v36]',e);return json({error:String(e)},503)}});
