import crypto from 'node:crypto';
const ASSISTANT_UPSTREAM='https://tyxnyjyrfzspwcfjpzus.supabase.co/functions/v1/cuhalide-atlas-research-assistant-v1-public',CONTRACT_UPSTREAM='https://tyxnyjyrfzspwcfjpzus.supabase.co/functions/v1/cuhalide-atlas-runtime-contract-v1-public',PUBLIC_ORIGIN='https://cuhalide-atlas-v3.vercel.app',RELEASE='3.0.2',ASSISTANT_VERSION='10.2.0',EVIDENCE_VERSION='9.17.0',CURRENT_REVISION='5',MAX_BODY_BYTES=20000;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function requestBody(req){if(req.body==null)return undefined;if(Buffer.isBuffer(req.body)||typeof req.body==='string')return req.body;return JSON.stringify(req.body)}
function networkParts(req){const ip=String(req.headers['x-forwarded-for']||req.headers['x-real-ip']||'').split(',')[0].trim().slice(0,96),ua=String(req.headers['user-agent']||'').slice(0,240);return{ip,ua}}
function evidenceFingerprint(req){const{ip,ua}=networkParts(req);return crypto.createHash('sha256').update(`cuhalide-v50-evidence-v10.2|${ip}|${ua}`).digest('hex')}
function conversationFingerprint(req){const{ip,ua}=networkParts(req),session=String(req.headers['x-cuhalide-session']||'').toLowerCase(),safe=/^[a-f0-9]{64}$/.test(session)?session:'no-session';return crypto.createHash('sha256').update(`cuhalide-v50-conversation-v10.2|${ip}|${ua}|${safe}`).digest('hex')}
function bodyContract(body){if(body==null)return{ok:true};const raw=Buffer.isBuffer(body)?body:Buffer.from(typeof body==='string'?body:JSON.stringify(body));if(raw.byteLength>MAX_BODY_BYTES)return{ok:false,status:413,error:'Request body too large.'};let parsed;try{parsed=typeof body==='object'&&!Buffer.isBuffer(body)?body:JSON.parse(raw.toString('utf8'))}catch{return{ok:false,status:400,error:'Invalid JSON request body.'}}const messages=Array.isArray(parsed?.messages)?parsed.messages:[];if(messages.length>12)return{ok:false,status:400,error:'Too many chat messages.'};if(messages.some(m=>typeof m?.content!=='string'||m.content.length>4000))return{ok:false,status:413,error:'Message content exceeds the public query limit.'};return{ok:true}}
async function upstreamRequest(req,url){const isPost=req.method==='POST',attempts=isPost?1:3;let lastError=null,last=null;for(let attempt=0;attempt<attempts;attempt++){const headers={accept:req.headers.accept||'application/json','user-agent':`CuHalide-Atlas-Vercel-Research-Assistant/${ASSISTANT_VERSION}`};if(isPost){headers['content-type']=req.headers['content-type']||'application/json';headers['x-cuhalide-client']=evidenceFingerprint(req);headers['x-cuhalide-conversation-client']=conversationFingerprint(req)}try{const response=await fetch(url,{method:req.method,headers,body:isPost?requestBody(req):undefined,redirect:'follow',signal:AbortSignal.timeout(isPost?125000:5000)}),body=req.method==='HEAD'?'':await response.text();last={response,body};if(isPost||(![429].includes(response.status)&&response.status<500)||attempt===attempts-1)return last}catch(error){lastError=error;if(isPost||attempt===attempts-1)throw error}if(attempt<attempts-1)await sleep(180*(attempt+1))}if(last)return last;throw lastError||Error('Research Assistant upstream unavailable')}
function commonHeaders(res){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control','no-store');res.setHeader('X-Robots-Tag','noindex, nofollow');res.setHeader('X-CuHalide-Public-Access','query-and-view');res.setHeader('X-CuHalide-Release',RELEASE);res.setHeader('X-CuHalide-RAG-Version',EVIDENCE_VERSION);res.setHeader('X-CuHalide-Assistant-Version',ASSISTANT_VERSION);res.setHeader('X-CuHalide-Current-Curated-Revision',CURRENT_REVISION)}
export default async function handler(req,res){if(req.method==='OPTIONS'){res.statusCode=204;res.setHeader('Allow','GET, HEAD, POST, OPTIONS');res.setHeader('Cache-Control','no-store');return res.end()}if(!['GET','HEAD','POST'].includes(req.method)){res.statusCode=405;res.setHeader('Allow','GET, HEAD, POST, OPTIONS');return res.end('Method Not Allowed')}if(req.method==='POST'){const contract=bodyContract(req.body);if(!contract.ok){res.statusCode=contract.status;res.setHeader('Content-Type','application/json; charset=utf-8');commonHeaders(res);return res.end(JSON.stringify({error:contract.error,release:RELEASE,version:EVIDENCE_VERSION,assistant_version:ASSISTANT_VERSION}))}}try{const incoming=new URL(req.url,PUBLIC_ORIGIN),upstream=req.method==='POST'?new URL(ASSISTANT_UPSTREAM):new URL(CONTRACT_UPSTREAM);if(req.method!=='POST')upstream.searchParams.set('action','assistant');for(const[key,value]of incoming.searchParams.entries())upstream.searchParams.append(key,value);const{response,body}=await upstreamRequest(req,upstream);res.statusCode=response.status;res.setHeader('Content-Type',response.headers.get('content-type')||'application/json; charset=utf-8');commonHeaders(res);for(const header of['x-cuhalide-release','x-cuhalide-rag-version','x-cuhalide-assistant-version','x-cuhalide-current-curated-revision']){const value=response.headers.get(header);if(value)res.setHeader(header,value)}if(response.status===429||response.status>=500)res.setHeader('Retry-After',response.headers.get('retry-after')||'30');if(req.method==='HEAD')return res.end();return res.end(body)}catch(error){console.error('[cuhalide-research-assistant-proxy-v50.1]',error);res.statusCode=error?.name==='TimeoutError'||error?.name==='AbortError'?504:503;res.setHeader('Content-Type','application/json; charset=utf-8');commonHeaders(res);res.setHeader('Retry-After','30');if(req.method==='HEAD')return res.end();return res.end(JSON.stringify({error:res.statusCode===504?'CuHalide Research Assistant backend timed out.':'CuHalide Research Assistant backend is temporarily unavailable.',release:RELEASE,version:EVIDENCE_VERSION,assistant_version:ASSISTANT_VERSION}))}}
