import fs from 'node:fs';
import path from 'node:path';
const CONTRACT='https://tyxnyjyrfzspwcfjpzus.supabase.co/functions/v1/cuhalide-atlas-runtime-contract-v1-public';
const PUBLIC='https://cuhalide-atlas-v3.vercel.app',RELEASE='3.0.2',SITE='51',UI='51.0',META='51.0',PUBLIC_DATA='2.17.1',PH='1.4.0',OC='1.2.0',RAG='9.20.0',ASSISTANT='10.5.0',REV='9',STATE='prepublication-review';
const CITATION_PATH=path.join(process.cwd(),'CITATION.cff');
const headers=(ct='application/json; charset=utf-8')=>({'Content-Type':ct,'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow, noarchive','X-Content-Type-Options':'nosniff','X-CuHalide-Release':RELEASE,'X-CuHalide-Site-Version':SITE,'X-CuHalide-UI-Version':UI,'X-CuHalide-Meta-Version':META,'X-CuHalide-Public-Data-Version':PUBLIC_DATA,'X-CuHalide-Photophysics-Contract':PH,'X-CuHalide-Organic-Components-Contract':OC,'X-CuHalide-RAG-Version':RAG,'X-CuHalide-Assistant-Version':ASSISTANT,'X-CuHalide-Current-Curated-Revision':REV,'X-CuHalide-Publication-State':STATE});
async function runtime(action='health'){const u=new URL(CONTRACT);u.searchParams.set('action',action);const r=await fetch(u,{headers:{accept:'application/json','user-agent':'CuHalide-Atlas-Meta/51.0'},signal:AbortSignal.timeout(12000)}),raw=await r.text();let x;try{x=JSON.parse(raw)}catch{x={ok:false,error:'invalid runtime health response'}};if(!r.ok||x?.ok!==true)throw Error(`runtime contract ${r.status}`);return x}
function manifest(){return{schema_version:'2.4',project:'CuHalide Atlas',public_origin:PUBLIC,publication_state:STATE,frozen_release:{version:RELEASE,immutable:true,release_date:'2026-08-11',cutoff_inclusive_through:'2026-06-30',article_audit_records:346,structure_phase_rows:878,core_included_structure_rows:816},current_curated:{revision:9,curated_through:'2026-08-19',architecture:'full-current-atomic-structure-snapshot',article_audit_records:383,chemically_included_articles:372,canonical_verified_articles:369,structure_phase_rows:947,core_included_structure_rows:887,resolved_space_group_rows:744,verified_space_group_rows:717,verified_polar_rows:101,strict_polar_rows:91,strict_polar_articles:57,rag_documents:1330,rag_embedded:1330,taxonomy_rows:947,motif_resolved_rows:640,motif_unresolved_rows:307},runtime:{site_version:SITE,ui_version:UI,meta_version:META,public_data_version:PUBLIC_DATA,photophysics_contract_version:PH,organic_components_contract_version:OC,smart_rag_version:RAG,research_assistant_version:ASSISTANT,motif_atlas_version:'1.2'},photophysics:{policy:'two_pass_verified_or_verified_no_reported_data',article_queue:383,two_pass_verified_articles:329,verified_no_data_articles:54,publishable_samples:940,publishable_measurements:2275,publishable_values:3002,analysis_eligible_values:280,publishable_mechanism_claims:478,conflict_rows:66,nonterminal_conflicts:0},organic_components:{contract_version:OC,database_authority:true,representation_rows:965,represented_structures:908,verified_connectivity_rows:61,unresolved_rows:894,not_applicable_rows:10,connectivity_fail_closed:true},public_access:{mode:'query-and-view',governance_state:STATE,indexing:'disabled-prepublication',bulk_export:false,primary_pdf_si_cif:false,raw_evidence_locators:false}}}
function citation(){const body=fs.readFileSync(CITATION_PATH,'utf8');if(!/^cff-version:\s*1\.2\.0/m.test(body))throw Error('CITATION contract missing');return body}
export default async function handler(req,res){if(!['GET','HEAD'].includes(req.method)){res.statusCode=405;res.setHeader('Allow','GET, HEAD');return res.end('Method Not Allowed')}try{const u=new URL(req.url,PUBLIC),asset=String(u.searchParams.get('asset')||u.searchParams.get('action')||'health').toLowerCase();let body,status=200,type='application/json; charset=utf-8';if(asset==='health'||asset==='health.json'){const x=await runtime('health');body=JSON.stringify({...x,site_version:SITE,ui_version:UI,meta_version:META,public_data_version:PUBLIC_DATA,photophysics_contract_version:PH,organic_components_contract_version:OC,smart_rag_version:RAG,research_assistant_version:ASSISTANT,current_curated_revision:9,publication_state:STATE})}else if(asset==='manifest'||asset==='release-manifest.json'){body=JSON.stringify(manifest(),null,2)}else if(asset==='citation'||asset==='citation.cff'||asset==='cff'){type='text/plain; charset=utf-8';body=citation()}else if(asset==='robots'||asset==='robots.txt'){type='text/plain; charset=utf-8';body='User-agent: *\nAllow: /\nDisallow: /api/\n# Prepublication review: indexing disabled by response and page-level noindex directives.\n'}else{status=404;body=JSON.stringify({error:'unknown metadata asset'})}res.statusCode=status;for(const[k,v]of Object.entries(headers(type)))res.setHeader(k,v);if(req.method==='HEAD')return res.end();return res.end(body)}catch(e){console.error('[meta-r9]',e);res.statusCode=503;res.setHeader('Retry-After','30');for(const[k,v]of Object.entries(headers()))res.setHeader(k,v);return res.end(JSON.stringify({ok:false,error:'CuHalide Atlas metadata service is temporarily unavailable.',release:RELEASE,current_curated_revision:9,publication_state:STATE}))}}
