import fs from 'node:fs';
import path from 'node:path';
const CONTRACT='https://tyxnyjyrfzspwcfjpzus.supabase.co/functions/v1/cuhalide-atlas-runtime-contract-v1-public';
const PUBLIC='https://cuhalide-atlas-v3.vercel.app',RELEASE='3.0.2',SITE='52',UI='52.0',META='52.1',PUBLIC_DATA='2.18.0',PH='1.4.0',OC='1.2.0',SEMANTIC='10.0.0',CUXPLORE='10.6.0',KNOWLEDGE='1.3.0',REV='10',STATE='prepublication-review';
const SOURCE_INDEX={release:'cuxplore-fulltext-v2-20260924',indexed_through:'2026-09-24',literature_articles:410,catalog_doi_records:410,doi_records:403,fulltext_doi_records:403,documents:727,characters:21421324,text_blocks:6275,native_text_files:664,sparse_text_files:6,empty_or_unreadable_files:57,active_catalog_dois:384,active_catalog_blocks:6175,raw_source_text_exposed:false,semantic_index_separate:true,denominator_note:'410 = the DOI-deduplicated literature corpus. 403 of those articles are represented in full-text v2; full-text coverage is not a second article corpus.'};
const CIF_RECONCILIATION={release:'cif-reconciliation-20260924',updated_at:'2026-09-24',registered_files:114,parsed_files:114,cu_structure_blocks:237,identity_review_rows:29,identity_resolved_rows:26,quarantined_rows:3,dimensionality_flags:10,dimensionality_adjudicated:10,authority_rows:939,core_included_rows:901,authority_overwritten:false};
const CITATION_PATH=path.join(process.cwd(),'CITATION.cff');
const RUNTIME_TTL_MS=30000;let runtimeCache=null,runtimePromise=null;const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const headers=(ct='application/json; charset=utf-8')=>({'Content-Type':ct,'Cache-Control':'no-store, max-age=0','X-Robots-Tag':'noindex, nofollow, noarchive','X-Content-Type-Options':'nosniff','X-CuHalide-Release':RELEASE,'X-CuHalide-Site-Version':SITE,'X-CuHalide-UI-Version':UI,'X-CuHalide-Meta-Version':META,'X-CuHalide-Public-Data-Version':PUBLIC_DATA,'X-CuHalide-Photophysics-Contract':PH,'X-CuHalide-Organic-Components-Contract':OC,'X-CuHalide-CuXplore-Version':CUXPLORE,'X-CuHalide-Knowledge-Contract':KNOWLEDGE,'X-CuHalide-RAG-Version':SEMANTIC,'X-CuHalide-Assistant-Version':CUXPLORE,'X-CuHalide-Current-Curated-Revision':REV,'X-CuHalide-Publication-State':STATE});
async function runtime(action='health'){
 const now=Date.now();if(action==='health'&&runtimeCache?.expiresAt>now)return runtimeCache.value;if(action==='health'&&runtimePromise)return runtimePromise;
 const work=(async()=>{let lastError=null;for(let attempt=0;attempt<3;attempt++){const u=new URL(CONTRACT);u.searchParams.set('action',action);try{const r=await fetch(u,{headers:{accept:'application/json','user-agent':'CuHalide-Atlas-Meta/52.0'},signal:AbortSignal.timeout(attempt===0?6000:attempt===1?8000:10000)}),raw=await r.text();let x;try{x=JSON.parse(raw)}catch{x={ok:false,error:'invalid runtime health response'}};if(r.ok&&x?.ok===true)return x;lastError=Error(`runtime contract ${r.status}`);if(r.status<500&&r.status!==429)break}catch(error){lastError=error}if(attempt<2)await sleep(180*(attempt+1))}throw lastError||Error('runtime contract unavailable')})();
 if(action!=='health')return work;
 runtimePromise=work.then(value=>{runtimeCache={value,expiresAt:Date.now()+RUNTIME_TTL_MS};runtimePromise=null;return value}).catch(error=>{runtimePromise=null;throw error});
 return runtimePromise
}
function manifest(){return{
 schema_version:'2.6',
 project:'CuHalide Atlas',
 public_origin:PUBLIC,
 publication_state:STATE,
 frozen_release:{version:RELEASE,immutable:true,release_date:'2026-08-11',cutoff_inclusive_through:'2026-06-30',date_note:'The scientific cutoff (30 June 2026) and archived release date (11 August 2026) are distinct.',article_audit_records:346,structure_phase_rows:878,core_included_structure_rows:816},
 current_curated:{revision:10,curated_through:'2026-09-14',architecture:'full-current-atomic-structure-snapshot',article_audit_records:383,chemically_included_articles:372,canonical_verified_articles:372,structure_phase_rows:939,core_included_structure_rows:901,resolved_space_group_rows:761,verified_space_group_rows:734,verified_polar_rows:101,strict_polar_rows:94,strict_polar_articles:60,taxonomy_rows:939,motif_resolved_rows:677,motif_unresolved_rows:262,motif_geometry_resolved_rows:286,denominator_note:'The public literature corpus contains 410 DOI-deduplicated articles. The 383/372 fields below are retained only as structured-data revision provenance, not as alternative article-corpus totals. 939 = structure/phase authority rows; 901 = Core-Included public curated rows.'},
 cuxplore:{version:CUXPLORE,knowledge_contract:KNOWLEDGE,semantic_index_version:SEMANTIC,semantic_records:1322,semantic_embedded:1322,source_index:SOURCE_INDEX},
 cif_reconciliation:CIF_RECONCILIATION,
 runtime:{site_version:SITE,ui_version:UI,meta_version:META,public_data_version:PUBLIC_DATA,photophysics_contract_version:PH,organic_components_contract_version:OC,motif_atlas_version:'1.2'},
 photophysics:{policy:'two_pass_verified_or_verified_no_reported_data',article_queue:383,two_pass_verified_articles:329,verified_no_data_articles:54,publishable_samples:941,publishable_measurements:2278,publishable_values:3002,analysis_eligible_values:280,publishable_mechanism_claims:478,conflict_rows:66,nonterminal_conflicts:0},
 organic_components:{contract_version:OC,database_authority:true,representation_rows:968,represented_structures:911,verified_connectivity_rows:61,unresolved_rows:897,not_applicable_rows:10,connectivity_fail_closed:true},
 public_access:{mode:'query-and-view',governance_state:STATE,indexing:'disabled-prepublication',bulk_export:false,primary_pdf_si_cif:false,raw_evidence_locators:false}
}}
function citation(){const body=fs.readFileSync(CITATION_PATH,'utf8');for(const required of [/^cff-version:\s*1\.2\.0/m,/Current Curated rev\.10 \(prepublication review\)/,/Structured Photophysics 1\.4\.0/,/Organic Components 1\.2\.0/])if(!required.test(body))throw Error(`CITATION rev.10 contract missing: ${required}`);if(/Current Curated rev\.[1-9]\b/.test(body))throw Error('stale pre-rev10 citation metadata');return body}
export default async function handler(req,res){if(!['GET','HEAD'].includes(req.method)){res.statusCode=405;res.setHeader('Allow','GET, HEAD');return res.end('Method Not Allowed')}try{const u=new URL(req.url,PUBLIC),asset=String(u.searchParams.get('asset')||u.searchParams.get('action')||'health').toLowerCase();let body,status=200,type='application/json; charset=utf-8';if(asset==='health'||asset==='health.json'){const x=await runtime('health');const {smart_rag,research_assistant,...base}=x;const semanticRecords=Number(smart_rag?.active_current_documents||x?.current_curated?.counts?.rag_documents||1322),semanticEmbedded=Number(smart_rag?.active_current_embedded||x?.current_curated?.counts?.rag_embedded||1322);body=JSON.stringify({...base,site_version:SITE,ui_version:UI,meta_version:META,public_data_version:PUBLIC_DATA,photophysics_contract_version:PH,organic_components_contract_version:OC,current_curated_revision:10,cuxplore:{ok:(smart_rag?.ok!==false)&&(research_assistant?.ok!==false),version:CUXPLORE,knowledge_contract:KNOWLEDGE,semantic_index_version:SEMANTIC,semantic_records:semanticRecords,semantic_embedded:semanticEmbedded,source_index:SOURCE_INDEX},cif_reconciliation:CIF_RECONCILIATION,site_probe_mode:'frontend v52 active; Current Curated rev.10; CuXplore source index 2026-09-24',publication_state:STATE})}else if(asset==='manifest'||asset==='release-manifest.json'){body=JSON.stringify(manifest(),null,2)}else if(asset==='citation'||asset==='citation.cff'||asset==='cff'){type='text/plain; charset=utf-8';body=citation()}else if(asset==='robots'||asset==='robots.txt'){type='text/plain; charset=utf-8';body='User-agent: *\nAllow: /\nDisallow: /api/\n# Prepublication review: indexing disabled by response and page-level noindex directives.\n'}else{status=404;body=JSON.stringify({error:'unknown metadata asset'})}res.statusCode=status;for(const[k,v]of Object.entries(headers(type)))res.setHeader(k,v);if(req.method==='HEAD')return res.end();return res.end(body)}catch(e){console.error('[meta-rev10]',e);res.statusCode=503;res.setHeader('Retry-After','30');for(const[k,v]of Object.entries(headers()))res.setHeader(k,v);return res.end(JSON.stringify({ok:false,error:'CuHalide Atlas metadata service is temporarily unavailable.',release:RELEASE,current_curated_revision:10,publication_state:STATE}))}}
