import crypto from 'node:crypto';
import currentMotifs from './motifs.js';
const REV='9',SITE='51',UI='51.0',STATE='prepublication-review';
const all=(s,a,b)=>String(s).split(a).join(b);
function patch(body){if(typeof body!=='string')return body;let x=body;for(const a of ['Current Curated rev.8','Current Curated rev.7','Current Curated rev.6'])x=all(x,a,'Current Curated rev.9');for(const a of ['current-r8','current-r7','current-r6'])x=all(x,a,'current-r9');for(const a of ['rev.8','rev.7','rev.6'])x=all(x,a,'rev.9');for(const a of ['Rev.8','Rev.7','Rev.6'])x=all(x,a,'Rev.9');x=all(x,'content="8"','content="9"');x=all(x,'946-row taxonomy','947-row taxonomy');x=all(x,'946 structure rows','947 structure rows');x=all(x,'946-row Current Curated snapshot','947-row Current Curated snapshot');if(/\brev\.[678]\b/i.test(x))throw new Error('stale current-curated revision in Motif Atlas');return x}
function hashes(html){const out=[],re=/<script\b([^>]*)>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(String(html)))){if(/\bsrc\s*=/i.test(m[1]))continue;out.push(`'sha256-${crypto.createHash('sha256').update(m[2]).digest('base64')}'`)}return[...new Set(out)]}
function syncCsp(html,res){const c=String(res.getHeader?.('Content-Security-Policy')||'');if(!c)return;const hs=hashes(html);if(!hs.length)return;let next=c;if(/script-src\s+[^;]*;/i.test(next))next=next.replace(/script-src\s+[^;]*;/i,`script-src ${hs.join(' ')};`);if(/style-src\s+[^;]*;/i.test(next)){const style=String(html).match(/<style>([\s\S]*?)<\/style>/i)?.[1];if(style){const h=`'sha256-${crypto.createHash('sha256').update(style).digest('base64')}'`;next=next.replace(/style-src\s+[^;]*;/i,`style-src ${h};`)}}res.setHeader('Content-Security-Policy',next)}
export default async function handler(req,res){
  res.setHeader('X-CuHalide-Current-Curated-Revision',REV);res.setHeader('X-CuHalide-Site-Version',SITE);res.setHeader('X-CuHalide-UI-Version',UI);res.setHeader('X-CuHalide-Publication-State',STATE);
  const bridge={setHeader:(k,v)=>{const n=String(k).toLowerCase();if(n==='x-cuhalide-current-curated-revision')v=REV;if(n==='x-cuhalide-site-version')v=SITE;if(n==='x-cuhalide-ui-version')v=UI;if(n==='x-cuhalide-publication-state')v=STATE;return res.setHeader(k,v)},getHeader:k=>res.getHeader?.(k),removeHeader:k=>res.removeHeader?.(k),end:body=>{const out=patch(body);if(typeof out==='string'&&out.includes('</html>'))syncCsp(out,res);res.removeHeader?.('Content-Length');return res.end(out)}};
  Object.defineProperty(bridge,'statusCode',{get:()=>res.statusCode,set:v=>{res.statusCode=v}});return currentMotifs(req,bridge)
}
