import {normalizePhotophysicsVersion} from '../lib/photophysics-contract.js';

const DATA_UPSTREAM='https://tyxnyjyrfzspwcfjpzus.supabase.co/functions/v1/cuhalide-atlas-public-data-v3';
const CONTRACT_UPSTREAM='https://tyxnyjyrfzspwcfjpzus.supabase.co/functions/v1/cuhalide-atlas-runtime-contract-v1-public';
const PUBLIC_ORIGIN='https://cuhalide-atlas-v3.vercel.app';
const PUBLIC_DATA_VERSION='2.16.0';
const CURRENT_REVISION='7';
const ORGANIC_COMPONENTS_CONTRACT='1.1.0';
const PUBLICATION_STATE='prepublication-review';
const PUBLIC_ACTIONS=new Set(['health','bootstrap','articles','structures','polar','article','structure','article-structures','search','current-curated','candidates','status','errata','motifs','photophysics-health','photophysics','organic-components-health','organic-components']);
const PHOTOPHYSICS_ACTIONS=new Set(['photophysics-health','photophysics','article','structure']);
const TOTAL_TIMEOUT_MS=12000,FIRST_ATTEMPT_TIMEOUT_MS=5000,RETRY_DELAY_MS=120;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function targetUrl(incoming){const action=String(incoming.searchParams.get('action')||'health').toLowerCase(),control=action==='health'||action==='bootstrap',upstream=new URL(control?CONTRACT_UPSTREAM:DATA_UPSTREAM);for(const[key,value]of incoming.searchParams.entries()){if(key==='action'&&action==='health')continue;upstream.searchParams.append(key,value)}if(action==='health')upstream.searchParams.set('action','public-health');if(action==='motifs'){const limit=Math.max(1,Math.min(24,Number(upstream.searchParams.get('limit')||24)||24));upstream.searchParams.set('limit',String(limit))}return upstream}
async function fetchSnapshot(url,req){const started=Date.now();let last=null,lastError=null;for(let attempt=0;attempt<2;attempt++){const remaining=TOTAL_TIMEOUT_MS-(Date.now()-started);if(remaining<=250){if(last)return last;throw lastError||new Error('Public data timeout')}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),attempt===0?Math.min(FIRST_ATTEMPT_TIMEOUT_MS,remaining):remaining);try{const response=await fetch(url,{method:req.method,headers:{accept:req.headers.accept||'application/json','user-agent':req.headers['user-agent']||`CuHalide-Atlas-Vercel-Public-Data/${PUBLIC_DATA_VERSION}`},redirect:'follow',signal:controller.signal}),body=req.method==='HEAD'?'':await response.text(),snapshot={status:response.status,headers:response.headers,body};last=snapshot;const retryable=response.status===429||response.status>=500;if(!retryable||attempt===1)return snapshot}catch(e){lastError=e;if(attempt===1){if(last)return last;throw e}}finally{clearTimeout(timer)}await sleep(RETRY_DELAY_MS)}if(last)return last;throw lastError||new Error('Public data backend failed')}
function commonHeaders(res){res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Robots-Tag','noindex, nofollow, noarchive');res.setHeader('X-CuHalide-Public-Access','query-and-view');res.setHeader('X-CuHalide-Publication-State',PUBLICATION_STATE);res.setHeader('X-CuHalide-Public-Data-Version',PUBLIC_DATA_VERSION);res.setHeader('X-CuHalide-Current-Curated-Revision',CURRENT_REVISION);res.setHeader('X-CuHalide-Organic-Components-Contract',ORGANIC_COMPONENTS_CONTRACT)}
function parsedBody(snapshot){if(!snapshot?.body)return null;try{return JSON.parse(snapshot.body)}catch{return null}}
function snapshotPhotophysicsVersion(action,snapshot){
  if(!PHOTOPHYSICS_ACTIONS.has(action)||snapshot.status!==200)return null;
  const headerVersion=normalizePhotophysicsVersion(snapshot.headers?.get?.('x-cuhalide-photophysics-contract'));
  const body=parsedBody(snapshot);
  let bodyVersion=null;
  if(action==='photophysics-health'||action==='photophysics')bodyVersion=normalizePhotophysicsVersion(body?.version);
  else if(body?.photophysics&&typeof body.photophysics==='object')bodyVersion=normalizePhotophysicsVersion(body.photophysics.version);
  if(bodyVersion&&headerVersion&&bodyVersion!==headerVersion)throw new Error(`photophysics contract mismatch: body ${bodyVersion}, header ${headerVersion}`);
  const version=bodyVersion||headerVersion;
  if((action==='photophysics-health'||action==='photophysics')&&!version)throw new Error(`missing or unsupported photophysics contract for ${action}`);
  if(body?.photophysics&&typeof body.photophysics==='object'&&!version)throw new Error(`missing or unsupported attached photophysics contract for ${action}`);
  return version;
}
function annotateArticleContext(incoming,snapshot,photoVersion){if(snapshot.status!==200||String(incoming.searchParams.get('action')||'').toLowerCase()!=='article'||!snapshot.body)return snapshot.body;let x;try{x=JSON.parse(snapshot.body)}catch{return snapshot.body}if(!x?.item||typeof x.item!=='object')return snapshot.body;const origin=String(x.data_scope||'unresolved'),originRevision=Number(x.item.live_revision||0),hasPhoto=x.photophysics&&typeof x.photophysics==='object';x.record_context={serving_context:'current_curated',serving_revision:Number(CURRENT_REVISION),core_record_origin:origin,core_record_origin_release:origin==='frozen_release'?'3.0.2':null,core_record_origin_revision:originRevision>0?originRevision:null,attached_photophysics_context:hasPhoto?'current_curated':null,attached_photophysics_contract:hasPhoto?photoVersion:null,context_policy:'core_origin_preserved_current_overlays_explicit'};return JSON.stringify(x)}
export default async function handler(req,res){commonHeaders(res);if(!['GET','HEAD'].includes(req.method)){res.statusCode=405;res.setHeader('Allow','GET, HEAD');return res.end('Method Not Allowed')}try{const incoming=new URL(req.url,PUBLIC_ORIGIN),action=String(incoming.searchParams.get('action')||'health').toLowerCase();if(!PUBLIC_ACTIONS.has(action)){res.statusCode=404;res.setHeader('Content-Type','application/json; charset=utf-8');if(req.method==='HEAD')return res.end();return res.end(JSON.stringify({ok:false,error:'unknown public action',publication_state:PUBLICATION_STATE}))}const snapshot=await fetchSnapshot(targetUrl(incoming),req),photoVersion=snapshotPhotophysicsVersion(action,snapshot);res.statusCode=snapshot.status;res.setHeader('Content-Type',snapshot.headers.get('content-type')||'application/json; charset=utf-8');if(photoVersion)res.setHeader('X-CuHalide-Photophysics-Contract',photoVersion);const rel=snapshot.headers.get('x-cuhalide-release');if(rel)res.setHeader('X-CuHalide-Release',rel);if(snapshot.status===429||snapshot.status>=500)res.setHeader('Retry-After',snapshot.headers.get('retry-after')||'30');if(req.method==='HEAD')return res.end();return res.end(annotateArticleContext(incoming,snapshot,photoVersion))}catch(error){console.error('[public-data-v50.2-prepublication-hardening]',error);res.statusCode=503;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Retry-After','30');res.setHeader('X-CuHalide-Release','3.0.2');if(req.method==='HEAD')return res.end();return res.end(JSON.stringify({error:'CuHalide Atlas public data backend is temporarily unavailable.',release:'3.0.2',version:PUBLIC_DATA_VERSION,publication_state:PUBLICATION_STATE,organic_components_contract:ORGANIC_COMPONENTS_CONTRACT,public_access:'query-and-view'}))}}