const DATA_UPSTREAM='https://tyxnyjyrfzspwcfjpzus.supabase.co/functions/v1/cuhalide-atlas-public-data-v302-public';
const CONTRACT_UPSTREAM='https://tyxnyjyrfzspwcfjpzus.supabase.co/functions/v1/cuhalide-atlas-runtime-contract-v1-public';
const PUBLIC_ORIGIN='https://cuhalide-atlas-v3.vercel.app';
const PUBLIC_DATA_VERSION='2.13.0';
const CURRENT_REVISION='7';
const TOTAL_TIMEOUT_MS=12000,FIRST_ATTEMPT_TIMEOUT_MS=5000,RETRY_DELAY_MS=120;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function targetUrl(incoming){const action=String(incoming.searchParams.get('action')||'health').toLowerCase(),control=action==='health'||action==='bootstrap',upstream=new URL(control?CONTRACT_UPSTREAM:DATA_UPSTREAM);for(const[key,value]of incoming.searchParams.entries()){if(key==='action'&&action==='health')continue;upstream.searchParams.append(key,value)}if(action==='health')upstream.searchParams.set('action','public-health');return upstream}
async function fetchSnapshot(url,req){const started=Date.now();let last=null,lastError=null;for(let attempt=0;attempt<2;attempt++){const remaining=TOTAL_TIMEOUT_MS-(Date.now()-started);if(remaining<=250){if(last)return last;throw lastError||new Error('Public data timeout')}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),attempt===0?Math.min(FIRST_ATTEMPT_TIMEOUT_MS,remaining):remaining);try{const response=await fetch(url,{method:req.method,headers:{accept:req.headers.accept||'application/json','user-agent':req.headers['user-agent']||`CuHalide-Atlas-Vercel-Public-Data/${PUBLIC_DATA_VERSION}`},redirect:'follow',signal:controller.signal}),body=req.method==='HEAD'?'':await response.text(),snap={status:response.status,headers:response.headers,body};last=snap;const retryable=response.status===429||response.status>=500;if(!retryable||attempt===1)return snap}catch(e){lastError=e;if(attempt===1){if(last)return last;throw e}}finally{clearTimeout(timer)}await sleep(RETRY_DELAY_MS)}if(last)return last;throw lastError||new Error('Public data backend failed')}
function commonHeaders(res){res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Robots-Tag','noindex, nofollow');res.setHeader('X-CuHalide-Public-Access','query-and-view');res.setHeader('X-CuHalide-Public-Data-Version',PUBLIC_DATA_VERSION);res.setHeader('X-CuHalide-Current-Curated-Revision',CURRENT_REVISION)}
export default async function handler(req,res){if(!['GET','HEAD'].includes(req.method)){res.statusCode=405;res.setHeader('Allow','GET, HEAD');return res.end('Method Not Allowed')}try{const incoming=new URL(req.url,PUBLIC_ORIGIN),snapshot=await fetchSnapshot(targetUrl(incoming),req);res.statusCode=snapshot.status;res.setHeader('Content-Type',snapshot.headers.get('content-type')||'application/json; charset=utf-8');commonHeaders(res);const rel=snapshot.headers.get('x-cuhalide-release');if(rel)res.setHeader('X-CuHalide-Release',rel);if(snapshot.status===429||snapshot.status>=500)res.setHeader('Retry-After',snapshot.headers.get('retry-after')||'30');if(req.method==='HEAD')return res.end();return res.end(snapshot.body)}catch(error){console.error('[public-data-v50.2]',error);res.statusCode=503;res.setHeader('Content-Type','application/json; charset=utf-8');commonHeaders(res);res.setHeader('Retry-After','30');res.setHeader('X-CuHalide-Release','3.0.2');if(req.method==='HEAD')return res.end();return res.end(JSON.stringify({error:'CuHalide Atlas public data backend is temporarily unavailable.',release:'3.0.2',version:PUBLIC_DATA_VERSION,public_access:'query-and-view'}))}}
